### ISSUE TITLE
Installation blocked by antivirus

### ISSUE THREAD

**Issue by jawad-lotfi** [dotnet/vscode-dotnet-runtime#1036]
Hello
Each time I open Visual Studio Code in a C# or .NET project folder, the task to download and install the .NET runtime executes and is blocked by the antivirus we have at our workplace.
I already have installed dotnet manually and configured the extension to use the local installation, however, I have those error messages at each startup which is very annoying.
I am using other extensions such as the official C# and C# Dev Kits that prevent the uninstallation of this extension as well.
I cannot disable the antivirus either since it is managed by our IT administrator.
What can I do to disable the error messages, or even better disable the download and installation of the runtime altogether?

**Comment by baronfel** [comment]
There's a VSCode setting that you can set to tell this extension that you already have a runtime installed: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#manually-installing-net. Can you try that and see 
if it solves your need?

**Comment by jawad-lotfi** [comment]
Thank you for answering.
I have set the local path manually as indicated in that url, however, I still get the following error notifications every time even though I can code and test my programs just fine:
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/70293662/4d497e6a-9166-47e1-82d3-c36f2f2ba131)
![Screenshot 2023-07-17 154804](https://github.com/dotnet/vscode-dotnet-runtime/assets/70293662/7ce8c556-049a-42c6-9719-039e2bf458ea)

I thought that setting the path to dotnet manually would prevent the extension from attempting an installation from the online source, but it doesn't.

**Comment by baronfel** [comment]
We're tracking this here https://github.com/dotnet/vscode-dotnet-runtime/issues/1009 - I'm going to close this as a duplicate.
