### ISSUE TITLE
Error! The "file" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by Den4ik-dev** [dotnet/vscode-dotnet-runtime#1069]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /home/user/.config/Code/logs/20230716T224051/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1689537465254.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by n6v26r** [comment]
yep! same issue on vscode.

**Comment by baronfel** [comment]
Closing as duplicate.
