### ISSUE TITLE
vsCode keeps asking for already installed dotnet 7

### ISSUE THREAD

**Issue by mlanca** [dotnet/vscode-dotnet-runtime#1074]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /home/mikel/.var/app/com.visualstudio.code/config/Code/logs/20230716T185909/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1689548351287.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by socrates-yxh** [comment]
I have the same problem.

**Comment by khaimed** [comment]
me too.
