### ISSUE TITLE
Powershell command failed

### ISSUE THREAD

**Issue by pascal-pst** [dotnet/vscode-dotnet-runtime#108]
[DotNetAcquisition1596186572122.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/5006171/DotNetAcquisition1596186572122.txt)

**Comment by sfoslund** [comment]
Hi @pascal-pst, thanks for including the log file! I'm going to update the issue title and content to reflect the error we see there.

**Comment by sfoslund** [comment]
@pascal-pst is this failure still occurring with more recent versions of the extension?

**Comment by sfoslund** [comment]
Closing this due to age, please reopen if you're still seeing this issue, thanks!
