### ISSUE TITLE
why do you always try to download even I have installed the version

### ISSUE THREAD

**Issue by heartacker** [dotnet/vscode-dotnet-runtime#1105]
Downloading the .NET Runtime.
Downloading .NET version(s) 7.0.9 ...Downloading the .NET Runtime.
 -- Concurrent download of '6.0.20' started!

Downloading .NET version(s) 7.0.9, 6.0.20 .........................

![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1876302/6eaeb9e3-21ee-4049-bee4-a37353b747ef)

![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1876302/4225235a-4163-4caa-8639-518530bacd6f)

**Comment by socrates-yxh** [comment]
I have the same issue.

**Comment by TomSmith2021** [comment]
I have the same issue in Mac M1 Pro
