### ISSUE TITLE
Code lens references do not work in the variables

### ISSUE THREAD

**Issue by juanvaquero** [dotnet/vscode-dotnet-runtime#1167]
Type: <b>Bug</b>

Since yesterday August 3, 2023, I upgraded to the new Visual Studio Editor package in Unity, and installed the new Unity extension released on the same day. I do not see the references in the variables of the scripts, but I do see those of the classes and methods. I can also "access" the reference menu of a variable if I double click on it holding control/(Command in Mac).

Could you give me a solution to be able to have the references working in the variables too?

Thank you very much in advance.

Extension version: 1.6.0
VS Code version: Code 1.81.0 (Universal) (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.32GB free)|
|Process Argv|--crash-reporter-id 9a37cff7-e87a-4abc-bec7-dc4de918911b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by baronfel** [comment]
Hi @juanvaquero - this repo isn't for the Unity extension at all, it's a utility extension for acquiring the .NET SDK and Runtime. I think you'll find more answers if you open this at their repo here: https://github.com/microsoft/vscode-dotnettools/issues.

**Comment by juanvaquero** [comment]
Ok, yes you are right. Sorry for the confusion and thanks @baronfel.
