### ISSUE TITLE
Extension takes up all the CPUs on my Mac

### ISSUE THREAD

**Issue by IngageBrewerM** [dotnet/vscode-dotnet-runtime#1186]
Type: <b>Bug</b>

I used Extension Bisect to identify this extension as running all my CPUs to max on my Mac.  I have included the system and bisect info.

Extension version: 1.6.0
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T21:05:41.366Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 8c2a4963-89c9-46bc-97e5-c0f2e4bd9bac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by baronfel** [comment]
Any way you can pinpoint what we're supposedly doing? This extension just downloads a zip/tar and extracts it, so I'm a bit skeptical that would be pegging all your CPUs. Do you have any logs or anything from our extension to help narrow down the search space?

**Comment by IngageBrewerM** [comment]
Where would I find the logs for your extension?

**Comment by IngageBrewerM** [comment]
So, I uninstalled and reinstalled the `Base C#` extension, which reinstalled this extension, and I am not experiencing this issue any longer. Not sure why it was causing it prior to the reinstallation.  Thanks for the quick reply!
