### ISSUE TITLE
We should backport changes made for the ARM extension

### ISSUE THREAD

**Issue by StephenWeatherford** [dotnet/vscode-dotnet-runtime#12]
Shipping code here: https://github.com/microsoft/vscode-azurearmtools/tree/master/src/acquisition

The changes I made mostly fall into these categories:

1) Didn't want it to be an extension, and didn't want to expose the current commands (so as not to interfere with the eventual extension), so I made the code callable
2) Added telemetry in a few paths (ideally we need an API for that)
3) strict null checking/lint

Didn't have time to figure out how to properly made a fork and reference the fork from another repo, so I made a copy and modified the copy, but most filenames have renamed the same, so we could probably turn it into a fork and backport some of the changes if that would be useful.

**Comment by sfoslund** [comment]
#36 resolves the second item (Adding telemetry) and we don't plan on moving away from the extension model, so unless @StephenWeatherford has any other items we need to be aware of, this can be closed.

**Comment by StephenWeatherford** [comment]
Give me a couple of days to check...

**Comment by sfoslund** [comment]
It looks like all ARM changes have been backported. Feel free to file another issue if that isn't the case.
