### ISSUE TITLE
so stupid strategy to download .net runtime even if installed

### ISSUE THREAD

**Issue by lhrbu** [dotnet/vscode-dotnet-runtime#1206]
so you guys are intend to block developers to use vs code for c# development? otherwise why set such stupid strategy to download the runtime again and again from your poor server no matter.it is installed or not? more disgustingly, each time a new .net version release the extension just doesn't work until it download it via this approach from poor server, em you really don't want us to use vscode uh

**Comment by baronfel** [comment]
Thank you for this feedback. We're tracking your specific requests in other issues and working with the C# VSCode team in the meantime to motivate issues that users may be seeing.
