### ISSUE TITLE
.NET Acquisition Failed: Installation failed

### ISSUE THREAD

**Issue by lizanx** [dotnet/vscode-dotnet-runtime#1217]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /Users/lizan/Library/Application Support/Code/logs/20230810T143746/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1691649467497.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

Error Message:
 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/lizan/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/lizan/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10" -Version 7.0.10 -Runtime dotnet
/bin/sh: /Users/lizan/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/install scripts/dotnet-install.sh: Permission denied

Actually I already have .net7.0 installed:
```shell
dotnet --list-sdks
7.0.305 [/usr/local/share/dotnet/sdk]
7.0.400 [/usr/local/share/dotnet/sdk]
```

**Comment by lizanx** [comment]
Log File: 
[DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1691649467497.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/12309661/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1691649467497.txt)

**Comment by lizanx** [comment]
I didn't notice that the log file is empty.
I've fixed this error by executing VScode with sudo privilege, then the installation script succeeded.
But still, the new updates of the C# extension feels bad for now, it doesn't work as well as Omnisharp.
Where do I find the update details, please? The update log is very brief without necessary info about what the switch means.

**Comment by baronfel** [comment]
For details about the C# extension, you'll need to visit https://github.com/dotnet/vscode-csharp - that's where the C# extension is developed, issues are managed, etc.  This repo is just about SDK/Runtime acquisition.  We're working on a new version of this extension that will support re-using an existing .NET install, but the current version wasn't designed for that use case directly. You can check our docs [here](https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#manually-installing-net) for more information about how to tell this extension where to find your already-installed .NET install (and as a result, skip re-downloading).

**Comment by lizanx** [comment]
> For details about the C# extension, you'll need to visit https://github.com/dotnet/vscode-csharp - that's where the C# extension is developed, issues are managed, etc. This repo is just about SDK/Runtime acquisition. We're working on a new version of this extension that will support re-using an existing .NET install, but the current version wasn't designed for that use case directly. You can check our docs [here](https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#manually-installing-net) for more information about how to tell this extension where to find your already-installed .NET install (and as a result, skip re-downloading).

Thanks for reply!
