### ISSUE TITLE
Unable todisable or uninstall .NET Tools

### ISSUE THREAD

**Issue by vkuehn** [dotnet/vscode-dotnet-runtime#122]
The .Net Tools should only work with c# code. But nor every run only starts dotnetcore. I can not run powershell anymore in VS Code.
Therefore I wanted to uninstall or at least disable these tools but that ends in

Cannot disable extension '.NET Install Tool for Extension Authors'. Extension 'Azure Resource Manager (ARM) Tools' depends on this.
Cannot uninstall '.NET Install Tool for Extension Authors' extension. 'Azure Resource Manager (ARM) Tools' extension depends on this.

after uninstalling also all tools depending on .Net Tools and .Net Tools I have this in launch.json

The debug type is not recognized. Make sure that you have a corresponding debug extension installed and that it is enabled.(1)
for
"type": "coreclr",

How to properly uninstall and get my powershell debugger back ?

**Comment by sfoslund** [comment]
Thanks for filing an issue, can you give a little more detail? Why are you unable to run powershell with the extension installed?

> The debug type is not recognized. Make sure that you have a corresponding debug extension installed and that it is enabled.(1)
for
"type": "coreclr",

This error makes it sound like you're missing a required extension.

**Comment by vkuehn** [comment]
finally I got uninstalled everything .Net and not using VSCode for that anymore
