### ISSUE TITLE
[NETSDKE2E] It should not prompt error -undefined .NET version if cancel install .NET Runtime

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1227]
**[Environment]**
Extensions build: https://microsoft-my.sharepoint.com/personal/noahgilson_microsoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fnoahgilson%5Fmicrosoft%5Fcom%2FDocuments%2FNET%20SDK%20Acquisition%20Global%20VSIX%20Files&ga=1
VSCode: 1.81.1

**[Repro Steps]**
1. Install VSCode and extensions,
2. Run the 'Sample: Acquire .NET runtime' command, You should be asked to enter a Major.Minor version, then enter 'ESCape' to cancel.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/a40c250a-92f9-474a-957b-9a95c952cdd5)
3. Observe

**[Actual Result]**
An error popup in the bottom right corner of VSCode stating that cannot acquire .NET version "undefined"
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/e31ba0f8-ccdb-417d-9fad-06c64ca68c55)

**[Expected Result]**
1. It should not prompt error -undefined .NET version if cancel install .NET Runtime

**Comment by baronfel** [comment]
This isn't a real issue - the sample extension is just a sample and its error behavior is not representative of actual users of this extension's API.
