### ISSUE TITLE
there's an issue when i try to run a c# coding. 

### ISSUE THREAD

**Issue by ViniciusKendy17** [dotnet/vscode-dotnet-runtime#1229]
I'm trying to run a c# coding for the fisrt time, and i already installed all the extensions and the .net. however, when i run the code, the following message shows up = **spawn C:\MinGW\bin\cmd.exe ENOENT**. Does anyone know what i should do ?

`Downloading the .NET Runtime.
Using configured .NET path: C:\Program Files\dotnet\dotnet.exe
Downloading the .NET Runtime.
Downloading .NET version(s) 7.0.10 ... Error!
Failed to download .NET 7.0.10:
spawn C:\MinGW\bin\cmd.exe ENOENT

 Error!
.NET Acquisition Failed: Installation failed: Error: spawn C:\MinGW\bin\cmd.exe ENOENT`

**Comment by nagilson** [comment]
Hm, can you try running in a cmd C:\MinGW\bin\cmd.exe and see what it says? I am surprised it is trying to find a cmd in MinGW.

**Comment by ViniciusKendy17** [comment]
i've already fixed this issue, i was surprised as well man, i believe that the path was wrong, then i changed it and it worked out.
even though, i appreciate for trying to help me out.

**Comment by nagilson** [comment]
Awesome, glad its working now. Thanks!
