### ISSUE TITLE
Set existingDotnetPath for all extensions?

### ISSUE THREAD

**Issue by sliekens** [dotnet/vscode-dotnet-runtime#1240]
Hello,

I'm currently working on enhancements to the Dev Container feature to install .NET inside a Dev Container (https://github.com/devcontainers/features/pull/628).

One of my objectives is to simplify the configuration process for using the pre-installed .NET Runtime across all extensions by configuring `dotnetAcquisitionExtension.existingDotnetPath`.

### Current configuration

Currently I have this in my `devcontainer-feature.json`:

``` json
{
  "customizations": {
    "vscode": {
      "settings": {
        "dotnetAcquisitionExtension.existingDotnetPath": [
          {
            "extensionId": "ms-dotnettools.csharp",
            "path": "/usr/share/dotnet/dotnet"
          },
          {
            "extensionId": "ms-dotnettools.csdevkit",
            "path": "/usr/share/dotnet/dotnet"
          }
        ]
      }
    }
  }
}
```

I have identified a few problems with this configuration:

1. I need to know ahead of time which extensions will require .NET and add them to the array in `devcontainer-feature.json`
2. If a user wants to add an extension to the configuration in their own `devcontainer.json`, it will overwrite the existing configuration from `devcontainer-feature.json`. This leads to complete replacement, rather than merging.

### Ideal configuration approach

I would like a simplified configuration for both current and future extensions. Here are the proposed alternatives, any of which would help me achieve my goal:

1. Simplified global configuration

``` json
{
    "dotnetAcquisitionExtension.existingDotnetPath": "/usr/share/dotnet/dotnet"
}
```

2. Using a wildcard to keep the configuration schema intact

``` json
{
  "dotnetAcquisitionExtension.existingDotnetPath": [
    {
      "extensionId": "*",
      "path": "/usr/share/dotnet/dotnet"
    }
  ]
}
```

3. Support object syntax to facilitate configuration merging

``` json

{
  "dotnetAcquisitionExtension.existingDotnetPath": {
    "ms-dotnettools.csharp": "/usr/share/dotnet/dotnet",
    "ms-dotnettools.csdevkit": "/usr/share/dotnet/dotnet"
  }
}
```
Thanks for your time and consideration.

**Comment by baronfel** [comment]
This is a useful idea, but I think it's almost entirely unnecessary with the next major version of this extension, which optionally allows for using the standard globally-installed .NET SDK/Runtime instead of per-extension.

**Comment by sliekens** [comment]
Closing as I haven't had any issues with newer versions of the extensions.

**Comment by nagilson** [comment]
Thanks for reporting its been better for you, and for the thorough write-up. Your points are well-considered. Even though youve closed this I do actually think there is still some value in this, people get confused about why they need to set both for C# devkit. There are more major UX and other reliability improvements Id prioritize over this, but its definitely worth our consideration.

**Comment by nagilson** [comment]
this was added :)

**Comment by sliekens** [comment]
Nice work 👊

**Comment by nagilson** [comment]
Thanks 😄  It's been around for a long time now, just forgot to update the issue..
