### ISSUE TITLE
Changelog for ".NET Install Tool for Extension Authors" extension

### ISSUE THREAD

**Issue by lonix1** [dotnet/vscode-dotnet-runtime#1250]
VSCode's [.NET Install Tool for Extension Authors](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-runtime) is directed to this repo.

It has no changelog. Serious devs won't upgrade unless you tell them what's in the new version.

Please provide a changelog for the extension. If at all possible, please provide it in such a way that it is exposed in the vscode changelog tab (when viewing the extension).

Thank you.

**Comment by baronfel** [comment]
We should definitely do this. It's as simple as making sure there's a CHANGELOG.md file in the root of each extension we publish. Team, I'll take this on for getting started, then we can keep it updated as PRs get merged.
