### ISSUE TITLE
Unity compilation freezes VSCode's extentions for 3~5 seconds

### ISSUE THREAD

**Issue by jaoreir** [dotnet/vscode-dotnet-runtime#1259]
Type: <b>Bug</b>

## Reproduction steps

1. Open a unity project's script with VSCode
2. Edit the script so unity will recompile when switching back to the unity editor
3. After recompilation starts, switch back to VScode.
4. VSCode's extensions freezes for 3~5 seconds.

### Expected behaviour

VSCode's extensions works normally after unity compiles the c# code

### Actual behaviour

VSCode's extensions freezes for 3~5 seconds, then goes back to normal.

While frozen:
- Features not provided by the extensions work normally, e.g. navigating the files.
- The vim emulation extension does not respond to key strokes, instead it does them all at once when unfreezed. Sometimes it gets stuck on one of the keystrokes inputted while frozen, which is only fixed after a VSCode restart.
- The commit message that shows up after the current line provided by gitlens gets stuck on the line selected before compilation starts. Even after using the mouse to select another line, the commit message will not update.

Extension version: 1.7.0
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (5.10GB free)|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by baronfel** [comment]
Please reach out to the Unity VSCode extension for problems regarding that extension: https://marketplace.visualstudio.com/items?itemName=visualstudiotoolsforunity.vstuc
