### ISSUE TITLE
Error loading the ARM file

### ISSUE THREAD

**Issue by pawel-rozek** [dotnet/vscode-dotnet-runtime#129]
The issue text was copied to the clipboard.  Please paste it into this window.

**Repro steps:**

1.Open WSL (Ubuntu 20.04)
2. Navigate to the git repo directory
3. code .
4. Open azuredeploy.json file
[DotNetAcquisition1601910487969.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/5328237/DotNetAcquisition1601910487969.txt)

**Extension Version:** 0.1.2
**Error Message:** Dotnet Core Acquisition Failed: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.8" -Runtime dotnet -Version 3.1.8
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: 5: 
: not found
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

**Error Stack:** Error: Dotnet Core Acquisition Failed: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.8" -Runtime dotnet -Version 3.1.8
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: 5: 
: not found
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/extension.js:211:111243

**Comment by sfoslund** [comment]
Thanks for providing so much detail! It's possible that the extension is confused whether it is running on linux or windows. Does this file exist: /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh (replacing anonymous with your username)? If so, do you mind posting the content?

**Comment by pawel-rozek** [comment]
Yes it does exist, and its permissions 777 and the file is attached (zipped)
[dotnet-install.zip](https://github.com/dotnet/vscode-dotnet-runtime/files/5330096/dotnet-install.zip)

**Comment by sfoslund** [comment]
Thanks for the quick responses and details! I've been able to repro this and it appears to be a problem with linux vs windows line endings, when I convert to the right line endings it fixes the issue (see [this thread for converting](https://askubuntu.com/questions/966488/how-do-i-fix-r-command-not-found-errors-running-bash-scripts-in-wsl)). I'll look for a good way to fix this issue and try to get a PR in before our next release.
