### ISSUE TITLE
Windows 8.1 failed to downloading .NET 7

### ISSUE THREAD

**Issue by Alexey-B** [dotnet/vscode-dotnet-runtime#1299]
Fail to download .NET 7 on Windows 8.1 machine (version 7 does not supported on this OS) - keeps displaying the download message.

Log:
Downloading the .NET Runtime.
Using configured .NET path: C:\Program Files\dotnet\dotnet.exe
Downloading the .NET Runtime.
Downloading .NET version(s) 7.0.10 .....

More info:
The issue is similar to [68](https://github.com/dotnet/vscode-dotnet-runtime/issues/68) but setting “dotnetAcquisitionExtension.installTimeoutValue” to anything doesn't helps.

How to stop any autoupdates?

**Comment by baronfel** [comment]
See 'Manually Installing .NET' in [our docs](https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md) for the option I'd recommend.

**Comment by Alexey-B** [comment]
> See 'Manually Installing .NET' in [our docs](https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md) for the option I'd recommend.

Thanks for the answer!
I tried to install .NET SDK 7.0 manualy, but still without success.

Here is info from my dotnet:
C:\Program Files\dotnet>dotnet.exe --info
ПАКЕТ SDK ДЛЯ .NET:
 Version:   7.0.400
 Commit:    73bf45718d

Среда выполнения:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  2.2.300 [C:\Program Files\dotnet\sdk]
  6.0.316 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.
WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.
WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

And my settings.json for VSCode:
"dotnetAcquisitionExtension.existingDotnetPath": [
{
    "extensionId": "msazurermtools.azurerm-vscode-tools",
    "path": "C:\\Program Files\\dotnet\\dotnet.exe"
},
{
    "extensionId": "ms-dotnettools.csdevkit",
    "path": "C:\\Program Files\\dotnet\\dotnet.exe"
},
{
    "extensionId": "ms-dotnettools.vscodeintellicode-csharp",
    "path": "C:\\Program Files\\dotnet\\dotnet.exe"
},
{
    "extensionId": "ms-dotnettools.csharp",
    "path": "C:\\Program Files\\dotnet\\dotnet.exe"
},
{
    "extensionId": "ms-dotnettools.vscode-dotnet-runtime",
    "path": "C:\\Program Files\\dotnet\\dotnet.exe"
},
]

Still see:
Downloading the .NET Runtime.
Using configured .NET path: C:\Program Files\dotnet\dotnet.exe
Downloading the .NET Runtime.
Downloading .NET version(s) 7.0.10 .....

**Comment by baronfel** [comment]
Can you please include the detailed extension log? If you use the 'Report an issue with the .NET Install Tool for Extension Authors` command from the command palette you should get some additional instructions about how and where to find that log.

**Comment by Alexey-B** [comment]
I tried this, but the report is empty.
Looks like I figured it out. The problem was not in .NET Install Tool for Extension Authors, but in the dependent extension [Unity](https://marketplace.visualstudio.com/items?itemName=VisualStudioToolsForUnity.vstuc). The problem is related to [this](https://github.com/microsoft/vscode-dotnettools/issues/396) and [this](https://github.com/dotnet/vscode-csharp/issues/6004#issuecomment-1664353164).
Finally this setting helped me:
 {
    "extensionId": "visualstudiotoolsforunity.vstuc", 
    "path": "/usr/local/share/dotnet/dotnet"
}
Thanks for the help!

**Comment by baronfel** [comment]
Glad to hear it! We'll be working on the output logging to let users know _which_ extension is requesting the .NET Download so that users know which extension IDs to use in the configuration settings.
