### ISSUE TITLE
Extend script download/installation timeout to 10m

### ISSUE THREAD

**Issue by baronfel** [dotnet/vscode-dotnet-runtime#1301]
The current duration means that anyone with a < 8Mbps connection will never succeed - we need to extend this. 10 minutes widens the success pathway to those with ~5Mbps or greater connections.

**Comment by sailro** [comment]
I fully agree! I'm working on the Visual Studio Tools for Unity team, and we've seen multiple users complaining about this timeout value. We even added a note about this in our troubleshooting notes. `10m` seems to be a better choice indeed.

cc @jbevain 

Thanks!

**Comment by nagilson** [comment]
Resolved by https://github.com/dotnet/vscode-dotnet-runtime/pull/1320
