### ISSUE TITLE
vscode failed to download and config manually failed

### ISSUE THREAD

**Issue by liu0fanyi** [dotnet/vscode-dotnet-runtime#1313]
# Describe the bug

Failed to download .NET 6.0.21:
download from web and `dotnet --info`
```
...
.NET SDKs installed:
  6.0.121 [C:\Program Files\dotnet\sdk]
  7.0.110 [C:\Program Files\dotnet\sdk]
...
```
and then set
```
    "dotnetAcquisitionExtension.existingDotnetPath": [
        {"extensionId": "secretlab.yarn-spinner", "path": "C:\\Program Files\\dotnet\\dotnet.exe"},
    ],
```
not work,still download .net and failed

## **Please attach log file(s) here if you have any:**
>❗ Privacy Alert! The contents in our log files may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

If you came here from VS Code, the log file location should be copied to the clipboard.

## Other Info:
Errors the extension may have encountered have likely been added to your terminal or VS Code windows. Please paste it/them here and describe what happened and the problem you are facing.

**Reproduction Steps**

**Expected behavior**

**Exceptions & Errors (if any)**

**Further technical details**
- Your VSCode Version
1.81.1
- The version of the extension that's on your machine
v1.7.0
- Your operating system details
win10

**Comment by baronfel** [comment]
Are you sure that no other extensions you have installed use this extension? You'd need to make sure all of them have config entries for remapping the path to dotnet.

**Comment by liu0fanyi** [comment]
> Are you sure that no other extensions you have installed use this extension? You'd need to make sure all of them have config entries for remapping the path to dotnet.

found another one `csharp` and config
```
    "dotnetAcquisitionExtension.existingDotnetPath": [
        {"extensionId": "ms-dotnettools.csharp", "path": "C:\\Program Files\\dotnet\\dotnet.exe"},
        {"extensionId": "secretlab.yarn-spinner", "path": "C:\\Program Files\\dotnet\\dotnet.exe"}
    ],
```
still not work ,each time i open `.yarn` file from plugin `yarn-spinner`. 

start 

`Downloading the .NET Runtime.
Downloading .NET version(s) 6.0.21 .......................................................................................................................................................................................................................................`

**Comment by liu0fanyi** [comment]
And I have tried c# file `.cs`
It works, I can't understand...
```
Downloading the .NET Runtime.
Using configured .NET path: C:\Program Files\dotnet\dotnet.exe
```

**Comment by liu0fanyi** [comment]
https://github.com/YarnSpinnerTool/VSCodeExtension/issues/42#issue-1846054776

found Issue here, id in yarn-spinner plugin wrong

**Comment by baronfel** [comment]
Glad to hear it! We're going to add the extension id of the requesting extension to the logs in the future to make this easier.
