### ISSUE TITLE
error cmake

### ISSUE THREAD

**Issue by XavierMombimbo** [dotnet/vscode-dotnet-runtime#1328]
CMake Error at /usr/share/cmake-3.25/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_in

**Comment by nagilson** [comment]
Please raise this with https://github.com/microsoft/vscode-cmake-tools

**Comment by XavierMombimbo** [comment]
Thank you sir
