### ISSUE TITLE
MacOS installation fails due to hard dependency on wget

### ISSUE THREAD

**Issue by esuomi** [dotnet/vscode-dotnet-runtime#133]
I was actually trying to use the [ARM Tools](https://github.com/microsoft/vscode-azurearmtools) which relies on this one, but the console output pointed to this tool instead so I felt this is the more appropriate place for this.

Anyway, opening an ARM template file which activates the aforementioned extension triggers loading of .NET Core tooling, which due to this being the first time fails catastrophically as `wget` is not available on MacOS by default:

```sh
Downloading .NET Core tooling version(s) 3.1.9 ............ Error!
Failed to download .NET Core tooling 3.1.9:
/Users/myusername/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: line 594: wget: command not found
/myusername/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: line 594: wget: command not found


 Error!
Dotnet Core Acquisition Failed: undefined
```

**Comment by StephenWeatherford** [comment]
https://github.com/dotnet/vscode-dotnet-runtime/issues/137

**Comment by StephenWeatherford** [comment]
The error message ain't so helpful, either.
![image](https://user-images.githubusercontent.com/6913354/98197944-b1d38580-1edc-11eb-89d8-607efc74824f.png)

**Comment by MEETANDGREET** [comment]
How did you solve this problem?

**Comment by StephenWeatherford** [comment]
`brew install wget`worked for me

**Comment by Elringus** [comment]
I wonder how such glaring regression could've slipped? Don't you run any tests before pushing new releases to the marketplace?

This basically kills all the dotnet packages for mac users. Please consider fixing asap.

**Comment by sfoslund** [comment]
This is an issue with the install scripts that the extension relies on, which we acquire dynamically and ship out of band with this extension. The install scripts team is aware of this issue and hoping to get a fix out early next week (see https://github.com/dotnet/install-scripts/issues/95).

**Comment by sfoslund** [comment]
This issue has been fixed on the install scripts side. Please try again, noting that the scripts can be cached so it might take two attempts before you get the updated fix. Let us know if you're having recurring issues- thanks!

**Comment by Elringus** [comment]
Now it fails with:

```
[2020-11-11 20:39:38.858] [renderer1] [error] spawn dotnet ENOENT: Error: spawn dotnet ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

I've tried multiple times, re-installed vscode and .net runtime, but it's the same.

**Comment by sfoslund** [comment]
Would you be able to provide log files?

**Comment by Elringus** [comment]
Actually, it's probably not related with this issue. I've opened another one: https://github.com/dotnet/vscode-dotnet-runtime/issues/141

**Comment by sfoslund** [comment]
Agreed, I'll close this one again.
