### ISSUE TITLE
https://aka.ms/dotnet-os-lifecycle 

### ISSUE THREAD

**Issue by Denis71753** [dotnet/vscode-dotnet-runtime#1331]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\denis\AppData\Roaming\Code\logs\20230828T145212\window1\exthost\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1693223791275.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by nagilson** [comment]
Please provide more info so we can assist you.
