### ISSUE TITLE
Error acquiring .NET

### ISSUE THREAD

**Issue by phootrf** [dotnet/vscode-dotnet-runtime#1341]
# Describe the bug

Error acquiring .NET

Following log entry:
An error occurred while installing .NET (7.0): .NET Acquisition Failed: Installation failed: Error: Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; & 'c:\Users\phoot\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.7.2\dist\install scripts\dotnet-install.ps1' -InstallDir 'c:\Users\phoot\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10' -Version 7.0.10 -Runtime dotnet }

Der Befehl "powershell.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

-> Command "powershell.exe" ist either wrongly spelled or could not be found.

powershell has been installed, and it is part of the PATH variable

## **Please attach log file(s) here if you have any:**
>❗ Privacy Alert! The contents in our log files may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

If you came here from VS Code, the log file location should be copied to the clipboard.

## Other Info:
Errors the extension may have encountered have likely been added to your terminal or VS Code windows. Please paste it/them here and describe what happened and the problem you are facing.

**Reproduction Steps**
1. set up unity editor with latest visual studio editor package
2. set up preferences to use vscode as external scripting editor
3. install unity extension for vscode, have it install all dependencies

**Expected behavior**
no error, full intellisense and code completion

**Exceptions & Errors (if any)**
no intellisense working
no code completion working

**Further technical details**
- Your VSCode Version
1.81.1
- The version of the extension that's on your machine
v0.9.0
- Your operating system details
Windows 10 Pro

**Comment by phootrf** [comment]
I should add that I tried to add an existing .NET installation into the settings, which did not resolve my issues.

**Comment by nagilson** [comment]
@phootrf thank you for reporting the issue and filling it out 😄  This is very valuable information and I hope we can fix it for you.
I am surprised powershell.exe is not found. 

May you tell us the following?
Open a CMD / Command Prompt in Windows, and run the following. What's the output?
a. `PATH` (Make sure to remove any private data from the PATH, I just want to know what powershell is on the path.)
b. `powershell.exe` 
c. `pwsh`
d. `powershell`

Also, if possible, may you tell us if Powershell is checked here?
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/23152278/70cf25b8-0c1a-4e6f-a324-3560edc87b62)

To get there, search in the taskbar for 'Turn Windows Features on or off' then scroll down until you see Powershell 2.0 Checkbox.

Or follow these instruction:
(Press the Windows key and type Control Panel there and press Enter.
Click the drop-down menu in the top right corner of the screen to select Large icons.
Click on Programs and Features.
Click on the Turn Windows features on or off option from the left pane.
In the Windows Features screen, verify Windows PowerShell (it can be suffixed with 2.0 depending on the version) checkbox is checked or not.)

**Comment by andreaswyrmmeyr** [comment]
I am running into a similar issue and when looking at the PATH I have PowerShell but not powershell.exe.

**Comment by phootrf** [comment]
@nagilson I should add that the .NET Runtime Install Tool version is v1.7.2.

These are your requested screenshots:
PATH:
![path](https://github.com/dotnet/vscode-dotnet-runtime/assets/63897048/29d25360-51d2-488a-ade2-a4036dbb6ff5)

Windows Features:
![powershell2](https://github.com/dotnet/vscode-dotnet-runtime/assets/63897048/c7357cd2-1fcd-4485-9f45-bf38a5073ca8)

Error Message in VSC:
![dotnet](https://github.com/dotnet/vscode-dotnet-runtime/assets/63897048/ed4e3607-71e9-456a-891b-bd02c2c8799e)

.NET Runtime Output is as follows:
Downloading the .NET Runtime.
Downloading .NET version(s) 7.0.10 ..... Error!
Failed to download .NET 7.0.10:
powershell.exe is not discoverable on your system. Is PowerShell added to your PATH and correctly installed? Please visit: https://learn.microsoft.com/powershell/scripting/install/installing-powershell-on-windows.
You will need to restart VS Code after these changes. If PowerShell is still not discoverable, try setting a custom existingDotnetPath following our instructions here: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md.

 Error!
Failed to download .NET 7.0.10:
Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; & 'c:\Users\phoot\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.7.2\dist\install scripts\dotnet-install.ps1' -InstallDir 'c:\Users\phoot\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10' -Version 7.0.10 -Runtime dotnet }
Der Befehl "powershell.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.


 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; & 'c:\Users\phoot\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.7.2\dist\install scripts\dotnet-install.ps1' -InstallDir 'c:\Users\phoot\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10' -Version 7.0.10 -Runtime dotnet }
Der Befehl "powershell.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.


Hope this helps.

**Comment by andreaswyrmmeyr** [comment]
@nagilson 

('powershell.exe' is not recognized as an internal or external command,
operable program or batch file.)

('powershell' is not recognized as an internal or external command,
operable program or batch file.)

(pwsh
PowerShell 7.3.6)

these are the responses from entering the aforementioned commands into CMD.

**Comment by nagilson** [comment]
Thank you so much, that's what we maybe thought -- that powershell core (powershell 7, also called pwsh) is installed but that uninstalled or did not ship with powershell 5.1. which is accessed as powershell. We have a fix in the works we hope to ship soon that will hopefully remedy this issue 🥳

**Comment by phootrf** [comment]
@nagilson

I am really sorry for the delay -- was off base for some time. I've run the commands I forgot to execute last time, sorry gain. Here are the results:
![cmd](https://github.com/dotnet/vscode-dotnet-runtime/assets/63897048/a3a3cb27-83dc-47cd-b2e3-24d677c04fe2)

**Comment by nagilson** [comment]
That's ok :) Thank you for your help. I think this should be fixed in 1.7.3, let us know if you still face this issue.
