### ISSUE TITLE
Failed to download .NET 7.0 TIMEOUT

### ISSUE THREAD

**Issue by Alexey-B** [dotnet/vscode-dotnet-runtime#1342]
Error in VSCode startup. I have no problem with inet connection.
The problem started around 08/31/2023.
Windows 8.1, VScode 1.79.2

Error!
TIMEOUT: The request to https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json timed out at 1000 ms. This only occurs if your internet
 or the url are experiencing connection difficulties; not if the server is being slow to respond. Check your connection, the url, and or increase the timeout value here: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#install-script-timeouts

 Error!
Please ensure that you are online: Request to https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json Failed: canceled

 Error!
Failed to download .NET 7.0:
Please ensure that you are online: Request to https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json Failed: canceled

 Error!
Please ensure that you are online: Request to https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json Failed: canceled

Downloading the .NET Runtime.
Using configured .NET path: C:\Program Files\dotnet\dotnet.exe
Downloading the .NET Runtime.
Using configured .NET path: C:\Program Files\dotnet\dotnet.exe

**Comment by Alexey-B** [comment]
Nevermind fixed with settings.json:
"dotnetAcquisitionExtension.installTimeoutValue": 360

**Comment by ZengHugh** [comment]
Save following lines to settings.json reference(https://stackoverflow.com/questions/76703190/vscode-timeout-error-when-download-dotnet-runtime-v7-0-9)
"dotnetAcquisitionExtension.existingDotnetPath": [
        {
            "extensionId": "ms-dotnettools.csdevkit",
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"
        },
        {
            "extensionId": "ms-dotnettools.vscodeintellicode-csharp",
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"
        },
        {
            "extensionId": "ms-dotnettools.csharp",
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"
        },
        {
            "extensionId": "ms-dotnettools.vscode-dotnet-runtime",
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"
        }
    ]

**Comment by ZengHugh** [comment]
Manually update the .NET version you need, then vscod will automatic identification it.
