### ISSUE TITLE
VS Code not works on MacOS.

### ISSUE THREAD

**Issue by danilodumba** [dotnet/vscode-dotnet-runtime#1345]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /Users/danilodumba/Library/Application Support/Code/logs/20230903T135900/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1693760550933.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by baronfel** [comment]
@danilodumba please follow the instructions and upload a log file so that we can help you.

**Comment by nagilson** [comment]
Please fill out the form so we can help you and then we will reopen this.
