### ISSUE TITLE
Go-language

### ISSUE THREAD

**Issue by RAJVEERSIN** [dotnet/vscode-dotnet-runtime#1348]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\Rajbir singh\AppData\Roaming\Code\logs\20230904T152040\window1\exthost\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1693821121598.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by nagilson** [comment]
Will re open once the data is provided.
