### ISSUE TITLE
[NETSDKE2E] Installation of .NET runtime fails due to permission denied macOS and Linux

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/vscode-dotnet-runtime#1357]
**[Environment]**
Extensions build: vscode-dotnet-runtime-1.7.3
VSCode: 1.81.1
OS: Mac Sonoma(14.0) & Monterey M1(12.6.8) & Ubuntu (22.04)

**[Repro Steps]**
1. Install VSCode and extensions.
2. Run the `Sample: Concurrently acquire all 2.X .NET Core runtimes' command. 
3. Observe

**[Expected Result]**
It should succeed without any error messages or pop-ups.

**[Actual Result]**
The installation fails and pops up the error as below.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/87680983/6c752d55-fac5-4256-b9d6-7dfcc6593051)

```
An error occurred while installing .NET (2.1): .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/e2euser/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.7.3/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/e2euser/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/2.1.30" -Version 2.1.30 -Verbose -Runtime dotnet
/bin/sh: /Users/e2euser/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.7.3/dist/install scripts/dotnet-install.sh: Permission denied

```

**Comment by WenJunJi01** [comment]
Here is the additional information on macOS and Linux.
[Ubuntu 22.04.zip](https://github.com/dotnet/vscode-dotnet-runtime/files/12545866/Ubuntu.22.04.zip)
[macOS Sonoma 14.0.zip](https://github.com/dotnet/vscode-dotnet-runtime/files/12545868/macOS.Sonoma.14.0.zip)

**Comment by NicoleWang001** [comment]
Not repro on the new build 1.7.3

**Comment by WenJunJi01** [comment]
It hasn't reproduced for a long time, so I closed it.
