### ISSUE TITLE
Privacy Alert!

### ISSUE THREAD

**Issue by JohnyKid123** [dotnet/vscode-dotnet-runtime#1358]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\ASUS RoG\AppData\Roaming\Code\logs\20230906T123622\window1\exthost\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1693992989561.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by nagilson** [comment]
Please fill out the form so we can help you and then we will re open this.
