### ISSUE TITLE
.NET Runtime Installation Tool - v1.7.2 - Error 400 while Downloading the .NET Runtime

### ISSUE THREAD

**Issue by jtrivett** [dotnet/vscode-dotnet-runtime#1359]
# Describe the bug
.NET Runtime Installation Tool extension v1.7.2 for VS Code fails to download .NET Runtime. Extension reports an HTTP error 400 when attempting to retrieve data from URL https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json. The URL is accessible via curl (Git Bash) and browser on the same machine. Machine is behind a corporate proxy which uses certificate-based authentication, and the machine has the HTTP_PROXY and HTTPS_PROXY environment variables set.

This error prevents bicep template validation and  intellisense/autocomplete from functioning in VS Code. Reverting to extension v1.7.1 resolves the issue.

## **Please attach log file(s) here if you have any:**
Downloading the .NET Runtime.
 Error!
Please ensure that you are online: Request to https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json Failed: Request failed with status code 400

 Error!
Failed to download .NET 7.0:
Please ensure that you are online: Request to https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json Failed: Request failed with status code 400

 Error!
Please ensure that you are online: Request to https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json Failed: Request failed with status code 400

## Other Info:
Errors the extension may have encountered have likely been added to your terminal or VS Code windows. Please paste it/them here and describe what happened and the problem you are facing.

**Reproduction Steps**
Install .NET Runtime Installation Tool extension v1.7.2
Reload VS Code
Errors are displayed in pop-up windows and console output

**Expected behavior**
.NET Runtime Installation Tool extension v1.7.2 is able to successfully install the .NET Runtime

**Exceptions & Errors (if any)**

**Further technical details**
- Your VSCode Version
1.81.1

- The version of the extension that's on your machine
1.7.2

- Your operating system details
Windows 11 Enterprise 21H2

**Comment by nagilson** [comment]
Thank you for your detailed report.

For 1.7.2 we rehauled all of the web request code and migrated from `request` (now deprecated) to `axios`. We are seeing much better success rates per the average customer, but proxies appear to be an issue for axios cache https://github.com/axios/axios/issues/5256, they closed the initial issue https://github.com/axios/axios/issues/925 but never fixed it. 

We are going to try using a different proxy agent and think it will resolve your issue.

@jtrivett If we send you a new .VSIX would you be able to confirm if the fix works for you? Thanks!

**Comment by jtrivett** [comment]
@nagilson Thanks for the quick response. I'd be happy to test the fix when ready.

**Comment by nagilson** [comment]
Thank you for your patience and willingness to help :smile: -- most of that time was not really coding and more so trying to find a proxy that would reproduce the issue, and seeing if I am even allowed to just drop a file here for you to try. We are going to hopefully release the change soon regardless as version 1.7.3, so you may feel free to wait until then and we can see if it fixes the issue for you.

Here is a preview-build of the [test vsix](https://drive.google.com/file/d/1aLcXQbGbaQ44zN3-jkbbKtdBhk8LRlrt/view?usp=sharing) file if you are still interested. Please note that this is not a stable build and is a development/preview build so it should not be used in production and there are no guarantees.

**Comment by nagilson** [comment]
We just released 1.7.3, please let us know if it solves your issue?

**Comment by jtrivett** [comment]
Yes, all looks well in 1.7.3! No errors, and all of the bicep extension functionality seems to be working as expected. Thank you for the prompt support and fix, much appreciated!

**Comment by nagilson** [comment]
Fantastic, thank you for the update! And you are very welcome :)
