### ISSUE TITLE
I am trying to make a virtual agent for a construction company that the app user can answer prompts from the agent and  the agent will generate a proposal 

### ISSUE THREAD

**Issue by Enki420** [dotnet/vscode-dotnet-runtime#1362]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

### Describe the solution you'd like
A clear and **concise** description of what you want to happen. Include any alternative solutions you've considered.

**Comment by nagilson** [comment]
Please fill out the issue template and we can help you then.
