### ISSUE TITLE
Error! .NET Acquisition Failed: Installation failed: Error: Command failed: powershell.exe

### ISSUE THREAD

**Issue by LarryStewart2022** [dotnet/vscode-dotnet-runtime#1365]
# Describe the bug
I tried to add a configuration to debug streamlit. as soon as i click (add configuration, this error pops up

 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; & 'c:\Users\lstewart\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.7.2\dist\install scripts\dotnet-install.ps1' -InstallDir 'c:\Users\lstewart\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10' -Version 7.0.10 -Runtime dotnet }
'powershell.exe' is not recognized as an internal or external command,
operable program or batch file.

**Further technical details**
- Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by nagilson** [comment]
should be resolved in 1.7.3, let us know if this still occurs :)
