### ISSUE TITLE
dotnet

### ISSUE THREAD

**Issue by EliteTuner** [dotnet/vscode-dotnet-runtime#1366]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\TerryReedy\AppData\Roaming\Code\logs\20230909T212433\window1\exthost\ms-dotnettools.vscode-dotnet-sdk\DotNetAcquisition-ms-dotnettools.vscode-dotnet-sdk-1694309690811.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by nagilson** [comment]
Please fill out the issue template and we can help you then.
