### ISSUE TITLE
.NET Acquisition Failed: undefined (0.2.2)

### ISSUE THREAD

**Issue by StephenWeatherford** [dotnet/vscode-dotnet-runtime#137]
[DotNetAcquisition1604528413523.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/5490784/DotNetAcquisition1604528413523.txt)

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Repro steps:**

1.

**Extension Version:** 0.2.2
**Error Message:** .NET Acquisition Failed: undefined
**Error Stack:** Error: .NET Acquisition Failed: undefined
	at /Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-0.2.2/dist/extension.js:211:111566
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by sfoslund** [comment]
Post discussion notes:
- The wget failure is an issue with the install scripts, which is being tracked here: https://github.com/dotnet/install-scripts/issues/95
- Within the extension we should ensure that if the install scripts write to stderr we see those results in the error message
