### ISSUE TITLE
v1.7.2 new axios library fails to honour/use local CAs that work in reqwest from v1.7.1

### ISSUE THREAD

**Issue by philipcraig** [dotnet/vscode-dotnet-runtime#1376]
# Describe the bug

For version v1.7.1 or earlier, I am able to successfully use extension Ionide for F#, which uses C#, which uses this extension.

I am behind a corporate firewall, with dotnet 6.0 installed in a docker container and the container opened. Our corporate setup uses a MITM proxy server, with its own CA and private SSL cert. v1.7.1 worked fine with all of this.

All is well if I force version v1.7.1 of this extension.

With v.1.7.2, I instead get errors when it tries to fetch from the Internet.

I suspect the issue is that axios library is not being set up to use a local CA if it is present.

See here: https://stackoverflow.com/a/53585725 for how to set it up correctly. An Agent has to be created using the local private CA. The former library before axios (reqwest) did this automatically.

The operating system is Windows/WSL with a docker container containing Redhat, with .net 6.0 installed.

**Comment by philipcraig** [comment]
Yes, I can confirm that i'm seeing the same issue as in #1359 

So this is a duplicate and I'll close it and monitor #1359 

I unfortunately can't try the 1.73 preview .vsix from that issue, as I'm not able or allowed to load from google drive into work.

**Comment by nagilson** [comment]
Thanks for helping. I (hope) it is the same issue. If 1.7.3 doesn't fix it we can re open it and I'll probably take a go and doing what that SO post says (or something relatively similar.)

**Comment by philipcraig** [comment]
> Thanks for helping. I (hope) it is the same issue. If 1.7.3 doesn't fix it we can re open it and I'll probably take a go and doing what that SO post says (or something relatively similar.)

I confirm that v1.7.3 fixed this issue. Thanks!

**Comment by nagilson** [comment]
Fantastic news :)
