### ISSUE TITLE
Zhopensii

### ISSUE THREAD

**Issue by Deasite** [dotnet/vscode-dotnet-runtime#1377]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\Admin\AppData\Roaming\Code\logs\20230913T235150\window2\exthost\ms-dotnettools.vscode-dotnet-sdk\DotNetAcquisition-ms-dotnettools.vscode-dotnet-sdk-1694639492366.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by nagilson** [comment]
Please fill out the template and we can re open it, we need this information to help you.
