### ISSUE TITLE
scriptAcquisitionUrl should use an aka.ms redirect link instead of pointing directly to the install script download location

### ISSUE THREAD

**Issue by StephenWeatherford** [dotnet/vscode-dotnet-runtime#138]
This way it could be easily rolled back to a previous version if necessary.

It would also be nice to have a redirect link available for the troubleshooting page as well (currently ARM extension has a direct link, but the location could change in the future).

**Comment by sfoslund** [comment]
@bozturkMSFT you already have tiered releases, right? And I seem to remember hearing that your team was going to make less investment in the scripts in the future, so we're unlikely to see any instability, is that correct?

**Comment by StephenWeatherford** [comment]
Either way it's extremely easy to add a new aka.ms link, this is standard engineering practice.

**Comment by bozturkMSFT** [comment]
@sfoslund Sorry, I have just seen this. No, we don't have tiered releases. We are putting the scripts in maintenance mode at the end of this year, but until then we have a bulk of changes coming. So aka.ms links sound like a good thing to have in the coming months.
