### ISSUE TITLE
.NET Install Tool invalid value in settings.json 

### ISSUE THREAD

**Issue by utami1511** [dotnet/vscode-dotnet-runtime#139]
I am trying to use an existing installation of .NET by changing the value of the dotnetAcquisitionExtension.existingDotnetPath in settings.json by following the instruction in the link below:

https://github.com/dotnet/vscode-dotnet-runtime/blob/master/Documentation/troubleshooting.md#install-script-timeouts

But it's still coming up with error: 'Incorrect type'. Can anyone please help?

![net install tool error](https://user-images.githubusercontent.com/41478225/98509036-a43f4680-22b4-11eb-973a-7258c9bf0623.JPG)

**Comment by sfoslund** [comment]
This appears to be an issue with the vscode json checking, it should not have an effect on the extension. That being said, it looks like you've added extra "\"'s in your path. Once you remove those, this configuration should work as expected.

**Comment by utami1511** [comment]
@sfoslund  Can you please point out where do I have extra ""'s in my path?

**Comment by sfoslund** [comment]
Sorry, Github interpreted it as an escape character. I meant you have exra `\`'s in your path. (it should be `C:\Program Files...` instead of `C:\\Program Files...`).

**Comment by sfoslund** [comment]
@utami1511 have you been able to manually configure your path successfully?

**Comment by cloudfright** [comment]
I'm having a similar issue. I modified settings,json like this 

`{
    "dotnetAcquisitionExtension.existingDotnetPath": [
        {"extensionId": "msazurermtools.azurerm-vscode-tools", "path": "C:\Program Files\dotnet\dotnet.exe"}
    ]
}`

.. and then see this:

![image](https://user-images.githubusercontent.com/74401729/99048672-c4f5ed80-258d-11eb-9357-53133b0db36c.png)

**Comment by julien-chenylina** [comment]
I have the same problem。
![image](https://user-images.githubusercontent.com/15798451/99071757-b2ab9c00-25ed-11eb-8cf6-e7ca6ca6ecf6.png)

**Comment by cloudfright** [comment]
In the extension package.json the version and path defined rather than the extensionId - is this related?

`"dotnetAcquisitionExtension.existingDotnetPath": {
					"type": {
						"version": "string",
						"path": "string"
					},
					"description": "File Path to an existing installation of .NET."
				}`

**Comment by sfoslund** [comment]
@cloudfright you're right, the package.json type is a mistake and it likely causing the settings.json warning. However, this should not effect the actual usage of the feature. @julien-chenylina @utami1511 is you ignore the warnings are you able to run with the configured path or do you get the `Ignoring existing .NET paths` message too?
@cloudfright I'm assuming you're using this extension with the azure resource manager extension, is that correct? What version do you have installed?

**Comment by StephenWeatherford** [comment]
> `Sorry, Github interpreted it as an escape character. I meant you have exra \'s in your path. (it should be C:\Program Files... instead of C:\\Program Files...).`

The `\'s` must be escaped

**Comment by cloudfright** [comment]
@sfoslund I'm using it with the BICEP v0.23 extension and see the error when trying to open a .bicep file.

**Comment by sfoslund** [comment]
> I'm using it with the BICEP v0.23 extension and see the error when trying to open a .bicep file.

@cloudfright this is an issue with the bicep extension then. They need to pass us their extension Id in order to get access to this feature (See this issue I filed against another extension that had to do the same thing: https://github.com/dotnet/interactive/issues/875)

**Comment by sfoslund** [comment]
I've filed an issue against the bicep extension: https://github.com/Azure/bicep/issues/906

**Comment by julien-chenylina** [comment]
Yes,  I get the Ignoring existing .NET paths message
![image](https://user-images.githubusercontent.com/15798451/99139584-ff868580-2674-11eb-9b0d-256d447d8fea.png)

**Comment by sfoslund** [comment]
It looks like you are using the naninovel extension, which also seems to have not updated. I've filed an issue on their repo: https://github.com/Naninovel/VSCode/issues/2

**Comment by cloudfright** [comment]
Hi. Just an update from me. v0.2.0 has fixed the error message when trying to set a manual path (thank you!), but I'm finding that even though I have a manual path set, it's still attempting to download / install and is failing related to #131 (log attached)

My manual config is:

`{ 
    "dotnetAcquisitionExtension.existingDotnetPath": [
        {"extensionId": "msazurermtools.azurerm-vscode-tools", "path": "C:\Program Files\dotnet\dotnet.exe"}
    ]
}`

[DotNetAcquisition1606221273335.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/5590007/DotNetAcquisition1606221273335.txt)

**Comment by sfoslund** [comment]
It looks like you are using the ARM extension ID in your config, if you are using the bicep extension you will want to specify that instead by replacing the extensionId field with ms-azuretools.vscode-bicep

**Comment by cloudfright** [comment]
Thank you @sfoslund :)
