### ISSUE TITLE
1.7.3 add HOME env var to vscode process which should not

### ISSUE THREAD

**Issue by pbl-pw** [dotnet/vscode-dotnet-runtime#1400]

**Comment by nagilson** [comment]
May you please provide a bit more detail, why do you think the extension does this, and why does this cause a problem?

**Comment by pbl-pw** [comment]
@nagilson 
when disable or downgrade this extension to 1.7.2, then no **HOME** env var added.
![dnbug](https://github.com/dotnet/vscode-dotnet-runtime/assets/3636470/ca1f78cd-78f1-4118-b6a4-b0e9e2a0b713)
git command will detect different **HOME** inside and outside vscode, then it can't find my git global config file in **HOME** path

**Comment by nagilson** [comment]
It's possible one of our added dependencies fiddles with the home variable.

The culprit in that case would be 1 of:
get-proxy-settings
https-proxy-agent
proper-lockfile

**Comment by nagilson** [comment]
it IS get-proxy-settings that sets HOME 🤨 when we import it, it sets HOME, so thats cool
