### ISSUE TITLE
Cannot install .NET

### ISSUE THREAD

**Issue by almimoon158** [dotnet/vscode-dotnet-runtime#1403]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\ALAYAREAMI\AppData\Roaming\Code\logs\20230905T112235\window3\exthost\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1695400557971.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by nagilson** [comment]
Please update your extension by reinstalling, uninstalling, then recreate a more detailed report.
