### ISSUE TITLE
Fails to run dotnet on MacOS after download

### ISSUE THREAD

**Issue by Elringus** [dotnet/vscode-dotnet-runtime#141]
When dotnet runtime is downloaded with vscode-dotnet-runtime extension the runtime fails to run on MacOS. 
When dotnet runtime is installed manually it works fine.

Steps to reproduce (on MacOS):
1. Make sure no dotnet runtimes installed on the machine
2. Install [Naninovel](https://marketplace.visualstudio.com/items?itemName=Elringus.naninovel) extension in VSCode (it's a language server built with .NET Core 3.1)
3. Activate the extension by opening a file with `.nani` extension

Expected: vscode-dotnet-runtime downloads dotnet runtime and language server is started with the downloaded runtime.
Actual: vscode-dotnet-runtime downloads dotnet runtime, but the language server fails to run with the following log:

```
2020-11-11T18:01:40.445Z info: Current log level: debug.
2020-11-11T18:01:40.445Z info: Launching Naninovel language service...
2020-11-11T18:01:40.453Z debug: Found dotnet command at '/Users/admin/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.10/dotnet'.
2020-11-11T18:01:40.453Z debug: Found language server at '/Users/admin/.vscode/extensions/elringus.naninovel-1.1.1/server/NaninovelLanguageServer.dll'.
2020-11-11T18:01:40.459Z info: Naninovel language service started.
[Error - 9:01:40 PM] Starting client failed
Launching server using command dotnet failed.
Error: Launching server using command dotnet failed.
```

If you now install .NET Core 3.1 manually (via https://dotnet.microsoft.com/download) the extension will activate and work fine.

**Comment by sfoslund** [comment]
Can you provide the extension log files? The path to the log file location will be available from the extension's "Report issue" command.

**Comment by Elringus** [comment]
Here is the extension log:
```
11/11/2020, 9:01:40 PM DotnetVersionResolutionCompleted
3.1
3.1.10

11/11/2020, 9:01:40 PM DotnetInstallationValidated
3.1.10

11/11/2020, 9:01:40 PM DotnetAcquisitionAlreadyInstalled
3.1.10

11/11/2020, 9:01:40 PM DotnetCommandSucceeded
acquire
```

**Comment by sfoslund** [comment]
Does /Users/admin/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.10/dotnet exist? And does it match the install location that shows up in the extension log (I'm assuming there's a path there that you removed for privacy)

**Comment by Elringus** [comment]
It does exist and the language server works fine under the same paths when run manually via terminal:
```
"/Users/admin/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.10/dotnet" "/Users/admin/.vscode/extensions/elringus.naninovel-1.1.1/server/NaninovelLanguageServer.dll"
```

It's just VSCode fails to run the dll with the dotnet runtime path [provided by the vscode-dotnet-runtime extension's `aquire` command](https://github.com/Naninovel/VSCode/blob/master/src/language/client.ts#L92). And it only happens when the dotnet runtime is downloaded by vscode-dotnet-runtime extension. When the runtime is installed manually (globally), everything works fine.

**Comment by sfoslund** [comment]
It sounds like this is an issue with the way you are using the path that the extension returns then. Please check out the sample extension in this repo for an example: https://github.com/dotnet/vscode-dotnet-runtime/blob/master/sample/src/extension.ts

**Comment by Elringus** [comment]
It seems the issue was actually caused by [vscode-languageclient](https://github.com/microsoft/vscode-languageserver-node); particularly `cwd` option of the lsp executable doesn't seem to work properly on mac. I've based the extension client code on the [official Azure bicep package](https://github.com/Azure/bicep/blob/main/src/vscode-bicep/src/language/client.ts#L47), so the same issue affects it as well, probably. Specifying full path to the dotnet executable instead of using cwd seem to fix the issue.

Anyway, all this is not related with vscode-dotnet-runtime, so I'm closing the issue. Sorry for taking your time and thanks for the prompt responses!
