### ISSUE TITLE
Error with .NET acquisition on C# Extension update

### ISSUE THREAD

**Issue by SusanTWhite** [dotnet/vscode-dotnet-runtime#1413]
# Describe the bug
Unable to connect to server

## **Please attach log file(s) here if you have any:**
>❗ Privacy Alert! The contents in our log files may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

[DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1695731444737.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/12727578/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1695731444737.txt)

If you came here from VS Code, the log file location should be copied to the clipboard. 

c:\Users\xxxxxxx\AppData\Roaming\Code\logs\20230926T083039\window1\exthost\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1695731444737.txt. Note that this file may contain personal data.

## Other Info:
Errors the extension may have encountered have likely been added to your terminal or VS Code windows. Please paste it/them here and describe what happened and the problem you are facing.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: EPERM: operation not permitted, unlink 'c:\Users\anonymous\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.11\dotnet.exe'
**Error Stack:** Error: .NET Acquisition Failed: EPERM: operation not permitted, unlink 'c:\Users\anonymous\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.11\dotnet.exe'
    at c:\Users\anonymous\.vscode\extensions\vscode-dotnet-runtime-library\dist\Acquisition\DotnetCoreAcquisitionWorker.js:95:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Reproduction Steps**
Recently updated C# extension to latest in Visual Code

**Expected behavior**
No errors

**Exceptions & Errors (if any)**

Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
No compatible .NET runtime found. Minimum required version is 7.0.
[Error - 8:30:56 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Could not resolve the dotnet path!
    at t.DotnetRuntimeExtensionResolver.<anonymous> (c:\Users\xxxxxx\.vscode\extensions\ms-dotnettools.csharp-2.3.27-win32-x64\dist\extension.js:2:1421031)
    at Generator.next (<anonymous>)
    at s (c:\Users\xxxxxx\.vscode\extensions\ms-dotnettools.csharp-2.3.27-win32-x64\dist\extension.js:2:1419403)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

[](url)
**Further technical details**
- Your VSCode Version
-  The version of the extension that's on your machine
- Your operating system details

Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by SusanTWhite** [comment]
NOTE: I was able to get this working by disabling the Dev Kit and disabling and re-enabling the C# extension. Seems like there is a potential compatibility issue.

**Comment by nagilson** [comment]
Your issue was very helpful, so thank you for taking the time to add the log :) 

Basically, for 1.8.0 we have to do a reinstall of the .NET Runtime, and we failed to delete the old one because it was being used by CDK. However, we only do the uninstall process if the install was successful, and the API still returns the dotnet it installed successfully. The uninstall failed because the old .NET runtime was in use, presumably by CDK or someone else like that.

The failure you're seeing in CDK/C# is likely related. @dibarbet @AArnott If CDK falls back to the .NET Runtime, will it request to install the runtime, and always use the runtime path that .NET installs? Does it do any 'saving' of a runtime the extension already installed and try to use that? If so, this might be an issue. I'd suspect it to be more widespread if so, though

**Comment by AArnott** [comment]
CDK will ask the .NET Runtime install tool, at startup, if and only if it cannot find an appropriate match on the PATH. It will check and call on every startup.
It's _possible_ that we 'leak' the path to .NET runtime assemblies in the MEF cache that we create. If we do, I could see that being problematic when the paths change from one session to the next.
