### ISSUE TITLE
Getting a error 

### ISSUE THREAD

**Issue by poojith7** [dotnet/vscode-dotnet-runtime#1439]
# Describe the bug

## **Please attach log file(s) here if you have any:**
>❗ Privacy Alert! The contents in our log files may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement
Traceback (most recent call last):

If you came here from VS Code, the log file location should be copied to the clipboard.
  line 1, in <module>
    import cv2
  , line 181, in <module>
    bootstrap()
 local/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  .local/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
 .local/lib/python3.10/site-packages/cv2/typing/__init__.py", line 157, in <module>
    Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'
## Other Info:
Errors the extension may have encountered have likely been added to your terminal or VS Code windows. Please paste it/them here and describe what happened and the problem you are facing.

**Reproduction Steps**

**Expected behavior**

**Exceptions & Errors (if any)**

Traceback (most recent call last):

**Further technical details**
- Your VSCode Version

- The version of the extension that's on your machine

- Your operating system details
- ubuntu i installed all the dependencies
[virtualAIGym-main (1).zip](https://github.com/dotnet/vscode-dotnet-runtime/files/12791609/virtualAIGym-main.1.zip)

**Comment by nagilson** [comment]
This seems like a failure for your python project or the python extension, not the runtime extension. Please follow up there.
