### ISSUE TITLE
<!-- IMPORTANT: Please be sure to remove any private information before submitting. -->  **Repro steps:**  1.  **Extension Version:** 0.1.2

### ISSUE THREAD

**Issue by sollo-users** [dotnet/vscode-dotnet-runtime#144]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\API\AppData\Roaming\Code - Insiders\logs\20201114T045344\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition1605326240780.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by sfoslund** [comment]
Hi @sollo-users, it looks like this is the second issue you're reported but we aren't able to take action unless more detail about the error is provided. I'm going to close this issue for now, but please provide more information and reopen- thanks!
