### ISSUE TITLE
Thoughts on the structure of distro-support.json

### ISSUE THREAD

**Issue by mateusrodrigues** [dotnet/vscode-dotnet-runtime#1480]
Hi folks! From our perspective as .NET Ubuntu distro maintainers, @dviererbe and I have been thinking of ways to structure the `distro-support.json` document with the following goals in mind:

- **Avoid the need to maintain a .NET version support matrix per distro**: improving scalability and maintenance overhead in the near and long-term.
- **Delegate as much as possible to the distro package manager**: that is, delegate the figuring out of which .NET packages are available in "current" version to the package manager.

This is ultimately what we came up with:

```
{
	...
	"Ubuntu": {
		"installCommand": "sudo apt-get update && sudo apt-get install -y {0}",
		"uninstallCommand": "sudo apt-get remove {0}",
		"updateCommand": "sudo apt-get update && apt-get upgrade -y {0}",
		"searchCommand": "apt-cache search {0}",
		"isInstalledCommand": "sudo apt list --installed {0}",
		"packageLookupCommand": "dpkg -l {0}",
		"expectedDistroFeedInstallDirectory" : "/usr/lib/dotnet/sdk",
		"expectedMicrosoftFeedInstallDirectory" : "/usr/bin/dotnet",
		"installedSDKVersionsCommand": "dotnet --list-sdks",
		"installedRuntimeVersionsCommand": "dotnet --list-runtimes",
		"currentInstallationVersionCommand": "dotnet --version",
		"currentInstallPathCommand" : "which dotnet",
		"packages": [
			{
				"version": "6.0",
				"sdk": [
					"dotnet-sdk-6.0"
				],
				"runtime": [
					"dotnet-runtime-6.0"
				],
				"aspnetcore": [
					"aspnetcore-runtime-6.0"
				]
			},
			{
				"version": "7.0",
				"sdk": [
					"dotnet-sdk-7.0"
				],
				"runtime": [
					"dotnet-runtime-7.0"
				],
				"aspnetcore": [
					"aspnetcore-runtime-7.0"
				]
			},
			{
				"version": "8.0",
				"sdk": [
					"dotnet-sdk-8.0"
				],
				"runtime": [
					"dotnet-runtime-8.0"
				],
				"aspnetcore": [
					"aspnetcore-runtime-8.0"
				]
			}],
		"strategy": [
			{
				"version": "18.04",
				"preInstallCommands": [
					"apt-get update && apt install -y wget",
					"wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb",
					"sudo dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb"
				]
			},
			{
				"version": "20.04",
				"preInstallCommands": [
					"apt-get update && apt install -y wget",
					"wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb",
					"sudo dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb"
				]
			},
			{
				"version": "24.04",
				"packages": [{
					"version": "8.0",
					"sdk": "dotnet-sdk-8.0-DIFFERENT-NAME"
				}]
			}
		]
	},
        ...
}
```

1. Added a `searchCommand` for package discovery purposes.

2. Added the `packages` array parameter.
  - This serves as a way to globally store every binary package name for that distro per .NET version. e.g. the 6.0 SDK package, in Ubuntu, is called `dotnet-sdk-6.0`. However, if the name ever changes in a future release archive, the `sdk` parameter, as well as `runtime` and `aspnetcore`, are array types, which can include all past and present package names for searching purposes.
  - The goal of this parameter is to let the extension know exactly which packages to search for during discovery. Whether that package is available/supported or not on that Ubuntu release is up to the package manager to figure out and let the extension act accordingly. Thus, the need for `searchCommand`.
  
3. Added the `strategy` array parameter.
  - This array stores distro version-specific strategy overrides.
  - As an example, versions 18.04 and 20.04 include `preInstallCommands` that, theoretically, should be run before package discovery.
  - Also, version 24.04 includes a `packages` parameter that overrides the global package naming in `Ubuntu:packages` for the 8.0 SDK, supposing it has a different name exclusively for that release (unlikely, but well...).
    - That package name could also be added to `Ubuntu:packages` as an SDK naming possibility for 8.0. The only behavioral difference would be that that name would also be searched for on Ubuntu versions other than 24.04. So, if one wants to spare the CPU cycles and HTTP calls for that, this is the way.

This is a rough draft of what the algorithm would look like:

```
$ubuntu_version = 'current Ubuntu version'
$dotnet_version = '.NET version to be installed'
```

- 1. Any strategies for `$ubuntu_version`?
  - 1.1. If `preInstallCommands`, run them
  - 1.2. If `packages` naming override, store them
- 2. Run `searchCommand` against package names for `$dotnet_version`
  - 2.1. If package manager found package, supported
    - 2.1.1. Install packages with `installCommand`
  - 2.2. If package manager did **not** find package, unsupported.
    - 2.2.1. Let extension handle error UX

cc @JL03-Yue @nagilson @omajid

**Comment by nagilson** [comment]
@mateusrodrigues @dviererbe @omajid

Thank you all for your thoughtful feedback and listening to our proposals, both now and within our meeting.

I think this proposal is well-thought out and appreciate the time you clearly put into it. It will certainly reduce the maintenance burden. I will go ahead and make this change to adopt the `packages` and `searchCommand`. For RHEL, I think we can use `yum --cacheonly list {0}`. I like this idea a lot!

I think the `strategy` implementation is the best one, however, I like how our current structure separates it into `versions` and then a `version`. I think for now, we will choose to continue with the slower but simpler approach, with the option to change it in the future. Of course, the `version` will no longer contain the supported dotnet versions but instead just any `preinstallCommands` or extras someone could add on later.

I think we'd also want the ability to add the ability for another distro to 'inherit' another's commands. I will have to update our documentation and specs for that!

**Comment by nagilson** [comment]
We have incorporated this feedback now, so I will close it. Thank you for your valuable help :)
