### ISSUE TITLE
.NET 7.0.13 fails on Mac OS with `/libhostfxr.dylib' not valid for use in process: mapped file has no Team ID`

### ISSUE THREAD

**Issue by chemicalcrux** [dotnet/vscode-dotnet-runtime#1486]
# Describe the bug

.NET 7.0.13 is failing to activate. The output window indicates there is a code signing problem.

## Log files:

[DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1698249623371.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/13168099/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1698249623371.txt)

The following appears in the output window:

[output.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/13168161/output.txt)

The notable bit:

> '/Users/crux/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~arm64/host/fxr/7.0.13/libhostfxr.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?))

I checked the code signing on the .dylib. It seems okay. I don't know much about this, though, so I could be missing the problem.

```
crux@fens-mbp-2 7.0.13 % codesign --verify --verbose libhostfxr.dylib
libhostfxr.dylib: valid on disk
libhostfxr.dylib: satisfies its Designated Requirement
```

## Other Info:
**Reproduction Steps**
Launching VSCode is sufficient to cause this problem. I tried deleting the `7.0.13~arm64` folder and redownloading, but that didn't change.

**Expected behavior**
The .dylib loads!

**Exceptions & Errors (if any)**
See above

**Further technical details**
- Your VSCode Version
1.83.1

- The version of the extension that's on your machine
1.8.1

- Your operating system details
M1 MacBook
macOS Ventura 13.3.1 (a)

I tried to use the `dotnetAcquisitionExtension.existingDotnetPath` setting to choose an older version of .NET, but the extension seems to be ignoring it. Here is what I tried using:

```
        "dotnetAcquisitionExtension.existingDotnetPath": [
          {
            "extensionId": "ms-dotnettools.csharp",
            "path": "/usr/share/dotnet/dotnet"
          },
          {
            "extensionId": "ms-dotnettools.csdevkit",
            "path": "/usr/share/dotnet/dotnet"
          }
        ]
```

So, I cannot test if this is also happening with older versions. I'm pretty sure they were working fine, though, since the issue just cropped up today.

**Comment by chemicalcrux** [comment]
Okay, I can confirm that 7.0.12 is working fine over here -- I just copied the 7.0.12~arm64 folder and named it 7.0.13~arm64, and the extension happily loaded it (:

**Comment by larryPlayabl** [comment]
I am experiencing this as well. Just started today. Not sure what changed. I tried copying over a 7.0.12 directory but it hasn't worked... yet.

**Comment by jecc1982** [comment]
The same thing happened to me too. I only have 6.0.x SDK and Runtime installed in the CLI (i.e /usr/local/share/dotnet).

The C# extension uses the 7.0 version installed (under ~/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/) by the .NET Runtime Install Tool. I tried to manually deleted 7.0.13~arm64. The extension then automatically downloaded 7.0.13 and still had the same error. I then replaced 7.0.13~arm64 with the previously installed 7.0.12~arm64 folder suggested by https://github.com/dotnet/vscode-dotnet-runtime/issues/1486#issuecomment-1779648132 and that worked for me.

**Comment by mark-night** [comment]
I am experiencing this as well.
Following instructions [here](https://devblogs.microsoft.com/dotnet/csharp-dev-kit-now-generally-available/#comment-19211) didn't help.
But @chemicalcrux 's renaming trick solved it (temporarily)

**Comment by nagilson** [comment]
Thank you for reporting this issue, there was a mistake with the 7.0.13 runtime release where the files were signed as if they are the Windows runtime, so they are considered 'ad-hoc' signed as they are improperly signed. Our release team is working to reship the runtime files with a correct signature.

Users on both Mac x64 and Mac ARM64 are impacted. 

@chemicalcrux's solution is the best work-around for now.

**Comment by nagilson** [comment]
A new .NET Runtime has shipped and an official work around is posted here with more information: 
https://github.com/dotnet/core/issues/8861

Please reach out if you experience any more difficulties. Unfortunately, there is a manual step needed to fix this issue.
I will leave this issue pinned for a bit until the number of hits on it dies down, then I will close it. 

Thank you for your reports everyone, and @chemicalcrux for a work-around ( and a cool avatar.)

**Comment by jecc1982** [comment]
Confirm that getting the extension to redownload 7.0.13 works in Mac now.

**Comment by nagilson** [comment]
Thanks for confirming :)

**Comment by nagilson** [comment]
Hi folks, since this issue is resolved and we arent getting any more reports Im going to close and un pin it.
