### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by andres7925** [dotnet/vscode-dotnet-runtime#1503]
# Describe the bug

The .NET Core SDK cannot be located: Error running dotnet --info: Error: spawn C:\WINDOWS\system32\cmd.exe;C:\MinGW\bin;C:\Users\USUARIO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pygame; ENOENT

. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.

## **Please attach log file(s) here if you have any:**
>❗ Privacy Alert! The contents in our log files may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

If you came here from VS Code, the log file location should be copied to the clipboard.

## Other Info:
Errors the extension may have encountered have likely been added to your terminal or VS Code windows. Please paste it/them here and describe what happened and the problem you are facing.

**Reproduction Steps**

**Expected behavior**

**Exceptions & Errors (if any)**

**Further technical details**
- Your VSCode Version

- The version of the extension that's on your machine

- Your operating system details

**Comment by nagilson** [comment]
I believe the .NET SDK on your PATH is incorrect, it seems to expect the dotnet exe to be where your pygame is. So its trying to use that as a dotnet.exe. Please look into installing the .NET SDK again to try to resolve this and let me know how it goes.
