### ISSUE TITLE
[NETE2ESDK][Intermittent]Sometimes downloading the .NET SDK failed with timeout.

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1513]
# Describe the bug
Sometimes downloading the .NET SDK failed with timeout.

## Other Info:
Errors the extension may have encountered have likely been added to your terminal or VS Code windows. Please paste it/them here and describe what happened and the problem you are facing.

**Reproduction Steps**
1. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
2. Use the version it provided, which is 7.0.103. Hit enter.
3. Observe

**Expected behavior**
.NET SDK could be downloaded and installed successfully.

**Exceptions & Errors (if any)**
Downloading the .NET SDK failed with timeout.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/20030d62-1d41-4bd5-9844-6d1add95f99f)

**Further technical details**
OS: Mac Monterey X64(12.7)
VSCode: 1.84
Extensions: dotnet-install-tool-2.0.0

**Note**
1. After restarting the VSCode, the SDK could be downloaded and installed successfully
2. It only repro on Mac machine

**Comment by nagilson** [comment]
This should be closed for now as it seems to have been resolved :)
