### ISSUE TITLE
[NETE2ESDK][Intermittent]Sometimes an error occurred while installing .NET SDK

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1514]
# Describe the bug
Sometimes an error occurred while installing .NET SDK
## Other Info:

**Reproduction Steps**
1. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
2. Use the version it provided, which is 7.0.103. Hit enter.
3. Observe

**Expected behavior**
.NET SDK could be downloaded and installed successfully.

**Exceptions & Errors (if any)**
.NET SDK was downloaded and installed successfully, but there is an error occurred on the output.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/2e08240f-4256-4842-ad60-3517fc4ab6df)

**Further technical details**
OS: Mac Monterey X64(12.7)
VSCode: 1.84
Extensions: dotnet-install-tool-2.0.0

**Note**
1. This issue repro on Mac and Windows. The probability of recurrence on Mac is higher, and we met this issue only once on the Windows.

**Comment by v-xiaofchen** [comment]
This issue also repro on Windows 10 X64.

**Comment by nagilson** [comment]
This issue is now resolved.
