### ISSUE TITLE
[NETE2ESDK] It still keep downloading the older SDK even .NET acquisition failed with version conflicts.

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1516]
# Describe the bug
It still downloading the older SDK even .NET acquisition failed with version conflicts.

## Other Info:

**Reproduction Steps**
1. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
2.  Use the version it provided, which is 7.0.403. Hit enter.
3. After .NET 7.0.403 installed, then try to install the older SDK 7.0.402

**Expected behavior**
On windows, the older SDK installation should be failed with version conflicts.

**Exceptions & Errors (if any)**
Even .NET acquisition failed, but still keep downloading the older SDK e
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/cfd73702-0073-4815-aa50-52d153b07010)

**Further technical details**
OS: Win 11 X64 22H2(OS Build 22621.2428)
VSCode: 1.84
Extensions: dotnet-install-tool-2.0.0

**Comment by nagilson** [comment]
Closing this as resolved by the above PR.
