### ISSUE TITLE
Downloading .NET version(s) 7.0.13~x64 (forever)

### ISSUE THREAD

**Issue by Rikitik** [dotnet/vscode-dotnet-runtime#1517]
It just gets stuck downloading when trying to create a launch.json

5-11-2023 15:51:05 DotnetAcquisitionStatusRequested
7.0
390da8ca1cfee2ea2a23052cccf398a432a2e6f0021a8a548672fa7588875248

5-11-2023 15:51:05 WebRequestSent
https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json

5-11-2023 15:51:05 DotnetVersionResolutionCompleted
7.0
7.0.13

5-11-2023 15:51:05 DotnetAcquisitionStatusUndefined
7.0.13~x64

5-11-2023 15:51:05 DotnetCommandSucceeded
acquireRuntimeStatus

**Comment by nagilson** [comment]
May you please attach logs from the extension, they should be in this folder, then go to the folder at the time this issue occurred, then window1/exthost/ms-dotnettools.vscode-dotnet-runtime?

Log location:
Linux:  ~/.config/Code/logs
Mac: ~/Library/Application Support/Code/logs/
Windows: c:\Users\USERNAME\AppData\Roaming\Code\logs\

@ri

**Comment by Rikitik** [comment]
> May you please attach logs from the extension, they should be in this folder, then go to the folder at the time this issue occurred, then window1/exthost/ms-dotnettools.vscode-dotnet-runtime?
> 
> Log location: Linux: ~/.config/Code/logs Mac: ~/Library/Application Support/Code/logs/ Windows: c:\Users\USERNAME\AppData\Roaming\Code\logs\
> 
> @Rikitik

I went back to a previous version that is working perfectly the logs are no longer their since i purged everything just in case

**Comment by nagilson** [comment]
Ok, thanks and let us know if you hit it again so we can help!
