### ISSUE TITLE
[NETE2ESDK][Linux] The distro should not be shown as object in error info when trying to install unsupported .net SDK

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1519]
# Describe the bug
The distro should not be shown as object in output when trying to install unsupported .net SDK

## Other Info:

**Reproduction Steps**
1. On Linux
2. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
3. Use the version that is not supported, which is 5. Hit enter.
4. Observe the error.

**Expected behavior**
1. The error info should be correct.

**Exceptions & Errors (if any)**
The distro should not be shown as object in error info
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/c6b28405-f1fd-415c-97fa-46808e1f7025)

**Further technical details**
OS: Ubuntu 22.04 and 18.04, RHEL 9.2
VSCode: 1.84
Extensions: dotnet-install-tool-2.0.0

**Comment by nagilson** [comment]
This has been  resolved :)
