### ISSUE TITLE
Every package I have just came in at once

### ISSUE THREAD

**Issue by kaycoinsUSA** [dotnet/vscode-dotnet-runtime#152]
Over 2000
[autopep8-1.5.4.tar.gz](https://github.com/dotnet/vscode-dotnet-runtime/files/5647445/autopep8-1.5.4.tar.gz)

**Comment by sfoslund** [comment]
Hi @kaycoinsUSA, thanks for filing an issue. I'm going to close this for now as there is not enough information to be actionable, but please reopen with more information on what the error is. You can do this by pasting in the information copied to your clipboard when you made this issue and attaching the log file listed in the issue body. Thanks!
