### ISSUE TITLE
[NETE2ESDK][Ubuntu22.04] Installing different version .net SDK failed with distro issue on Ubuntu22.04

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1520]
# Describe the bug
 Installing different version .net SDK failed with distro issue on Ubuntu22.04

## Other Info:

**Reproduction Steps**
1. On Ubuntu 22.04 x64
2. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘ and enter 6.0.1xx
3. After 6.0.124 is installed
4. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘ and enter 7.0.103
5. Observe

**Expected behavior**
1. The .net SDK 7.0.103 is installed successfully

**Exceptions & Errors (if any)**
Installing .net SDK 7.0.103 failed with distro issue
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/d0a8c8a9-9fce-4c38-8b63-e9146b0cd458)

**Further technical details**
OS: Ubuntu 22.04
VSCode: 1.84
Extensions: dotnet-install-tool-2.0.0

**Comment by v-xiaofchen** [comment]
This issue also repro on Ubuntu 22.04 Arm64.

**Comment by NicoleWang001** [comment]
Met the same error if installing the same .NET SDK again after restarted VSCode.

**Comment by v-xiaofchen** [comment]
This issue also repro on Ubuntu 23.10.
![ubuntu23 101](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/16ecbb53-7644-468e-ad76-a9906f5f00ad)

**Comment by nagilson** [comment]
The problem here is we should be reading the trimmed output of `readlink -f /usr/bin/dotnet` once we know we can validate that the share or lib folder is the true location for this. The bin location is used by both install types as a symlink

**Comment by nagilson** [comment]
This should be resolved now.

**Comment by NicoleWang001** [comment]
Close it as fixed.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/8dca579c-b7a3-458e-b985-c9a030f7c719)
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/e3367d74-a434-41d6-8efe-a6c36544732c)
