### ISSUE TITLE
[NETE2ESDK][Ubuntu23.10]On Ubuntu 23.10, installing .net SDK failed as cannot read properties of undefined.

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1523]
# Describe the bug
On Ubuntu 23.10, installing .net SDK failed as cannot read properties of undefined.

## Other Info:

**Reproduction Steps**
1. On Ubuntu23.10,
2. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
3. Use the version it provided, which is 7.0.103. Hit enter.
4. Observe

**Expected behavior**
1. The SDK could be installed successfully.

**Exceptions & Errors (if any)**
Installing .net SDK failed as cannot read properties of undefined.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/e8534484-3be2-48c7-809d-9500efec1095)

**Further technical details**
OS: Ubuntu 23.10
VSCode: 1.84
Extensions: dotnet-install-tool-2.0.0

**Comment by nagilson** [comment]
This has been resolved :)
