### ISSUE TITLE
[NETE2ESDK]The failure message should say the installation was cancelled rather than undefined if cancelling .NET SDK installation.

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1567]
# Describe the bug
The failure message should say the installation was cancelled rather than undefined if cancelling .NET SDK installation.

## Other Info:

**Reproduction Steps**
1. On Windows, open VScode not running as administrator
2. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
3. Use the version it provided, which is 7.0.103. Hit enter.
4. On the .NET Installer, click close before it can continue.
5. Observer the error info

**Expected behavior**
1. a failure message saying the installation was cancelled. 

**Exceptions & Errors (if any)**
.NET Acquisition Failed: underfined.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/65b2d1f2-aebd-4cd0-b92d-50ce830cc331)

**Further technical details**
OS: Win 11 22H2 22621.2715
VSCode: 1.84.2
Extensions: vscode-dotnet-install-tool-2-2.0.0

**Comment by nagilson** [comment]
This should be fixed.

**Comment by NicoleWang001** [comment]
This issue is fixed 
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/2e410e4d-ad54-4865-b907-027c00bfa4e3)
