### ISSUE TITLE
[NETE2ESDK][WinArm64] There is a pop-up: .NET Installer appear above VS Code if try installing it again after restarted VSCode.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1571]
# Describe the bug
There is a pop-up: .NET Installer appear above VS Code if try installing it again after restarted VSCode.

## Other Info:

**Reproduction Steps**
1. On WinArm64, open VScode not running as administrator
2. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
3. Use the version it provided, which is 7.0.103. Hit enter.
4. After 7.0.103 is installed succeed, restart VSCode
5. Try to install 7.0.103 again and observe 

**Expected behavior**
The extension should notice the SDK is already installed and give you a message saying it is already installed, there should be NO pop-up.
![ARMEXPECT1](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/84b101fe-68a1-43c7-b29d-f9c627208064)

**Exceptions & Errors (if any)**
 There is a pop-up: .NET Installer appear above VS Code.
![ARMFACT1](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/88554065-96a8-4e46-97d8-3ffd278c6d75)

**Further technical details**
OS: Win 11 Arm64 23H2(OS Build 25398.1)
VSCode: 1.84.2
Extensions: dotnet-install-tool-2.0.0

Note:

1.This issue does not repro with VS Code running as Administrator.
2.This issue is only repro on Win Arm64，not repro on Win X64.

**Comment by BinToss** [comment]
I have not experienced this issue. v2.0.2 works exactly as you expect it...aside from calling showOutput() when a Runtime already exists or an install was already requested. That has led to other extensions' users to upload .NET Runtime's Output instead of the corresponding extension's Output.

**Comment by yinjiehe01** [comment]
@BinToss This issue still repro on v2.0.2 on today's test.
![bug1571](https://github.com/dotnet/vscode-dotnet-runtime/assets/106043488/0f23b402-ab10-43ee-8bcc-4d44774ff076)

**Comment by nagilson** [comment]
This should be fixed pending the next release, please confirm this when the next testing session is done. cc @NicoleWang001

**Comment by v-xiaofchen** [comment]
This issue is fixed and not repro. close it.
![image](https://github.com/user-attachments/assets/a1de9475-15c4-4840-ae9f-44c81072fa62)
