### ISSUE TITLE
[NETE2ESDK] [MAC]The failure message should say the installation was cancelled rather than expected dotnet folder/usr/local/share/dotnet/dotnet does not exist if cancelling .NET SDK installation.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1572]
# Describe the bug

The failure message should say the installation was cancelled rather than expected dotnet folder/usr/local/share/dotnet/dotnet does not exist if cancelling .NET SDK installation.

## Other Info:

**Reproduction Steps**
1. On Mac, run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
2. Use the version it provided, which is 7.0.103. Hit enter.
3. On the .NET Installer, click close before it can continue.
4. Observer the error info

**Expected behavior**
 a failure message saying the installation was cancelled.

**Exceptions & Errors (if any)**
.NET Acquisition Failed: Validation of .dotnet installation for version 7.0.103 failed: Expected dotnet folder/usr/local/share/dotnet/dotnet does not exist.
![Mac1](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/1f64db14-8dac-41fa-91f0-7934944527a0)

**Further technical details**
OS: Mac Ventura X64(13.6.1)
VSCode: 1.84.2
Extensions: dotnet-install-tool-2.0.0

Note:
1.There is also a warning pop up in VS Code about telemetry collection in the bottom right corner.
This pop up will either say
 
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
Read more about .NET CLI Tools telemetry: [https://aka.ms/dotnet-cli-telemetry`](https://aka.ms/dotnet-cli-telemetry%60),

2.This issue is only repro on Mac.

**Comment by nagilson** [comment]
It seems I was mistaken since there even isnt really a custom message for this on windows, it currently just exits with 1 on the installer.

**Comment by nagilson** [comment]
Mac does not have an exit code for cancels and you can  only cancel by hitting X. There does not seem to be a good way for us to catch this at the moment.

**Comment by v-xiaofchen** [comment]
on Extensions: dotnet-install-tool-2.0.9, It actually fail like bellow:
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/3fb7ebb0-868f-4629-aee6-51e51489ffc4)

**Comment by nagilson** [comment]
Unfortunately, it's not possible to detect this on Mac without changes that would make the product overall worse by degrading other areas.
I'm going to mark this as closed as I've eliminated the error and we will just carry on in Mac going forward.

You may need to edit the testing plan to reflect this.
