### ISSUE TITLE
uname command not found

### ISSUE THREAD

**Issue by bboshoven** [dotnet/vscode-dotnet-runtime#1603]
Type: <b>Bug</b>

1. Install vscode on NixOS (using flakes).
2. Installing the C# dev kit extension.
3. Load any C# project.

Extension host gives following error:
2023-12-14 22:42:42.988 [error] Activating extension ms-dotnettools.csharp failed due to an error:
2023-12-14 22:42:42.988 [error] Error: Error: Command failed: uname -m
/bin/sh: line 1: uname: command not found

/bin/sh: line 1: uname: command not found

	at /home/boy/.vscode/extensions/ms-dotnettools.csharp-2.14.8-linux-x64/dist/extension.js:2:1147378
	at ChildProcess.exithandler (node:child_process:439:5)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:322:12)

I suspect with NixOS's different way of handling the path variable, the child process won't start with the correct environment variables. This causes the uname command to not exist.

Extension version: 2.0.0
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.1.67
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|31.32GB (28.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by baronfel** [comment]
Hi, this is a problem in the C# Dev Kit extension, not vscode-dotnet-runtime. Can you please re-open this issue there if it reoccurs?
