### ISSUE TITLE
 NETCoreSDK_Error

### ISSUE THREAD

**Issue by OPPOreno77** [dotnet/vscode-dotnet-runtime#1605]
### Describe the bug.

找不到 .NET Core SDK: Error running dotnet --info: Error: spawn C:\Windows\system32\cmd.exe; ENOENT 。將無法啟用 .NET Core 偵錯。確定 .NET Core SDK 已安裝且位於路徑上。

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

 無

### Expected Behavior

無答案

### Exceptions & Errors (if any)

15511515151affa

### .NET Install Tool Version

.NET7.0/8.0

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

2019

**Comment by baronfel** [comment]
Hi @OPPOreno77 - can you please provide any more of the extension log files so we can help you? We can reopen this once we have that data.

**Comment by OPPOreno77** [comment]
> 切特·胡斯克

我暫時不處理此問題，謝謝您。
