### ISSUE TITLE
how to have using asp.net mvc on controller

### ISSUE THREAD

**Issue by Tunjexy2x** [dotnet/vscode-dotnet-runtime#1610]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\User\AppData\Roaming\Code\logs\20231231T124139\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1704022919880.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by baronfel** [comment]
Hi @Tunjexy2x - please include your log files if you can so we can help you. We can reopen when that's added.
