### ISSUE TITLE
[NETE2ESDK][Linux] Installing .NET SDK failed with error options.name must be alphanumeric only

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1615]
### Describe the bug.

On Ubuntu and RHEL, Installing .NET SDK failed with error options.name must be alphanumeric only

### Reproduction Steps

1. Install VSCode and Extensions on Ubuntu 18.04 or 23.04 or 23.10 x64 or RHEL 9.3 x64
2. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
3. Use the version it provided, which is 7.0.103. Hit enter.
4. Observe

### Expected Behavior

.NET SDK could be downloaded and installed successfully.

### Exceptions & Errors (if any)

Installing .NET SDK failed with error options.name must be alphanumeric only
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/66d50b61-eb2a-45a2-b53b-4730b9c5dc5b)

### .NET Install Tool Version

vscode-dotnet-runtime-2.0.1-alpha-512822

### Your operating system? Please provide more detail, such as the version and or distro above.

Ubuntu 18.04 or 23.04 or 23.10 x64 or RHEL 9.3 x64

### VS Code Version

1.85.1

**Comment by NicoleWang001** [comment]
This issue is also repro with ubuntu22.04-arm64.

**Comment by NicoleWang001** [comment]
This issue is not repro with Mac and Windows.

**Comment by nagilson** [comment]
This should be resolved now

**Comment by NicoleWang001** [comment]
@nagilson   This issue is fixed on RHEL 9.3. But an new error was shown on Ubuntu 
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/c944b749-3518-4a30-8e65-443e4562e748)

**Comment by NicoleWang001** [comment]
Closed it as fixed.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/1f7ba891-ffbe-44a8-9ae7-76c04313e686)
