### ISSUE TITLE
[NETE2ESDK][Redhat9.3][Redhat8.9] Installing different version .net SDK failed as custom dotnet installation exists on Redhat.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1624]
### Describe the bug.

Installing different version .net SDK failed as custom dotnet installation exists on Redhat.

### Reproduction Steps

1. On Redhat 9.3 or 8.9
2. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘ and enter 6.0.1xx
3. After 6.0.124 is installed
4. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘ and enter 7.0.103
5. Observe

### Expected Behavior

The SDK 7.0.103 is installed successfully.

### Exceptions & Errors (if any)

Installing different version .net SDK failed as custom dotnet installation exists
![Redhatbug1](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/0682d062-bcf8-45bc-bacf-9bc6609034ae)

### Further technical details
OS: RHEL 9.3 and 8.9 
VSCode: 1.85.1
Extensions: dotnet-install-tool-2.0.1

### Note
This issue not repro on Ubuntu18.04,22.04 and 23.10.

**Comment by v-xiaofchen** [comment]
The same error if try installing .NET SDK again, here is detailed steps:

On Redhat
Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
Use the version it provided, which is 7.0.103. Hit enter.
After 7.0.103 is installed succeed
Try to install 7.0.103 again and observe the output
![installagain](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/a7626a81-1bac-4660-ad9c-c0d3a386968b)

**Comment by nagilson** [comment]
Hm. I really don't know why this is broken at a cursory check. resolvePathAsSymlink is set to false for the redhat provider and we only resolve the symlink if that's true. And regarding the install, It shouldn't be in bin, that's for sure. Will need to look more closely at this.

**Comment by nagilson** [comment]
I think I have fixed this.

**Comment by NicoleWang001** [comment]
Checked and this issue is fixed.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/ab10f944-8f35-440b-894a-ac5f4471a1ec)
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/ba486a9f-59d2-44d4-8d2b-ed1b46aaa4de)
