### ISSUE TITLE
[NETE2ESDK][Ubuntu22.04][Ubuntu23.10]The failure message should say the installation was installed rather than .NET acquisition failed with undefined if try installing it again on Ubuntu.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1625]
### Describe the bug.

The failure message should say the installation was installed rather than .NET acquisition failed with undefined if try installing it again on Ubuntu.

### Reproduction Steps

1. On Ubuntu 22.04 or 23.10
2. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
3. Use the version it provided, which is 7.0.103. Hit enter.
4. After 7.0.103 is installed succeed
5. Try to install 7.0.103 again and observe the output

### Expected Behavior

The extension should notice the SDK is already installed and give you a message saying it is already installed
![Ubuntu18-04](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/71b1f424-cc88-454a-9622-9f9087afa66e)

### Exceptions & Errors (if any)

It actually failed with .NET Acquisition Failed: undefined.
![Ubuntu22-04](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/09805dce-aa6b-4379-b9ca-44666832659a)

### Further technical details
OS: Ubuntu22.04 and 23.10
VSCode: 1.85.1
Extensions: dotnet-install-tool-2.0.1

### Note
This issue not repro on Ubuntu18.04.

**Comment by nagilson** [comment]
This is more of an issue than I thought since its on newer versions of Ubuntu. Except, I dont know how or why it thinks it has installed the 400 sdk unless something changed with the distro.

**Comment by nagilson** [comment]
This shuold be fixed pending the new testing, please validate this next time. cc @NicoleWang001

**Comment by nagilson** [comment]
I'm going to close this issue; may you confirm it was fixed?
