### ISSUE TITLE
[NETE2ESDK][Linux]The re-installation should be successful after the installation of .NET SDK  is canceled

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1631]
### Describe the bug.

The re-installation should be successful after the installation of .NET SDK is canceled

### Reproduction Steps

1. On Linux
2. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘ and enter 7.0.103
3. Click 'cancel' on 'Authentication Required' windows to cancel the .NET SDK installation.
4. After 7.0.103 is cancelled succeed, try to install 7.0.103 again and observe the output

### Expected Behavior

The re-installation should be successful after the installation of .NET SDK is canceled
![successfully](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/b83e4feb-1c32-4b06-a1ca-238f71c6ebc3)

### Exceptions & Errors (if any)

No download or changes were made as that install has already been requested.
![Linux3](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/793082fe-efdb-4235-9c46-e00ff24d9a15)

### .NET Install Tool Version

dotnet-install-tool-2.0.1

### Your operating system? Please provide more detail, such as the version and or distro above.

Ubuntu 18.04 or 22.04 or 23.10 x64 or RHEL 9.3 x64

### VS Code Version

1.85.1

### Note
This issue is not repro with Mac and Windows.

**Comment by nagilson** [comment]
I think I have fixed this one!

**Comment by NicoleWang001** [comment]
Checked and this issue was fixed.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/5ddb16c1-6c6d-4d56-bc90-43e6f5b942aa)
