### ISSUE TITLE
Follow up work on SDK Extension 

### ISSUE THREAD

**Issue by sfoslund** [dotnet/vscode-dotnet-runtime#165]
- [x] If possible, consolidate SDK extension and uninstall library into one directory/ webpack config. 
- [ ] ~~Consider incorporating existing path configuration setting for SDK extension~~
- [x] Update sample extension to expose SDK commands
- [x] Write test plan for vendor test passes
- [x] Audit/ expand repo documentation
- [x] Add support for adding SDK to PATH on mac
- [x] Add test coverage for adding to PATH

**Comment by sfoslund** [comment]
> Consider incorporating existing path configuration setting for SDK extension

For context, the existing path configuration in the runtime extension allows users to point to an existing .NET runtime install to avoid having the extension download a local copy. It's main goal was to be a workaround for any issues with installing a local copy. 

I would argue that we don't need a similar configuration setting for the SDK extension. The idea behind this extension is to install local copies on students' machines which will presumably not have global .NET installs. If we add this feature to support the global install case it feels like it's encouraging crossing streams in a way that could mess up the user's machine. 

@KathleenDollard @NTaylorMullen @wli3 let me know if you disagree, but for now I'm crossing this off the list as a won't fix.

**Comment by wli3** [comment]
agree. For education bundle we should be more opinionated.
