### ISSUE TITLE
[NETE2ESDK][Regression]There is no message saying that the .NET SDK is already installed if try installing it again.

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1658]
### Describe the bug.

There is no message saying that the .NET SDK is already installed if try installing it again.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

1. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
2. Use the version it provided, which is 7.0.103. Hit enter.
3. After 7.0.103 is installed succeed, try to install 7.0.103 again and observe the output

### Expected Behavior

The extension should notice the SDK is already installed and give you a message saying it is already installed such as  ‘A global install is already on the machine’, then return success as normal.

### Exceptions & Errors (if any)

There is only a success message with the path to dotnet
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/f8ed44f7-3218-4f9c-98ec-f18f3d865830)

### .NET Install Tool Version

2.0.2

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.86.0

**Comment by nagilson** [comment]
This is simply about fixing the messaging, it recognized the install was there and did not do any extra work, it just didnt communicate that.

**Comment by NicoleWang001** [comment]
This issue is sill repro
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/ce6f60d4-c7cb-4627-a6de-589ac49fc29d)

**Comment by nagilson** [comment]
This issue needs to be fixed eventually, but it is not a release blocker. We will need the logs to investigate (please send over the thread) as I am not getting this behavior.

**Comment by v-xiaofchen** [comment]
On windows x64, can see a message saying the SDK is already installed but it seems install 7.0.103 again.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/530bb09d-76ad-453b-ba25-2e24279cfd00)
On windows arm64. it the same behavior  as Linux: There is only a success message with the path to dotnet
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/8cd458d3-941f-44d1-8e02-3d71bbe3107e)

**Comment by v-xiaofchen** [comment]
Run the command multiple times: .NET Install Tool - Install the .NET SDK System-Wide.
There is only a success message with the path to dotnet on Mac-x64.
![image](https://github.com/user-attachments/assets/c3a4e648-4d7a-4513-91e8-21595c6f16a7)
For other OS like MAC-arm64, Linux and windows, can see a message saying the SDK is already installed and give you a message saying it is already installed 
![image](https://github.com/user-attachments/assets/bc1046a2-5955-459b-8397-124c2615097d)

**Comment by v-xiaofchen** [comment]
On .NET Install Tool Version 2.1.7
For Linux and Mac-x64: There is only a success message with the path to dotnet
![image](https://github.com/user-attachments/assets/09640d91-5a6d-4364-a8f3-520df4bf8b42)

**Comment by v-xiaofchen** [comment]
On .NET Install Tool Version 2.2.0
This issue is still repro on Linux and mac.
![image](https://github.com/user-attachments/assets/1b3a267d-5dbe-4484-a048-047daa11055a)

**Comment by nagilson** [comment]
It looks like this is actually fixed. On Linux it should say 'repairing packages.' On Mac, we wouldn't expect this to be the case. It no longer repros for me on win x64. Closing but if this needs to be updated somewhere please lmk.

**Comment by v-xiaofchen** [comment]
@nagilson 
Thank you for your minder, on Mac, the SDK will be installed repeatedly, but after restarting vscode it will show that it is already installed.
![Image](https://github.com/user-attachments/assets/5f3c5c0f-44e7-4266-b63f-b2d1df8da5dc)
If restart vscode, it will show that it is already installed
![Image](https://github.com/user-attachments/assets/7ffaa481-0c5d-413a-9889-45baeba0a822)

**Comment by nagilson** [comment]
Looks good!
