### ISSUE TITLE
[NETE2ESDK][RHEL].NET installation is failed with invalid version if using the command ‘Sample: Acquire .NET Runtime’ and select version ‘7.0.103’

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1661]
### Describe the bug.

On RHLE 9.3, .NET installation is failed with invalid version if using the command ‘Sample: Acquire .NET Runtime’ and select version ‘7.0.103’

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

1. On RHEL 9.3,
2. Run the command ‘Sample: Acquire .NET Runtime’ and select version ‘7.0.103’,
3. Observe.

### Expected Behavior

See that the install has a success message.

### Exceptions & Errors (if any)

.NET installation is failed with invalid version.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/c2e0e8f1-3b91-4f49-bca6-f17072f77d89)

### .NET Install Tool Version

2.0.2

### Your operating system? Please provide more detail, such as the version and or distro above.

Linux

### VS Code Version

1.86.0

**Comment by nagilson** [comment]
This should be fixed with the latest changes :)
