### ISSUE TITLE
[NETE2ESDK][Linux]The command: .NET Install Tool - Install the .NET SDK System-Wide should be shown after enable preview features for the extension.

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1662]
### Describe the bug.

On Linux, the command: .NET Install Tool - Install the .NET SDK System-Wide should be shown after enable preview features for the extension.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

1. On Linux
2. Go to the 'Extensions' tab in VS Code, right click the '.NET Install Tool' and go to 'Extension Settings', then click the box to Enable Preview Features.
3. Restart VSCode and Observe

### Expected Behavior

The command: .NET Install Tool - Install the .NET SDK System-Wide should be shown after enable preview features for the extension.

### Exceptions & Errors (if any)

The command: .NET Install Tool - Install the .NET SDK System-Wide is not shown.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/df4b9e6e-9590-4bf5-a5a5-e9292c0f33e1)

### .NET Install Tool Version

2.0.2

### Your operating system? Please provide more detail, such as the version and or distro above.

Linux

### VS Code Version

1.86.0

**Comment by nagilson** [comment]
I wonder if this is because it is a system with both hypervisor and WSL installed. Need to look into this and improve the logging here.

**Comment by nagilson** [comment]
I think this should be resolved. If not, I improved the logging that will help us diagnose this better.

**Comment by nagilson** [comment]
Confirmed not reproducing :)
