### ISSUE TITLE
Failed to run dotnet-install.sh on Linux

### ISSUE THREAD

**Issue by SignalMQ** [dotnet/vscode-dotnet-runtime#1673]
### Describe the bug.

Extension for AvaloniaUI before initializing the project, calls the dotnet sdk installation command from this extension, but then the installation is terminated due to errors in the logs that I found. There is also another suspicion that the extension does not see the sdk, which is installed manually.

### Please attach log file(s) here if you have any.

[.NET Runtime]
AvaloniaTeam.vscode-avalonia requested to download the .NET Runtime.
Downloading .NET version(s) 8.0.2~x64 ...... Error!
Failed to download .NET 8.0:
Web Request to https://dot.net/v1/dotnet-install.sh Failed: n[r].split is not a function. Aborting. Please ensure that you are online.

 Error!
Failed to download .NET 8.0:
Web Request to https://dot.net/v1/dotnet-install.sh Failed: n[r].split is not a function. Aborting. Please ensure that you are online.

 Done!
.NET 8.0.2~x64 executable path: /home/sobirjon/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.2~x64/dotnet

### Reproduction Steps

**Prerequisites:**
1) `dotnet-sdk-8.0` is installed in your system
2) `AvaloniaUI extension` and `C# DevKit extension` installed

Steps to reproduce:
1) Click `Create Avalonia Project`
2) Select path of project
3) Wait and see logs in `.NET Runtime` section

### Expected Behavior

dotnet-sdk installs with script, but if is already installed, extension skips this step

### .NET Install Tool Version

v2.0.1

### Your operating system? Please provide more detail, such as the version and or distro above.

Linux

### VS Code Version

1.86.2

**Comment by SignalMQ** [comment]
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/77734001/c10d83c0-0ffe-4a14-94d2-f0672c37b10c)

These scripts do not have access to run as a program, can this somehow affect the installation process?

**Comment by nagilson** [comment]
I think this should be fixed in version 2.0.2 once that gets released.

**Comment by nagilson** [comment]
this should be fixed now, lmk if you still encounter this upon downloading the new version! :)
