### ISSUE TITLE
[NETE2ESDK] On Ubuntu 23.10 only, redundant text in Authentication Required prompt.

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1680]
### Describe the bug.

On Ubuntu 23.10 only, redundant text in Authentication Required prompt.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

1. On Ubuntu 23.10,
2. Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
3. Use the version it provided, which is 7.0.103. Hit enter.
4. Observe the prompted Authentication Required

### Expected Behavior

Correct information in Authentication Required prompt
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/e86cea07-5411-4269-bb28-8176d5a4b8ad)

### Exceptions & Errors (if any)

Redundant texte in Authentication Required prompt
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/9ac2d4d5-ab9f-4f31-8258-50569c4c106c)

### .NET Install Tool Version

2.0.2

### Your operating system? Please provide more detail, such as the version and or distro above.

Linux

### VS Code Version

1.86.2

**Comment by nagilson** [comment]
This is great, actually. The reason it did not show this before was due to a bug with VS Code itself and or KDE sudo (linux library VS Code relies on.) Let me know if the doc needs to be updated.
