### ISSUE TITLE
Please paste it into this window

### ISSUE THREAD

**Issue by alexjuniook** [dotnet/vscode-dotnet-runtime#1682]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\lucia\AppData\Roaming\Code\logs\20240227T221621\window1\exthost\ms-dotnettools.vscode-dotnet-sdk\DotNetAcquisition-ms-dotnettools.vscode-dotnet-sdk-1709083787496.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by BinToss** [comment]
No information was provided.
