### ISSUE TITLE
The .NET Install Tool causes that HOME environment variable does not work

### ISSUE THREAD

**Issue by Patrick-Ze** [dotnet/vscode-dotnet-runtime#1686]
Type: <b>Bug</b>

The issue occurs on the Windows platform:

1. Set the user environment variable HOME to a value different from the default user directory and restart VSCode. GPG key is also stored in this directory.
2. Install the .NET Install Tool extension `v2.0.2`.
3. Use the includeif function in .gitconfig, and reference the HOME directory with `~`, for example:
```gitconfig
[includeIf "hasconfig:remote.*.url:git@gitlab.mydomain.ai:*/**"]
	path = ~/gitconfig/mydomain.conf
```
4. Configure the GPG key in `mydomain.conf`.
```ini
[user]
	name = First Last
	email = first.last@mydomain.ai
	signingkey = AABBCCDDEEFF
[commit]
	gpgsign = true
```
6. Attempt to commit a change using the VSCode Source Control GUI.
7. Encounter an error:
```log
gpg: directory '/c/Users/first.last/.gnupg' created
gpg: keybox '/c/Users/first.last/.gnupg/pubring.kbx' created
gpg: skipped "First Last <first.last@mydomain.ai>": No secret key
gpg: signing failed: No secret key
error: gpg failed to sign the data
fatal: failed to write commit object
```
9. Note: if I commit in the integrated terminal instead of source control panel, everything works.
10. Disable this extension, then the problem is gone.

Extension version: 2.0.2
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (16.23GB free)|
|Process Argv|C:\\Data\\VSCode\\#\\Gen2.code-workspace --crash-reporter-id 7ebef2d2-e730-4917-89f7-db088c3d217a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627cf:30244335
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
edj9j583:30958191
a89i1917:30961429

```

</details>

**Comment by meadowsjared** [comment]
I have a very similar issue, I believe our errors have the same root cause:
Installing the .NET Install Tool extension causes the VSCode source control GUI to no longer be able to read the global gitconfig.
If I install it, and then trying to commit using VSCode's Source Control GUI throws this error:
<details>
  <summary>Author identity unknown</summary>

```2024-03-05 08:09:48.636 [info] > git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file - --signoff -S [79ms]
2024-03-05 08:09:48.636 [info] Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: no email was given and auto-detection is disabled
2024-03-05 08:09:48.729 [info] > git config --get-all user.name [88ms]
2024-03-05 08:09:48.746 [info] No remotes found in the git config file.
2024-03-05 08:09:48.841 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/main refs/remotes/main [96ms]
2024-03-05 08:09:48.842 [warning] No such branch: main.
2024-03-05 08:09:48.842 [info] > git config --get commit.template [107ms]
2024-03-05 08:09:48.925 [info] > git status -z -uall [79ms]
```

</details>


even though I have set my name and email in my ~/.gitconfig file using
```
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
```
as they suggest.

It appears the after installing this extension, somehow the global gitconfig is not able to be read.  However it should be noted that if I manually set my name and email for every repo locally, then it will work fine.

However, this is not a long-term solution, and this extension is somehow interfering with git reading the global config. 🤔 

It should be noted, that this behavior does not happen if I'm using VSCode through WSL, it only throws this error when using it just through Windows. ¯\\\_(ツ)\_/¯

**Comment by nagilson** [comment]
That's extremely strange but its a very frustrating behavior... 

The only thing I can think of is we changed how the extension loads, to load after startup instead of when the extension is first called. But it will need more investigation, I dont know why this would impact Git....

**Comment by pbl-pw** [comment]
maybe same issue: https://github.com/dotnet/vscode-dotnet-runtime/issues/1400
