### ISSUE TITLE
Why the plugin always try to install .net7?

### ISSUE THREAD

**Issue by LurkyVAR** [dotnet/vscode-dotnet-runtime#1696]
### Describe the bug.

My project never mentions .net7 at all ,but everytime after vscode opened  a .net project the plug
![2024-03-09 145002](https://github.com/dotnet/vscode-dotnet-runtime/assets/19261276/08f28c14-5e6c-4b38-94a2-9c7faedabf34)
in starts  downloading .net7.

### Please attach log file(s) here if you have any.

ms-dotnettools.csdevkit requested to download the .NET Runtime.
Downloading .NET version(s) 7.0.16~x64 .....................................................................................................................................................................................

### Reproduction Steps

Just create project by using .net8 , and open the fold in vscode.

### Expected Behavior

I hope never download .net sdk which not be used in project. 
And ask whether editing the project config or downloading requiring .net before just start downloading.

### .NET Install Tool Version

 v2.0.2

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.87.1(user setup)

**Comment by nagilson** [comment]
.NET 7 is what Devkit and the C# extension run on, so they need it.
