### ISSUE TITLE
NET:NEW

### ISSUE THREAD

**Issue by jvsting** [dotnet/vscode-dotnet-runtime#1710]
### Is your feature request related to a problem? Please describe.

// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
Console.WriteLine("The current time is " + DateTime.Now);

### A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

Terminal
Hello, World!
The current time is 3/18/2024 10:24:42 AM

### Describe the solution you'd like

Terminal
Hello, World!
The current time is 3/18/2024 10:24:42 AM

### Additional context

Terminal
Hello, World!
The current time is 3/18/2024 10:24:42 AM

**Comment by nagilson** [comment]
The current time is 3/18/2024 10:24:42 AM
