### ISSUE TITLE
vs

### ISSUE THREAD

**Issue by kiruedmond13** [dotnet/vscode-dotnet-runtime#1715]
### Describe the bug.

s

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

c

### Expected Behavior

c

### Exceptions & Errors (if any)

c

### .NET Install Tool Version

v2.0.0

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.84.2

**Comment by nagilson** [comment]
sccc
