### ISSUE TITLE
inicialize php in xampp

### ISSUE THREAD

**Issue by rcg28061954** [dotnet/vscode-dotnet-runtime#1756]
### Describe the bug.

PHP 8.2.12 (cli) (built: Oct 24 2023 21:15:15) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
    with Xdebug v3.3.1, Copyright (c) 2002-2023, by Derick Rethans
zend_mm_heap corrupted

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

PS C:\xampp\htdocs\_POC\ADM> php -v

### Expected Behavior

i can not begin

### .NET Install Tool Version

PHP 8.2.12

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.88.1 user setup

**Comment by baronfel** [comment]
Hi, I think you have the wrong repo. This repo is for .NET SDK and Runtime installation, not PHP. Try looking in your extensions list for the PHO extension and seeing if they have a listed repository URL or issue-reporting URL, and provide them this same information - they might be able to help you more.
