### ISSUE TITLE
end of central directory record signature not found: CorruptZip: end of central directory record signature not found

### ISSUE THREAD

**Issue by HARKINGS** [dotnet/vscode-dotnet-runtime#1774]
### Describe the bug.

Can not Install ".NET Extension Pack" extension

### Please attach log file(s) here if you have any.

Windows: (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:117226)

### Reproduction Steps

Click Install, the notification "Error while installing '.NET Extension Pack' extension. Please check the [log](command:workbench.action.showWindowLog) for more details." appear. Click [Log], found an Error "end of central directory record signature not found: CorruptZip: end of central directory record signature not found"

### Expected Behavior

Try Downloading Manual file "ms-dotnettools.vscode-dotnet-pack-1.0.13.vsix", I dont know how to use this file and location to save file

### .NET Install Tool Version

v1.0.13

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.88.1

**Comment by nagilson** [comment]
May you create this at https://github.com/dotnet/vscode-dotnet-pack/issues?
