### ISSUE TITLE
 ms-dotnettools.vscode-dotnet-runtime high cpu on arm64

### ISSUE THREAD

**Issue by edgedj** [dotnet/vscode-dotnet-runtime#1775]
Type: <b>Bug</b>

On Macbook Air with arm64, since upgrading to .net 8 - I'm seeing high cpu usage from VS Code - appearing as dotnet taking over 100% cpu when nothing is happening. Ran Bisect Utility and it narrowed the results to this:

Extension Bisect is done and has identified ms-dotnettools.vscode-dotnet-runtime as the extension causing the problem.

Extension version: 2.0.3
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:43:08.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 8, 8|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv|--crash-reporter-id bb93bbf0-8b02-48a4-a972-fb6c617dcdd9|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nagilson** [comment]
seems similar to https://github.com/dotnet/vscode-csharp/issues/7068

**Comment by nagilson** [comment]
If you have the info we requested in that issue, that would be really useful to help us help you with this issue.
