### ISSUE TITLE
Consider separate SDK update command

### ISSUE THREAD

**Issue by sfoslund** [dotnet/vscode-dotnet-runtime#178]
Since we have decided that the education bundle will be the only user of the SDK extension and they will only be requesting one version of the SDK at a time, we could consider adding an explicit update command. With the runtime extension we achieve update behavior with repeated acquire commands but one drawback to this is that we don't remove old patch versions while updating to newer patches. This isn't much of a concern with runtimes, which are relatively small, but if we repeatedly acquire new SDK versions without removing the previous one(s) the size will quickly get unwieldly. 

If we can assume that only one SDK is needed at a time then implementing such a command should be simple as it would be a combination of the existing uninstallAll and acquire commands. 

@NTaylorMullen @KathleenDollard do you have any thoughts here?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen @KathleenDollard do you have any thoughts here?

That'd absolutely be a valuable thing to have to "force" an update; however, it makes me ask the question: Would this be "instead" of automatic updating?

**Comment by sfoslund** [comment]
> Would this be "instead" of automatic updating?

I'm not sure I follow the question. 

I think in general if we can make the assumption that we will only be managing one SDK at a time it will make things a lot cleaner. Another area I'm thinking about is the install directories and the fact that we're installing to `.dotnet/version` right now. This means that every time we install a new version we have to add it to the PATH separately, which feels like overkill.

**Comment by NTaylorMullen** [comment]
> > Would this be "instead" of automatic updating?
> 
> I'm not sure I follow the question.
> 
> I think in general if we can make the assumption that we will only be managing one SDK at a time it will make things a lot cleaner. Another area I'm thinking about is the install directories and the fact that we're installing to `.dotnet/version` right now. This means that every time we install a new version we have to add it to the PATH separately, which feels like overkill.

oooo It wasn't you it was me. I misunderstood your original question. So I totally agree, there's no reason to support multiple SDKs IMO. Especially since they're supppposedddd to be backwards compat right? Aka a 6.0 can build >= 3.1 <=6.0 right?

So with that being said you could provide an "update my existing version" which in turn would be more like "move me to the next major" I imagine. Sounds reasonable.

**Comment by sfoslund** [comment]
> Especially since they're supppposedddd to be backwards compat right? Aka a 6.0 can build >= 3.1 <=6.0 right?

Yup!

> So with that being said you could provide an "update my existing version" which in turn would be more like "move me to the next major or minor" I imagine. 

Right, or the latest patch, which I imagine would be the most common scenario.

**Comment by NTaylorMullen** [comment]
> Right, or the latest patch, which I imagine would be the most common scenario.

Wouldn't latest patch be auto updated to though?

**Comment by sfoslund** [comment]
Closing as this is no longer needed.
