### ISSUE TITLE
Conversion and Build Errors with .NET Framework Project in C# Dev Kit

### ISSUE THREAD

**Issue by tuanngocfun** [dotnet/vscode-dotnet-runtime#1786]
### Describe the bug.

I am encountering multiple issues when trying to load a traditional .NET Framework project file (CommonLanguageRuntimeLibrary.csproj) into the C# Development Kit. The project fails to load due to its unsupported format and issues with MSBuild expressions. This bug report includes detailed error messages and a description of the unsuccessful conversion attempt to the new SDK style.

### Please attach log file(s) here if you have any.

The relevant logs are from the session where the errors were encountered.
[Projects.log](https://github.com/dotnet/vscode-dotnet-runtime/files/15186312/Projects.log)

### Reproduction Steps

1. Open the C# Dev Kit.
2. Attempt to load the CommonLanguageRuntimeLibrary.csproj file.
3. Observe the error messages related to unsupported project format and MSBuild issues.

### Expected Behavior

The project should load successfully without errors, properly interpreting MSBuild expressions and supporting the traditional .NET Framework project format within the new SDK constraints.

### Exceptions & Errors (if any)

- Error loading project due to unsupported format.
- MSBuild expression format errors.
- Repeated import errors for Microsoft.CSharp.targets.

### .NET Install Tool Version

v2.0.3

### Your operating system? Please provide more detail, such as the version and or distro above.

Linux

### VS Code Version

1.88.1

**Comment by baronfel** [comment]
This repository is not the correct location for issues with the C# DevKit - please raise this issue over at [microsoft/vscode-dotnettools](https://github.com/microsoft/vscode-dotnettools).
