### ISSUE TITLE
.NET 5.0 SDK not found in cmd if older SDK is already installed

### ISSUE THREAD

**Issue by vsccarl** [dotnet/vscode-dotnet-runtime#179]
If you install .NET SDK 3.1.406 alongside the DotNet coding pack, when you run `dotnet --info` in command prompt, it only shows that SDK 3.1.406 is installed. Installing 3.1.406 before or after the coding pack, or restarting cmd after opening VS Code, or signing in/out doesn't change the outcome. If 3.1 is uninstalled, running `dotnet --info` shows that .NET 5 SDK is installed.

![image](https://user-images.githubusercontent.com/12900364/109231171-ec5a7a00-777a-11eb-950e-de7be016c55f.png)

**Comment by sfoslund** [comment]
This is expected, the vscode-dotnet-sdk extension should not be used along side global installations of the SDK.
