### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by hoailuong123** [dotnet/vscode-dotnet-runtime#1798]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /Users/lethihoailuong/Library/Application Support/Code/logs/20240511T091240/exthost1/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1715399422909.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by baronfel** [comment]
Please provide more details before we can investigate your issue. The extension logs from within the VSCode Extension State Directory would be a great start.
