### ISSUE TITLE
visualstudiotoolsforunity.vstuc requested to download the .NET Runtime. Using configured .NET path: /usr/local/share/dotnet/dotnet

### ISSUE THREAD

**Issue by ozgurcll** [dotnet/vscode-dotnet-runtime#1799]
### Describe the bug.

visualstudiotoolsforunity.vstuc requested to download the .NET Runtime.
Using configured .NET path: /usr/local/share/dotnet/dotnet

"dotnetAcquisitionExtension.existingDotnetPath": [
    
        {
            "extensionId": "visualstudiotoolsforunity.vstuc",
            "path": "/usr/local/share/dotnet/dotnet"
        },
        {
            "extensionId": "ms-dotnettools.csdevkit",
            "path": "/usr/local/share/dotnet/dotnet"
        },
        {
            "extensionId": "ms-dotnettools.vscodeintellicode-csharp",
            "path": "/usr/local/share/dotnet/dotnet"
        },
        {
            "extensionId": "ms-dotnettools.csharp",
            "path": "/usr/local/share/dotnet/dotnet"
        },
        {
            "extensionId": "ms-dotnettools.vscode-dotnet-runtime",
            "path": "/usr/local/share/dotnet/dotnet"
        },
        {
            "extensionId": "msazurermtools.azurerm-vscode-tools",
            "path": "/usr/local/share/dotnet/dotnet"
        }
    ],

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

doesnt work anything

### Expected Behavior

doesnt work anything

### .NET Install Tool Version

v2.0.5

### Your operating system? Please provide more detail, such as the version and or distro above.

OSX / Darwin / Mac

### VS Code Version

1.89.1

**Comment by baronfel** [comment]
Our extension said that it was using your configured location, so this extension isn't doing anything. Please reach out to the extensions you're trying to use to triage your issue.
