### ISSUE TITLE
Offline installer fails to install extensions 

### ISSUE THREAD

**Issue by vsccarl** [dotnet/vscode-dotnet-runtime#180]
Install with the offline installer:

![image](https://user-images.githubusercontent.com/12900364/109232163-b5856380-777c-11eb-9839-2ffea4a30960.png)

**Comment by sfoslund** [comment]
@mavasani this should probably go to vscode-dotnet-pack too, right?

**Comment by vsccarl** [comment]
@sfoslund Moved to [#32](https://github.com/dotnet/vscode-dotnet-installer/issues/32)
