### ISSUE TITLE
SDK_FLUTTER

### ISSUE THREAD

**Issue by Camilosato23** [dotnet/vscode-dotnet-runtime#1800]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\camil\AppData\Roaming\Code\logs\20240513T090305\window1\exthost\ms-dotnettools.vscode-dotnet-sdk\DotNetAcquisition-ms-dotnettools.vscode-dotnet-sdk-1715610930926.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by baronfel** [comment]
Please provide more details before we investigate your issue.
