### ISSUE TITLE
.NET Getting Started page opens every time VS Code is opened

### ISSUE THREAD

**Issue by vsccarl** [dotnet/vscode-dotnet-runtime#181]
After closing the Getting Started page, or open a folder with a project, or opening a new folder, the Getting Started page continues to reopen.

**Comment by sfoslund** [comment]
@mavasani I assume this is an issue with vscode-dotnet-pack?

**Comment by vsccarl** [comment]
Moved to [#33](https://github.com/dotnet/vscode-dotnet-installer/issues/33)
