### ISSUE TITLE
[NETE2ESDK] There is no an error popup in the bottom right corner of VSCode, if enter an invalid version. 

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1826]
### Describe the bug.

There is no an error popup in the bottom right corner of VSCode, if enter an invalid version. 

### Reproduction Steps

1.Run the 'Sample: Acquire .NET runtime' command. You should be asked to enter a Major.Minor version, please enter an invalid version (for example, 'foo'). 
2.observe the output

### Expected Behavior

There is an error popup in the bottom right corner of VSCode, as seen below.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/80bb469d-09b8-44fa-a525-6fd20a00a179)

### Exceptions & Errors (if any)

There is no an error popup in the bottom right corner of VSCode, if enter an invalid version. 
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/d032e801-59db-466c-ba0e-bbb2ebfa31cb)

### .NET Install Tool Version

2.0.6

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.90.0

**Comment by v-xiaofchen** [comment]
The similar issue if try running the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘. here is detailed steps:
Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
Use the version '' and hit enter
observe the output
Expected Result:  
This should fail with an error that no version is provided. 
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/0223ab8c-297c-4724-a5f3-d07a754be186)
But there is no an error popup in the bottom right corner of VSCode Like bellow:
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/e8878087-4a3a-4e20-9114-7d8d2faec766)

**Comment by nagilson** [comment]
Interesting, thank you for pointing this out. This is lower priority than some of our other bugs but I will keep this in mind.

**Comment by Sapo07** [comment]
> ### Describe el error.
> No aparece una ventana emergente de error en la esquina inferior derecha de VSCode si ingresa una versión no válida.
> 
> ### Pasos de reproducción
> 1.Ejecute el comando 'Muestra: Adquirir tiempo de ejecución .NET'. Se le debe solicitar que ingrese una versión Major.Minor; ingrese una versión no válida (por ejemplo, 'foo'). 2.observar la salida
> 
> ### Comportamiento esperado
> Hay una ventana emergente de error en la esquina inferior derecha de VSCode, como se ve a continuación. ![imagen](https://private-user-images.githubusercontent.com/99376012/337134375-80bb469d-09b8-44fa-a525-6fd20a00a179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzYzMDAsIm5iZiI6MTcxODEzNjAwMCwicGF0aCI6Ii85OTM3NjAxMi8zMzcxMzQzNzUtODBiYjQ2OWQtMDliOC00NGZhLWE1MjUtNmZkMjBhMDBhMTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDIwMDAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZDViZWE2ZjBmOGVlOTM5ZjhlOGI5ZDJmOWRiNjBlMTJmNDQwNjJlZWY2NGQyYzc4ZDVlYTFhM2E1YWU4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CeXTmfpEGZxjKjh9gAp6TO9DeukHG3PcMs5nDnlpZjI)
> 
> ### Excepciones y errores (si los hay)
> No aparece una ventana emergente de error en la esquina inferior derecha de VSCode si ingresa una versión no válida. ![imagen](https://private-user-images.githubusercontent.com/99376012/337134512-d032e801-59db-466c-ba0e-bbb2ebfa31jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzYzMDAsIm5iZiI6MTcxODEzNjAwMCwicGF0aCI6Ii85OTM3NjAxMi8zMzcxMzQ1MTItZDAzMmU4MDEtNTlkYi00NjZjLWJhMGUtYmJiMmViZmEzMWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDIwMDAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MGVjZGQwNjNkZjM0NWE0Yzc4N2FlMzc3NTQ0ZWU5NmE2Y2E0NTM3MmIzZWJlNTk1ZDY5OGQzZjQ0OGE0NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h2g2CYpBfuC47E5A30_F2Tf6uCWQDWqdTxcvR6nDVWE)
> 
> ### Versión de la herramienta de instalación .NET
> 2.0.6
> 
> ### ¿Su sistema operativo? Proporcione más detalles, como la versión o la distribución anteriores.
>blockchair
> 
> ### Versión del código VS
> 1.90.0

1

**Comment by Sapo07** [comment]
Arte

**Comment by Sapo07** [comment]
[Magic Eden - Terms of Service (1).pdf](https://github.com/user-attachments/files/15794213/Magic.Eden.-.Terms.of.Service.1.pdf)

**Comment by v-xiaofchen** [comment]
The similar issue on Linux Does Not Install if Custom Install Exists ,here is detailed steps:
Install .NET using the install script by following [Install .NET on Linux without using a package manager - .NET | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install)
After this, run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
Use the version it provided, which is 7.0.103. Hit enter.
observe the output
Expected Result:
There is an error popup in the bottom right corner of VSCode Like bellow:
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/aa6146e3-edab-49a2-9ba3-dd5ac9002f6b)
But there is no an error popup in the bottom right corner of VSCode Like bellow:
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/01bfe496-40bc-47fe-9239-3c8ef05b836a)

**Comment by nagilson** [comment]
Bumping in priority since this seems to be a more global issue in the code. Not a release blocker

**Comment by v-xiaofchen** [comment]
On 2.1.6, there is an error popup in the bottom right corner of VS Code, but the "Manual Configuration" option is missing
![image](https://github.com/user-attachments/assets/0521f0cf-d1c4-4825-951a-b40e7c25705a)

**Comment by v-xiaofchen** [comment]
On 2.1.7, There is no an error popup in the bottom right corner of VSCode, if enter an invalid version.
![image](https://github.com/user-attachments/assets/a3a21582-bb85-45f0-82fa-52ef0cd37baf)
