### ISSUE TITLE
[NETE2ESDK][Loc] Installing .NET SDK failed in Simple Chinese OS

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/vscode-dotnet-runtime#1827]
### Describe the bug.

Installing .NET SDK failed in Simple Chinese OS

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Try to install the .NET SDK System-Wide in Simple Chinese Windows OS.

### Expected Behavior

SDK could be installed succeed.

### Exceptions & Errors (if any)

Failed to download .NET 8.0.301~unknown: .NET Acquisition Failed: The requested version
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/d705ad85-7561-41cc-986c-6be1a041d571)

### .NET Install Tool Version

2.0.6, 2.0.5

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.90.0

**Comment by NicoleWang001** [comment]
.NET SDK could be installed successfully in English OS.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/1e99f2c8-33b3-464a-ba6b-b4c968be2750)

**Comment by nagilson** [comment]
this should be fixed pending the new build

**Comment by NicoleWang001** [comment]
Thanks, @nagilson. Checked the new build, this issue was fixed. So close it.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/1578239/1f6eac6a-7231-44d8-908f-f2303302dee8)
