### ISSUE TITLE
Wrong target when start debugging from sub-folder projects

### ISSUE THREAD

**Issue by trannamtrung1st** [dotnet/vscode-dotnet-runtime#1837]
### Describe the bug.

My VSCode just auto-updated the C# Dev Kit extension to v1.8.2, and then my debugging suddenly failed.
My project is located inside a sub-folder and the generated `dotnet build` command has an incorrect `target` argument.
I had to revert back to a previous stable version to make it work again.

### Please attach log file(s) here if you have any.

dotnet: build /Users/trungtran/MyPlace/Personal/Learning/workflow-engines-learning/Samples/WELearning.ConsoleApp.Testing/WELearning.ConsoleApp.Testing.csproj 

dotnet build /Users/trungtran/MyPlace/Personal/Learning/workflow-engines-learning/WELearning.sln /target:WELearning_ConsoleApp_Testing /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:Configuration=Debug /p:Platform="Any CPU" 
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/trungtran/MyPlace/Personal/Learning/workflow-engines-learning/WELearning.DynamicCodeExecution.Engines.CSharpCompiled/WELearning.DynamicCodeExecution.Engines.CSharpCompiled.csproj : error MSB4057: The target "WELearning_ConsoleApp_Testing" does not exist in the project.
/Users/trungtran/MyPlace/Personal/Learning/workflow-engines-learning/WELearning.DynamicCodeExecution.Engines.V8Javascript/WELearning.DynamicCodeExecution.Engines.V8Javascript.csproj : error MSB4057: The target "WELearning_ConsoleApp_Testing" does not exist in the project.
/Users/trungtran/MyPlace/Personal/Learning/workflow-engines-learning/WELearning.DynamicCodeExecution.Engines.CSharpScript/WELearning.DynamicCodeExecution.Engines.CSharpScript.csproj : error MSB4057: The target "WELearning_ConsoleApp_Testing" does not exist in the project.
/Users/trungtran/MyPlace/Personal/Learning/workflow-engines-learning/Jint/Jint/Jint.csproj : error MSB4057: The target "WELearning_ConsoleApp_Testing" does not exist in the project.
/Users/trungtran/MyPlace/Personal/Learning/workflow-engines-learning/WELearning.Shared/WELearning.Shared.csproj : error MSB4057: The target "WELearning_ConsoleApp_Testing" does not exist in the project.
/Users/trungtran/MyPlace/Personal/Learning/workflow-engines-learning/WELearning.DynamicCodeExecution/WELearning.DynamicCodeExecution.csproj : error MSB4057: The target "WELearning_ConsoleApp_Testing" does not exist in the project.
/Users/trungtran/MyPlace/Personal/Learning/workflow-engines-learning/Samples/WELearning.ConsoleApp.Testing/WELearning.ConsoleApp.Testing.csproj : error MSB4057: The target "WELearning_ConsoleApp_Testing" does not exist in the project.
/Users/trungtran/MyPlace/Personal/Learning/workflow-engines-learning/WELearning.DynamicCodeExecution.Engines.JintJavascript/WELearning.DynamicCodeExecution.Engines.JintJavascript.csproj : error MSB4057: The target "WELearning_ConsoleApp_Testing" does not exist in the project.
/Users/trungtran/MyPlace/Personal/Learning/workflow-engines-learning/Samples/WELearning.Samples.DeviceService/WELearning.Samples.DeviceService.csproj : error MSB4057: The target "WELearning_ConsoleApp_Testing" does not exist in the project.
/Users/trungtran/MyPlace/Personal/Learning/workflow-engines-learning/WELearning.Core/WELearning.Core.csproj : error MSB4057: The target "WELearning_ConsoleApp_Testing" does not exist in the project.

 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

### Reproduction Steps

1. Create a solution
2. Create a sub-folder (physical)
3. Create a project inside that sub-folder
4. Add to solution
5. Start debugging from the project `Program.cs` file

### Expected Behavior

Should start debugging like normal

### .NET Install Tool Version

v2.0.6

### Your operating system? Please provide more detail, such as the version and or distro above.

OSX / Darwin / Mac

### VS Code Version

1.90.0

**Comment by a-magdy** [comment]
I've been facing the exact same issue

I've reset everything possible, restarted the machine multiple times, cleaned my solution's all build folders multiple times.. nothing worked

I even Deleted VSCode and other VS folders:
rm -rf "$HOME/Library/Application Support/Code"
rm -rf "$HOME/.vscode"

Still didn't work

When I run directly in the terminal is works just fine

So what I do know, is I run from the terminal directly using
dotnet run --project <path>
then I do a .Net core Attach from VSCode using the default config


{
"name": ".NET Core Attach",
"type": "coreclr",
"request": "attach"
},

**Comment by a-magdy** [comment]
Well it turned out it is an issue in the VSCode (C# Dev Kit) extension 
An update was released yesterday which has the issue
Can you select that extension and (Install Another Version) and select the one the was released 3 weeks ago
Until they fix it

![Screenshot 2024-06-13 at 23 06 22](https://github.com/dotnet/vscode-dotnet-runtime/assets/14139855/01e64090-4d77-4596-8aaf-577f87acb04c)

![Screenshot 2024-06-13 at 23 06 34](https://github.com/dotnet/vscode-dotnet-runtime/assets/14139855/5f6fd1e7-b67e-4700-b35c-21cdb93abe0f)

**Comment by a-magdy** [comment]
The issue on the C# Dev Kit about the same problem

https://github.com/microsoft/vscode-dotnettools/issues/1195

I think you should close this one here, as this isn't the repo with the problem

**Comment by trannamtrung1st** [comment]
@a-magdy Thanks. I see the issue there. Will close this for now.
