### ISSUE TITLE
VS Code can compile and run project, but highlights .Net dependencies as missing

### ISSUE THREAD

**Issue by GerryOnGithub** [dotnet/vscode-dotnet-runtime#1841]
### Describe the bug.

I first logged the issue here: https://stackoverflow.com/questions/78599036/vs-code-with-net-syntax-highlighting-problems-incorrectly?noredirect=1#comment138581132_78599036

![Screenshot 2024-06-15 073417](https://github.com/dotnet/vscode-dotnet-runtime/assets/23443806/b9f71793-7469-4c4e-bc96-f4bd3cc0f26a)
![Screenshot 2024-06-15 073454](https://github.com/dotnet/vscode-dotnet-runtime/assets/23443806/53b261b5-8dbe-4178-959c-5be00eab98fb)

![Screenshot 2024-06-15 073800](https://github.com/dotnet/vscode-dotnet-runtime/assets/23443806/b199cce7-574f-417f-9782-e95fb66969d3)

![Screenshot 2024-06-15 074235](https://github.com/dotnet/vscode-dotnet-runtime/assets/23443806/3a65c961-0da6-48c8-bdb9-bd59c8335ee5)

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Open a complex .Net project the was originally created in Visual Studio and open in VS Code that has the .Net extensions

### Expected Behavior

Proper highlighting of errors

### Exceptions & Errors (if any)

program compiles and runs

### .NET Install Tool Version

v2.0.6

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.90.0

**Comment by baronfel** [comment]
This should be logged at the microsoft/vscode-dotnettools repo, the repo for the actual editor functionality. This repo is a helper extension only for installing the .NET Runtime/SDK if a developer doesn't have a required one present.
