### ISSUE TITLE
The .NET Install Tool returned an unexpected result. Please view the 'Output' -> '.NET Install Tool' window for more info.

### ISSUE THREAD

**Issue by AliRamazanYildirim** [dotnet/vscode-dotnet-runtime#1844]
### Describe the bug.

Error
Failed to download .NET 8.0.106-global~x64:
.NET Acquisition Failed: Cancelling .NET Install, as command apt-get update returned with status 100.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

.NET Acquisition Failed: Cancelling .NET Install, as command apt-get update returned with status 100.

### Expected Behavior

.NET Acquisition Failed: Cancelling .NET Install, as command apt-get update returned with status 100.

### .NET Install Tool Version

.Net 8

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.90.1

**Comment by nagilson** [comment]
This should be fixed in version 2.1.1. let us know if you still experience it, please.
