### ISSUE TITLE
[NETE2ESDK]Add support for Ubuntu24.04.

### ISSUE THREAD

**Issue by yinjiehe01** [dotnet/vscode-dotnet-runtime#1872]
### Describe the bug.

Unable to install .NET SDK by using sample command

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

1.install the VS Code in a clean Ubuntu 24.04 machine.
2.install the sample and dotnet-install-tool extension in VS Code.
3.F1->Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)

### Expected Behavior

.NET SDK should be installed successfully

### Exceptions & Errors (if any)

Unable to install the .NET SDK as it shows Ubuntu 24.04 does not offically support dotnet version 7.0.103/6.0.132
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/106043488/07b1d92c-ecd3-4008-872f-5151e479ee4e)
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/106043488/c0ef4730-bf18-43bc-9c9b-44f3250601e4)

### .NET Install Tool Version

2.0.9

### Your operating system? Please provide more detail, such as the version and or distro above.

Linux

### VS Code Version

1.91.0

**Comment by nagilson** [comment]
Does it work for .NET 8?

**Comment by yinjiehe01** [comment]
Yes, it works well for .NET 8
![image](https://github.com/user-attachments/assets/15f4bae3-cab3-47cd-91b5-a3c11e0ef96b)

**Comment by yinjiehe01** [comment]
@nagilson This issue still repro's on 6.0 and 7.0, not repro on 8.0 in build 2.1.0.

**Comment by nagilson** [comment]
Thank you for testing. @yinjiehe01 for this product, ubuntu only supports .NET 8 so this is the correct behavior. .NET 6 is only supported via a backport and there is no official build of .NET 6 for ubuntu 24.04. 

Should we update the testing document to reflect this information? If so and you have edit permission, you are free to do so. :)
