### ISSUE TITLE
[NETE2ESDK] [Ubuntu]Failed to download .NET 8.0.1xx.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1873]
### Describe the bug.

Failed to download .NET 8.0.1xx.

### Reproduction Steps

1.Run the '.NET Install Tool - Install the .NET SDK System-Wide' command. The command should suggest the newest stable version of .NET. Right now on Linux it should suggest 8.0.1xx.
2.Hitting enter to install and observe the output

### Expected Behavior

This should install the newest 8.0.1xx version of the .NET SDK that is released.

### Exceptions & Errors (if any)

Failed to download .NET 8.0.1xx.
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/50881194-9d70-4385-895d-4e31122d4b3f)

### .NET Install Tool Version

dotnet-install-tool-2.0.9

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.91.0

### Note
This issue not repro on Windows, Mac and Red hat

**Comment by v-xiaofchen** [comment]
This issue also repro on 7.0.1xx and 6.0.1xx via sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)
7.0.1xx:
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/9628be48-86a5-46bb-b82f-36726542d1b4)
6.0.1xx:
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/99376012/27fc3398-b63f-471c-ac36-5c4f989e4139)

**Comment by nagilson** [comment]
this should be fixed, please try it again.

**Comment by v-xiaofchen** [comment]
This issue is fixed on the new build.
![image](https://github.com/user-attachments/assets/5876c555-f2aa-4576-97d7-842bc869d038)
