### ISSUE TITLE
**Error Message:** .NET Acquisition Failed: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by jamesdedon** [dotnet/vscode-dotnet-runtime#1889]
### Describe the bug.

Please attach the log file located at /Users/dedo3671/Library/Application Support/Code/logs/20240718T084913/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1721310558919.txt. Note that this file may contain personal data.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Cannot read properties of undefined (reading 'includes')
**Error Stack:** Error: .NET Acquisition Failed: Cannot read properties of undefined (reading 'includes')
	at y.getErrorOrStringAsEventError (/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.0/dist/extension.js:2:29266)
	at y.<anonymous> (/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.0/dist/extension.js:2:26235)
	at Generator.next (<anonymous>)
	at s (/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.0/dist/extension.js:2:21947)

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.
[DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1721310558919.txt](https://github.com/user-attachments/files/16284429/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1721310558919.txt)

### Reproduction Steps

Launch VS Code and start working with Data Wrangler

### Expected Behavior

Everything working without this error. 

### .NET Install Tool Version

v2.1.1

### Your operating system? Please provide more detail, such as the version and or distro above.

OSX / Darwin / Mac

### VS Code Version

1.91.1

**Comment by nagilson** [comment]
Please see https://github.com/dotnet/vscode-dotnet-runtime/issues/1886, 2.1.1 includes a fix.
