### ISSUE TITLE
[NETE2ESDK] Manually installed SDK is not displayed in the list when running the ‘.NET Install Tool: Uninstall .NET’ command 

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1919]
### Describe the bug.

Manually installed SDK is not displayed in the list when running the ‘.NET Install Tool: Uninstall .NET’ command 

### Reproduction Steps

1.Install the .NET 6.0 from https://dotnet.microsoft.com/en-us/download/dotnet/6.0
2.Open the command palette and run the ‘.NET Install Tool: Uninstall.NET’ command
3.Observe

### Expected Behavior

Manually installed SDK is displayed in the list when running the ‘.NET Install Tool: Uninstall .NET’ command 

### Exceptions & Errors (if any)

Manually installed SDK is not displayed in the list when running the ‘.NET Install Tool: Uninstall .NET’ command 
![image](https://github.com/user-attachments/assets/c5d4a452-c734-46b4-bc75-eb0c5a7e2ea4)

### .NET Install Tool Version

2.1.2

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.92.2

**Comment by nagilson** [comment]
Same as https://github.com/dotnet/vscode-dotnet-runtime/issues/1918

**Comment by v-xiaofchen** [comment]
Closed it as by design.
