### ISSUE TITLE
[NETE2ESDK] [MAC] The .NET runtimes has not been uninstalled after uninstalling the SDK via '.NET Install Tool: Uninstall .NET’ command on MAC.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1921]
### Describe the bug.

The .NET runtimes has not been uninstalled after uninstalling the SDK via '.NET Install Tool: Uninstall .NET’ command on MAC

### Reproduction Steps

1.Run the command ‘.NET Install Tool: Install .NET SDK System-Wide' to install the .NET SDK and enter the newest version.
2.Open the command palette and run the ‘.NET Install Tool: Uninstall.NET’ command
3.Select the SDK to uninstall that you had installed
4.Observe

### Expected Behavior

Uninstall should succeed.

### Exceptions & Errors (if any)

The .NET runtimes has not been uninstalled after uninstalling the SDK via '.NET Install Tool: Uninstall .NET’ command on MAC
![image](https://github.com/user-attachments/assets/6c55c396-3612-45f2-ab62-c9afad2b9c8a)

### .NET Install Tool Version

2.1.2

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.92.2

**Comment by nagilson** [comment]
This is a good point, but this is actually expected. The uninstall was only of the SDK, not the runtime. The .NET Host should remain after the SDK is uninstalled with the current plan we have for the application. Btw, Linux will behave the same way.

If you may, please feel free to update the testing document to reflect this information.
