### ISSUE TITLE
[NETE2ESDK] After downgrading the .NET Installer Tool, the .NET runtime download succeeds with errors.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1926]
### Describe the bug.

After downgrading the .NET Installer Tool, the .NET runtime download succeeds with errors.

### Reproduction Steps

1.Install version '2.1.2' of the .NET Installer Tool extension
2.Downgrade installation to a previous released version for example version '2.0.5', 
3.Run the 'Sample: Acquire .NET Runtime' command for '5.0' and wait for it to finish
4.Observe

### Expected Behavior

It should succeed without any errors.

### Exceptions & Errors (if any)

The runtime download succeeds but an error occurs.
![image](https://github.com/user-attachments/assets/271cf370-11b7-4b88-8282-43a88fe152da)
![image](https://github.com/user-attachments/assets/e077b0ee-ea2e-42ef-b60f-130fec60ef7e)

### .NET Install Tool Version

2.1.2

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.92.2

### Note
Can repro this issue on Windows11-x64 and Windows-arm64, Linux ubuntu-2204

**Comment by nagilson** [comment]
@v-xiaofchen @vsccarl This is only when downgrading the Extension, not upgrading, correct?

While not ideal, I understand why this is happening. And there is not really much we can do about it, we can't patch the older versions.

We could switch to a new data source for newer versions. Basically the data contains some new info that older extensions wont be able to operate on.

**Comment by nagilson** [comment]
I could not get this to happen when upgrading so I will not consider it a release blocker, we have some important fixes to get out.

**Comment by v-xiaofchen** [comment]
Yes,I tried upgrading from version '2.0.5' of the extension to version '2.0.9' on Linux ubuntu-2204，
![image](https://github.com/user-attachments/assets/86a65a46-6678-4d08-be53-27c902f87c3d)
Then, run the 'Sample: Acquire .NET Runtime' command with version '2.0.9' and for '6.0'. It still failed.
![image](https://github.com/user-attachments/assets/3fc1ab44-324c-4744-83ec-9879666f7e00)
But if you upgrade to version 2.1.x, you can succeed.

**Comment by v-xiaofchen** [comment]
This issue does not repro on version 2.1.6.
![image](https://github.com/user-attachments/assets/344b1847-cda7-4646-8d18-34d4dd850e33)

**Comment by v-xiaofchen** [comment]
This issue did not recur when downgrading from version 2.1.6 to version 2.0.5.
![image](https://github.com/user-attachments/assets/3c28e17b-3ae8-47a0-9a07-63892de91331)

**Comment by v-xiaofchen** [comment]
Closed as fixed.
