### ISSUE TITLE
Cannot download dotnet 8.0 in docker container from WSL, local path resolution not working

### ISSUE THREAD

**Issue by will-jac** [dotnet/vscode-dotnet-runtime#1934]
### Describe the bug.

I'm using [docker on WSL](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) to develop dotnet applications inside of docker containers. For various reasons, many of the containers I work with only have dotnet 6.0 installed, and won't be updated to 8.0 anytime soon. I have dotnet 8.0 installed in Windows and in WSL.

Locally in WSL and in Windows, this works fine (I think--I've never actually seen the dotnet install tool do anything, but I can do all my typical dotnet development and use language features in C#).

However, once building and launching a container, the dotnet install tool fails to resolve the path to dotnet and fails to install dotnet 8.0. For some containers, this is fine--I don't get language features and I get a warning mark (annoying), but I can do what I need from the command line. For others, this is a critical error as they don't actually contain an SDK, and assume that I'll be downloading it or using to my global install via the dotnet install tool.

My vscode user settings have the shared dotnet path set: 
`"dotnetAcquisitionExtension.sharedExistingDotnetPath": "/usr/share/dotnet/dotnet"`

WSL output shows valid installations:
```
$ ls /usr/share/dotnet/dotnet
/usr/share/dotnet/dotnet
$ ls /usr/share/dotnet/sdk
6.0.424  7.0.410  8.0.303
$ ls /usr/share/dotnet/shared/Microsoft.NETCore.App/
6.0.32  7.0.20  8.0.7
```

I could just change the Dockerfile here for just me and not commit that file, or manually download the SDK each time, but that's not a great workflow.

Note that my docker containers have web access--I'm using `networkingMode=mirrored` and `dnsTunneling=true` in my `.wslconfig`, and explicitly set DNS in my `/etc/resolv.conf`, but this seems pretty standard. Downgrading to 1.7.2 does **not** fix this issue--the error is the same, just with a different column number for the error location in the minified js.

Error output from a container that includes the 6.0 sdk:
![image](https://github.com/user-attachments/assets/4aff0aa1-bb56-4fac-bced-b837b718b0b4)
Dotnet output from that container:
```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.421
 Commit:    04f27549cd

Runtime Environment:
 OS Name:     debian
 OS Version:  12
 OS Platform: Linux
 RID:         debian.12-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.421/

global.json file:
  Not found

Host:
  Version:      6.0.29
  Architecture: x64
  Commit:       189fbbd88d

.NET SDKs installed:
  6.0.421 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.29 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.29 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

Error output from a container without any sdk:
![image](https://github.com/user-attachments/assets/3e057fb5-aa8a-41a1-9db1-908327412099)

My exhost log folder does not have a `ms-dotnettools.vscode-dotnet-runtime` folder, only `ms-vscode-remote.remote-containers`. If I should be looking somewhere else, happy to try again.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Minimal example simply requires opening any dotnet project in a docker container. From WSL, run:
```
mkdir dotnet-install-failure && cd dotnet-install-failure
dotnet new console
mkdir .devcontainer && touch .devcontainer/devcontainer.json
code .
```
Put the below configuration in the devcontainer.json file:
```
{
    "name": ".NET Install Error Demo",
    "image": "mcr.microsoft.com/dotnet/sdk:6.0",
    "customizations": {
        "vscode": {
            "extensions": [
                "ms-dotnettools.csharp"
            ]
        }
    }
}
```

Then, build and attach the container (ctrl+shift+p > Dev Containers: (re)build container) and look for the failures in the output.
![image](https://github.com/user-attachments/assets/bc4c5bea-477c-4df2-b837-e9a48e1e3b15)
![image](https://github.com/user-attachments/assets/4087d240-8c82-477c-82c3-540e641c5365)
![image](https://github.com/user-attachments/assets/c1916d89-2a82-498c-bcac-5a1acc471e00)

### Expected Behavior

1. My local (on WSL) dotnet installation is successfully found and used even in the devcontainer when the path is specified in my VSCode user settings
2. When a 8.0 sdk is not found in the container and not found locally, it successfully downloads
3. When a dotnet 6.0 sdk is found but an 8.0 sdk is not found and fails to downloaded, nothing happens and the tool does not report an error (since 6.0 is still supported until EOL in November)
4. Only when no supported sdk is found or able to download is an error reported

### .NET Install Tool Version

v2.1.5

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.92.1

**Comment by nagilson** [comment]
Per @lifengl, you must install the 8.0 runtime into that location. Here's why.

The location you point to has only the 6.0 runtime and SDK. Your project, of course, is only 6.0. Thats good. But DevKit runs on 8.0. So it needs an 8.0 runtime. That 8.0 version is not for your project. It is for DevKit to run.

**Comment by nagilson** [comment]
I think we need to change this PATH setting
🤦 It is super confusing. DevKit tried to find .NET. It found that it didnt have the .NET it needed to run. So it asks us to get one. But we have a PATH set. But nobody understands that the PATH is what DevKit is using to run, not what their project is using to run.

The setting is blindly returning the PATH without checking whether it meets the requirements of any given request. So it returns that. So DevKit is like... um, huh, it asked for an 8,0 runtime and thought it got it, but we gave it a 6,0 one and then it doesn't work.

IMO we should make the PATH setting only apply if it meets the condition of the request...

**Comment by will-jac** [comment]
Thanks for the clarification @nagilson, my expectation was that the PATH setting would be on the host machine and not the docker image. Sounds like that's not the case.

In this case, it sounds like the problem is with the runtime not successfully downloading. I've tried downgrading to the version before the networking changes (1.7), without success. Anything I can do to assist with debugging that issue, or to figure out on my side why it isn't able to connect and download?

I assume there's no hope that devkit would continue to support 6.0 until EOL, or ability to have the install tool resolve the PATH variable using WSL instead of the docker image?

Otherwise, it sounds like my workaround is to include dotnet 8.0 in the Dockerfile so that it's installed, and avoid committing that change so as not to mess with our CI pipelines 😅

**Comment by nagilson** [comment]
It will never even try to download the runtime if the existingPath option is set. Is there a reason you want to keep that setting active with the above information? 

I am pretty sure if you unset the setting, it will work. Your docker image will need a 6.0 SDK installed, but that should be it.
