### ISSUE TITLE
Error Message Gotten

### ISSUE THREAD

**Issue by nico-liao0918** [dotnet/vscode-dotnet-runtime#1940]
### Describe the bug.

I got this error message when I tried to use the .Net Install tool. to download and install .Net 3.5 sdk but it failed due to.... See below for the error. Even If I have great internet connection. I get this message.

Error : (DotnetCommandFailed)
Failed to download .NET 3.5-global~x64:
Request to https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/3.5/releases.json Failed: Request failed with status code 404. Aborting.

Please ensure that you are online.

If you're on a proxy and disable registry access, you must set the proxy in our extension settings. See https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

Error : (DotnetCommandFailed)
Failed to download .NET 3.5-global~x64:
Request to https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/3.5/releases.json Failed: Request failed with status code 404. Aborting.

Please ensure that you are online.

If you're on a proxy and disable registry access, you must set the proxy in our extension settings. See https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md.

### Reproduction Steps

I used the Net Install tool and wanted to install the .Net 3.5 sdk. 

### Expected Behavior

Should have downloaded .net 3.5 sdk

### Exceptions & Errors (if any)

Error : (DotnetCommandFailed)
Failed to download .NET 3.5-global~x64:
Request to https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/3.5/releases.json Failed: Request failed with status code 404. Aborting.

Please ensure that you are online.

If you're on a proxy and disable registry access, you must set the proxy in our extension settings. See https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md.

### .NET Install Tool Version

2.1.5

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

Version: 1.92.2 (user setup) Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9 Date: 2024-08-14T17:29:30.058Z Electron: 30.1.2 ElectronBuildId: 9870757 Chromium: 124.0.6367.243 Node.js: 20.14.0 V8: 12.4.254.20-electron.0 OS: Windows_NT x64 10.0.22635

**Comment by nagilson** [comment]
I dont think there is such a version of the .NET SDK. There is the .NET framework version 3.5. But this tooling does not support acquiring that. Sorry, but youll need to download it on the website.
