### ISSUE TITLE
Educ bundle botnet

### ISSUE THREAD

**Issue by Seye226** [dotnet/vscode-dotnet-runtime#1951]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /Users/souphineseye/Library/Application Support/Code/logs/20240913T235602/window44/exthost/ms-dotnettools.vscode-dotnet-sdk/DotNetAcquisition-ms-dotnettools.vscode-dotnet-sdk-1726274298789.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by nagilson** [comment]
May you please attach the log? Let us know your issue.
