### ISSUE TITLE
[NETE2ESDK] [Linux] It will still show the download even if the distro Linux does not support the .NET

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1956]
### Describe the bug.

It will still show the download even if the distro Linux does not support the.NET

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

1.Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
2.Use the version ‘5.0’ and hit enter.
3.Oberve

### Expected Behavior

This will fail with an error on Linux that it is not supported.

### Exceptions & Errors (if any)

It will still show the download even if the distro Linux does not support the .NET
![image](https://github.com/user-attachments/assets/bc6f3403-5485-4dcc-9d8d-1b7ff5245b29)

### .NET Install Tool Version

dotnet-install-tool-2.1.6

### Your operating system? Please provide more detail, such as the version and or distro above.

Linux

### VS Code Version

1.93.1

**Comment by nagilson** [comment]
Hm, that should not happen. It could be benign but it could also be really bad. I need to look into this. The log is weird too. Not sure if its a blocker or not.

**Comment by nagilson** [comment]
It might be an await that eslint thought we could get rid of but we can't

**Comment by nagilson** [comment]
Hm yep this is bad and it is due to a missing await that eslint told me to get rid of -_-

**Comment by v-xiaofchen** [comment]
With the new 2.1.6 build, this issue does not repro.
![image](https://github.com/user-attachments/assets/151f8f8f-a5fe-4c07-8b61-90ca593d71b3)
