### ISSUE TITLE
[NETE2ESDK] .NET runtime acquisition via sample cannot be found by "Find Path" command

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1961]
### Describe the bug.

.NET runtime acquisition via sample cannot be found by "Find Path" command 

### Reproduction Steps

1.Run the 'Sample: Acquire .NET runtime' command. You should be asked to enter a Major. Minor version, please enter '3.1'.
2. After 3.1 runtime is installed succeed, run the 'Sample: Find the .NET on the PATH' command and enter '3.1'
3. observe the output

### Expected Behavior

It should return the path to Simple .NET runtime acquisition.

### Exceptions & Errors (if any)

Simple .NET runtime acquisition cannot be found by "Find Path" command
![image](https://github.com/user-attachments/assets/e42e8600-7049-4c81-a058-add36617ba9a)

### .NET Install Tool Version

2.1.7

### Your operating system? Please provide more detail, such as the version and or distro above.

Linux/MAC/Windows

### VS Code Version

1.93.1

**Comment by nagilson** [comment]
This is a good thing to raise, but it is an expected behavior. The runtime installation is meant to not edit the system wide machine state, which the path API is meant to search only.
