### ISSUE TITLE
[NETE2ESDK] Unable to find .NET X86 installation path by "Find Path" command.

### ISSUE THREAD

**Issue by yinjiehe01** [dotnet/vscode-dotnet-runtime#1962]
### Describe the bug.

Unable to find .NET X86 (install from https://dotnet.microsoft.com/en-us/download/dotnet) installation path by "Find Path" command on Windows X64.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

1.Download X86 SDK or runtime from https://dotnet.microsoft.com/en-us/download/dotnet and install.
2.Add X86 SDK or runtime installation path to the environment variables.
3.Open VS Code and Run the 'Sample: Find the.NET on the PATH' command.
4.Change the .NET runtime architecture to X86 and then press ENTER to find X86 SDK or runtime installation path.

### Expected Behavior

The .NET X86 installation path can be found through the "Find Path" command on Windows X64.

### Exceptions & Errors (if any)

The .NET X86 installation path cannot be found through the "Find Path" command on Windows X64.

### .NET Install Tool Version

2.1.7

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.93.1

**Comment by nagilson** [comment]
I tried to repro this. The only way I can repro this is if vscode is not restarted after editing the PATH and installing .NET x86, though that was on an x64 device. May you confirm that you restarted vscode here?

**Comment by v-xiaofchen** [comment]
Thanks for the reminder, the issue does not repro after restarting VS code.

**Comment by nagilson** [comment]
The PATH is propagated through any child process we spawn so I dont know how we can fix this. Maybe by communicating with an upper level process but I dont think that is really easy to do and I dont know off the top of my head how we would do that. The SDK install thru vscode shouldn't hit this issue, so I think ill close it for now...
