### ISSUE TITLE
[NETE2ESDK] It should give message if an invalid version was requested by "Find Path" command

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1963]
### Describe the bug.

It should give message if an invalid version was requested by "Find Path" command

### Reproduction Steps

1. Run 'Sample: Find the .NET on the PATH' command.
2. Use the version it provided, which is 8.0. Hit enter
3. After 8.0. is enter succeed, then please enter an invalid condition version (for example, 'greater').
4. Observer

### Expected Behavior

It should give message if an invalid version was requested by "Find Path" command

### Exceptions & Errors (if any)

The request by "Find Path" command is inaccurate
![image](https://github.com/user-attachments/assets/51f23f58-f579-4ccd-97ba-9a924975674f)

### .NET Install Tool Version

2.1.7

### Your operating system? Please provide more detail, such as the version and or distro above.

Other

### VS Code Version

1.93.1

**Comment by nagilson** [comment]
This UI dialog will never be available to users, so please don't consider this a bug for this api/menu item in particular.
