### ISSUE TITLE
[NETE2ESDK] Unable to find .NET zip package installation path containing Chinese characters by "Find Path" command. 

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1967]
### Describe the bug.

Unable to find .NET zip package installation path containing Chinese characters by "Find Path" command. 

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

1.Download X64 SDK or runtime zip package from  https://dotnet.microsoft.com/en-us/download/dotnet on Windows X64.
2.Use zip package and unzip it in a custom location containing Chinese characters (for example, 'D:\Test自定义路径 ')
3.Add X64 SDK or zip installation path to the environment variables.
4.Open VS Code and Run the 'Sample: Find the.NET on the PATH' command.

### Expected Behavior

The .NET zip installation path containing Chinese characters can be found through the "Find Path" command.

### Exceptions & Errors (if any)

Unable to find .NET zip package installation path containing Chinese characters by "Find Path" command. 
![image](https://github.com/user-attachments/assets/e33964ee-b2b6-4f9c-8cc2-5fc13e0f1a46)

### .NET Install Tool Version

dotnet-install-tool-2.1.7

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.93.1

**Comment by NicoleWang001** [comment]
Add screen with a custom location containing Chinese characters (for example, 'D:\a你好 ')
![image](https://github.com/user-attachments/assets/9b9f3cba-8949-4f78-8cd1-1570019f74a3)

**Comment by nagilson** [comment]
This is a very good find, thank you
