### ISSUE TITLE
Guys SEPTEMBER has just 30 days. 

### ISSUE THREAD

**Issue by boldurean** [dotnet/vscode-dotnet-runtime#1970]
### Describe the bug.

.NET Install Tool Changelog 2.1.7 release w
<img width="763" alt="Screenshot 2024-10-01 at 09 50 05" src="https://github.com/user-attachments/assets/e18dfc4c-1c27-49e5-b400-9090b45928ec">
as done on 31 September and month has just 30 days :|

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Open .NET Install Tool changelog. Look up the release date

### Expected Behavior

idk just change the date to 1st OCT maybe? 

### .NET Install Tool Version

2.1.7

### Your operating system? Please provide more detail, such as the version and or distro above.

OSX / Darwin / Mac

### VS Code Version

1.93.1 (Universal)

**Comment by nagilson** [comment]
Lol yes, this was a typo on my part. It released on the 30th of September.
Ill fix this in the changelog when we do the next release (it's already fixed pending https://github.com/dotnet/vscode-dotnet-runtime/pull/1971/files)

**Comment by nagilson** [comment]
Thank you for reporting btw. This was very amusing to read.
