### ISSUE TITLE
Downloading through the install tool plugin is extremely slower than official site

### ISSUE THREAD

**Issue by NullDict** [dotnet/vscode-dotnet-runtime#1980]
### Describe the bug.

It seems that the install tool plugin is downloading the dotnet SDK at a frustratingly slow speed, and after even half an hour, the installation is still not complete.

However, using the URL provided on the dotnet official website: https://download.visualstudio.microsoft.com/download/pr/6224f00f-08da-4e7f-85b1-00d42c2bb3d3/b775de636b91e023574a0bbc291f705a/dotnet-sdk-8.0.403-win-x64.exe allows for a significantly faster download speed.

Unfortunately, through the local network URL connection detection tool, I found that the install tool plugin does not seem to be downloading the dotnet SDK via the aforementioned URL.

I hope this issue can be optimized. Thank you.

### Please attach log file(s) here if you have any.

AvaloniaTeam.vscode-avalonia requested to download the .NET Runtime.
Downloading .NET version(s) 8.0.10~x64 .............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

### Reproduction Steps

It can only be reproduced in areas where the download speed from the plugin's internal address is extremely slow.

### Expected Behavior

The download can be completed very quickly using the URL provided on the dotnet official website, while downloading and installing through the plugin’s address takes over half an hour.

### .NET Install Tool Version

v2.2.0

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.94.2（system setup）

**Comment by nagilson** [comment]
Do you mind sharing which region (country) you are located in? Our requests get routed through Axios. 
Secondarily, our log might provide some more information. Maybe there is a failure somewhere else. We hit the same url endpoint so I wouldnt expect this to be the case.

# logs

Our log files are located alongside VS Code logs. If you want to find them manually, navigate here: Linux: ~/.config/Code/logs Mac: ~/Library/Application Support/Code/logs/ Windows: c:\Users\USER\AppData\Roaming\Code\logs\

Then find the folder created at the time you experienced the bug in the logs folder. From there, go to window1 -> exthost -> ms-dotnettools.vscode-dotnet-runtime. The log file should be located in this folder.

Note: The window folder may change depending on how many VS Code windows you have open; if our extension is running in the 2nd window, it'd be in a folder called window2.

**Comment by NullDict** [comment]
I deleted the dotnet SDK from \Users\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime.dotnet and reinstalled it through VSCode. No more issues have arisen; it seems that there was a sporadic fluctuation from my ISP, and there shouldn’t be any problems. Thank you.
