### ISSUE TITLE
[NETE2ESDK] 'The .NET runtime architecture' doesn't work when using the "Find Path" command.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1984]
### Describe the bug.

'The .NET runtime architecture' doesn't work when using the "Find Path" command.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

1.Download X64 SDK from https://dotnet.microsoft.com/en-us/download/dotnet and install.
2.Open VS Code and Run the 'Sample: Find the.NET on the PATH' command.
3.Changing the .NET SDK architecture to X86 or even an invalid architecture and then press ENTER 
4.observer

### Expected Behavior

It should not find anything

### Exceptions & Errors (if any)

Always returns the .NET X64 installation path regardless of the architecture entered when using the "Find Path" command.
![Image](https://github.com/user-attachments/assets/df805d46-efdc-4a3b-b93e-41456047558b)

### Note
This issue does not repro on X64 runtime
![Image](https://github.com/user-attachments/assets/678e8d78-9d84-409e-a472-7013db466f69)

### .NET Install Tool Version

2.2.0

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.94.2

**Comment by NicoleWang001** [comment]
On Win Arm64, it always get .NET Arm64 installation path whatever the architecture is X64, X86 or Arm64
![Image](https://github.com/user-attachments/assets/f21f9efd-c27e-49ef-9b8f-2caa31f3c693)

**Comment by v-xiaofchen** [comment]
Fixed and closed it.
