### ISSUE TITLE
[NETE2ESDK] Error : (DotnetFeatureBandDoesNotExistError) occurs when the query condition is sdk in the Find Path feature.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#2015]
### Describe the bug.

Error : (DotnetFeatureBandDoesNotExistError) occurs when the query condition is **sdk** in the Find Path feature.

### Reproduction Steps

1.Run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)‘.
2.Use the version it provided, which is 7.0.103. Hit enter.
3.Run the 'Sample: Find the.NET on the PATH' command.
4.Enter the value of query condition, eg. 'sdk'
5.observer

### Expected Behavior

The .NET installation path should be found correctly without errors

### Exceptions & Errors (if any)

Error : (DotnetFeatureBandDoesNotExistError) occurs when the query condition is sdk in the Find Path feature
![Image](https://github.com/user-attachments/assets/d99d5dd2-d2d7-41c5-8682-1f3ad412e579)

### Note
1.When the query condition is **an sdk**, no error will be reported.
2.When the query conditon is **runtime** or **aspnetcore runtime**, no error will be reported.
3.When the query conditon is **an runtime** or **an aspnetcore runtime**, no error will be reported.

### .NET Install Tool Version

2.2.3

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.95.2

**Comment by nagilson** [comment]
Well, I am impressed that you tested this and thought of it and I am glad you did.
This bug is not so good. I will fix it.

**Comment by nagilson** [comment]
Oh actually, @v-xiaofchen, did it return the path and not undefined? It looks like this error gets suppressed, but it still bubbles up as an error to the user.

**Comment by nagilson** [comment]
It's in a try catch block though so why would it ???

**Comment by v-xiaofchen** [comment]
@nagilson Even if there is an error, it can return the path
![Image](https://github.com/user-attachments/assets/9ed45e93-3868-4ef2-99a4-4db8bee78fdd)

**Comment by nagilson** [comment]
OK awesome, thanks, I should probably still fix this before the release though because its confusing/annoying to people even if it actually works

**Comment by v-xiaofchen** [comment]
This issue does not repro on the new vscode-dotnet-runtime-2.2.3.
![Image](https://github.com/user-attachments/assets/3716ffd5-fb04-4823-9f42-31ea58b4b41b)
