### ISSUE TITLE
version to c# is incompatible

### ISSUE THREAD

**Issue by Thecrin** [dotnet/vscode-dotnet-runtime#2020]
VSC pidio una actualizacion del codigo c# de unity a la ultima verison y me dio error

**Comment by nagilson** [comment]
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.
