### ISSUE TITLE
C# Dev kit won't start

### ISSUE THREAD

**Issue by samuel-utbult-oborgen** [dotnet/vscode-dotnet-runtime#2023]
### Describe the bug.

VS Code updated itself and now C# Dev kit won't start.

### Please attach log file(s) here if you have any.

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### Reproduction Steps

1. Install VS Code on macOS 15.0.1.
2. Start VS Code.
3. Install C# Dev kit
4. Get the error.

### Expected Behavior

C# Dev kit should work like it did yesterday.

### .NET Install Tool Version

v2.2.2

### Your operating system? Please provide more detail, such as the version and or distro above.

OSX / Darwin / Mac

### VS Code Version

Version: 1.95.2 (Universal) Commit: e8653663e8840adaf45af01eab5c627a5af81807 Date: 2024-11-07T11:07:22.054Z (5 days ago) Electron: 32.2.1 ElectronBuildId: 10427718 Chromium: 128.0.6613.186 Node.js: 20.18.0 V8: 12.8.374.38-electron.0 OS: Darwin arm64 24.0.0

**Comment by samuel-utbult-oborgen** [comment]
It worked again when I installed .NET 9.

**Comment by nagilson** [comment]
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.
