### ISSUE TITLE
Error in running .NET Install Tool in Visual Studio Code

### ISSUE THREAD

**Issue by tinagalido** [dotnet/vscode-dotnet-runtime#2024]
### Describe the bug.

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Click a C# script in Unity. The error appears

### Expected Behavior

No error is generated

### .NET Install Tool Version

0.2.0

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

**Comment by dminhhoang26** [comment]
me toooooo

**Comment by mccaffers** [comment]
I cam across this today too. I updated the existingDotnetPath in VSCode settings.

I posted this on another comment - so cross posting:

Setting dotnetAcquisitionExtension.existingDotnetPath helped fix this issue for me:

![Image](https://github.com/user-attachments/assets/83f9021f-52bc-4e4f-a33a-4dfa9aa3c551)

```
   "dotnetAcquisitionExtension.existingDotnetPath": [
        {"extensionId": "msazurermtools.azurerm-vscode-tools", "path": "/usr/local/share/dotnet/dotnet"}
    ]
```

**Comment by peyronth** [comment]
As a temporary fix you can set C# extension version to 2.50.27 (Click on the down arrow next to uninstall button from extension details page).

https://github.com/user-attachments/assets/8fbe8cc8-fd61-4a87-a3cf-eae7239f4b33

If still not working you can also set dotnetSDKAcquisitionExtension.installTimeoutValue to a higher value.

**Comment by rodrigomaia** [comment]
Same here. On linux it's until worst. Doesn't works with downgrade.

**Comment by nagilson** [comment]
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.
