### ISSUE TITLE
Error in running .NET Install Tool in Visual Studio Code

### ISSUE THREAD

**Issue by The-algar** [dotnet/vscode-dotnet-runtime#2025]
### Describe the bug.

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

install latest version of VS code 

### Expected Behavior

install latest version of VS code 

### Exceptions & Errors (if any)

Installation of .NET 8.0.10.

### .NET Install Tool Version

v2.2.2

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.95.2

**Comment by The-algar** [comment]
Version: 1.95.2 (system setup)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by nagilson** [comment]
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.
