### ISSUE TITLE
UpdateErr

### ISSUE THREAD

**Issue by jitaqiu** [dotnet/vscode-dotnet-runtime#2028]
### Describe the bug.

如果搞不定服务器就请不要瞎基霸升级。每天弄得VSCode自动补全都他妈的不能用。不知道你们在干什么。

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

垃圾

### Expected Behavior

垃圾

### Exceptions & Errors (if any)

垃圾

### .NET Install Tool Version

垃圾

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

**Comment by nagilson** [comment]
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.
