### ISSUE TITLE
The requested and or resolved version is invalid - dotnet version 8.0.10

### ISSUE THREAD

**Issue by muneermsheikh** [dotnet/vscode-dotnet-runtime#2030]
### Describe the bug.

VS Code fails to start, and gives the error 

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### Reproduction Steps

starting VS Code gives the error

### Expected Behavior

No error has been encountered earlier, till this afternoon

### .NET Install Tool Version

8.0.32

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.95.2

**Comment by b93rn** [comment]
I had the same issue, and I resolved it by switching to a different .NET SDK version.

To install another SDK version in VSCode, open the Command Palette by pressing CTRL + Shift + P (or CMD + Shift + P on a Mac), and then run:

> .NET: Install Tool > Install the .NET SDK System-Wide


![Image](https://github.com/user-attachments/assets/9c1488bd-80a5-4c28-9929-6ccac98c6b50)

I selected version 9.0.100, installed it, and the issue was resolved.

**Comment by Norni-Far** [comment]
I have the same problem and the method above did not help .... .

> I had the same issue, and I resolved it by switching to a different .NET SDK version.
> 
> To install another SDK version in VSCode, open the Command Palette by pressing CTRL + Shift + P (or CMD + Shift + P on a Mac), and then run:
> 
> > .NET: Install Tool > Install the .NET SDK System-Wide
> 
> ![Image](https://github.com/user-attachments/assets/9c1488bd-80a5-4c28-9929-6ccac98c6b50)
> 
> I selected version 9.0.100, installed it, and the issue was resolved.

That's what the logs are showing: 
Downloading .NET version(s) 9.0.100-global~x64 ...user: Trying to install .NET 9.0.100-global~x64 but it already exists. No downloads or changes were made.

![Image](https://github.com/user-attachments/assets/87503892-3790-4f16-ba4e-56ad61380de1)

**Comment by b93rn** [comment]
> I have the same problem and the method above did not help .... .
> 
> > I had the same issue, and I resolved it by switching to a different .NET SDK version.
> > To install another SDK version in VSCode, open the Command Palette by pressing CTRL + Shift + P (or CMD + Shift + P on a Mac), and then run:
> > > .NET: Install Tool > Install the .NET SDK System-Wide
> > 
> > 
> > ![Image](https://github.com/user-attachments/assets/9c1488bd-80a5-4c28-9929-6ccac98c6b50)
> > I selected version 9.0.100, installed it, and the issue was resolved.
> 
> That's what the logs are showing: Downloading .NET version(s) 9.0.100-global~x64 ...user: Trying to install .NET 9.0.100-global~x64 but it already exists. No downloads or changes were made.
> 
> ![Image](https://github.com/user-attachments/assets/87503892-3790-4f16-ba4e-56ad61380de1)

Apparently there are a lot more issues created for this issue. This temp fix works for a lot of people: https://github.com/dotnet/vscode-dotnet-runtime/issues/2031#issuecomment-2473877014

**Comment by Norni-Far** [comment]
Yes! It works! 

I did:
As a temporary fix you can set C# extension version to 2.50.27

**Comment by nagilson** [comment]
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.
