### ISSUE TITLE
Cancelled Installation of .NET 8.0.10.

### ISSUE THREAD

**Issue by dmssystems** [dotnet/vscode-dotnet-runtime#2031]
Hi,

I can't run any of my MVC .net projects due to the above error.

Would you please support.

Thanks

**Comment by inoa-mgsimao** [comment]
.NET Install Tool output on VSCode:

Lots of

```
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
```

**Comment by b93rn** [comment]
Duplicate #2030

**Comment by nagilson** [comment]
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.
