### ISSUE TITLE
Error installing C# Dev Kit extension in Visual Studio Code

### ISSUE THREAD

**Issue by lwhi-dev** [dotnet/vscode-dotnet-runtime#2034]
### Describe the bug.

Installing the C# Dev Kit extension in VSCode and I get the following error.

![Image](https://github.com/user-attachments/assets/d19c9242-3fb7-49bb-84b4-410bbf046866)

### Please attach log file(s) here if you have any.

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### Reproduction Steps

Install C# Dev Kit extension from the marketplace in VSCode.

### Expected Behavior

Installation without error installing .NET

### .NET Install Tool Version

1.13.9

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.95.2

**Comment by nagilson** [comment]
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.
