### ISSUE TITLE
An error occurred while installing .NET (8.0.10). The requested and or resolved version is invalid.

### ISSUE THREAD

**Issue by kpilic123** [dotnet/vscode-dotnet-runtime#2036]
### Describe the bug.

.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

.

### Expected Behavior

.

### .NET Install Tool Version

v2.0.0

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

7.0

**Comment by nagilson** [comment]
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.
