### ISSUE TITLE
.net 8.0.10 version is invalid error

### ISSUE THREAD

**Issue by KawishG** [dotnet/vscode-dotnet-runtime#2037]
### Describe the bug.

when starting up vscode i get the error the installation is cancelled or the version couldnt be checked.

### Please attach log file(s) here if you have any.

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### Reproduction Steps

start up vscode, try to download C# and C# dev kit.

### Expected Behavior

it should just work and download but it isnt

### .NET Install Tool Version

8.0.10

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

**Comment by nagilson** [comment]
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.
