### ISSUE TITLE
The requested and or resolved version is invalid.

### ISSUE THREAD

**Issue by stanleyLin1527** [dotnet/vscode-dotnet-runtime#2039]
### Describe the bug.

I just opened the unity project and .NET install tool tells me that it can't install .NET

### Please attach log file(s) here if you have any.

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### Reproduction Steps

nothing special, I update to the newest version and get this bug

### Expected Behavior

idk

### .NET Install Tool Version

v2.2.2

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.95.2

**Comment by BNeutral** [comment]
Same issue here. Everything was working fine 12 hours ago (and for months), today I opened the same project and get hit by this. Downgrading from version 2.2.2 to 2.2.1 did not seems to solves the issue. Neither did adding "dotnetAcquisitionExtension.existingDotnetPath" to the settings file.

**Comment by nagilson** [comment]
pls see https://github.com/dotnet/vscode-dotnet-runtime/issues/2021
