### ISSUE TITLE
Cancelled Installation of .NET 8.0.10. The requested and or resolved version is invalid.

### ISSUE THREAD

**Issue by RID990908** [dotnet/vscode-dotnet-runtime#2040]
### Describe the bug.

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### Expected Behavior

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### Exceptions & Errors (if any)

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### .NET Install Tool Version

8

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

**Comment by BNeutral** [comment]
An explanation and workaround is provided on this other issue https://github.com/dotnet/vscode-dotnet-runtime/issues/2021
