### ISSUE TITLE
.NET Installation Tool on Cursor and Dotnet Version 7.0.8

### ISSUE THREAD

**Issue by alierengunaltili** [dotnet/vscode-dotnet-runtime#2041]
### Describe the bug.

An error occurred while installing .NET: The requested and or resolved version is invalid.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

An error occurred while installing .NET: The requested and or resolved version is invalid.

### Expected Behavior

Cannot go to the references of functions and variables.

### .NET Install Tool Version

v2.2.2

### Your operating system? Please provide more detail, such as the version and or distro above.

OSX / Darwin / Mac

### VS Code Version

1.95.2

**Comment by nagilson** [comment]
Please see https://github.com/dotnet/vscode-dotnet-runtime/issues/2021
