### ISSUE TITLE
Error installing Net v8

### ISSUE THREAD

**Issue by Mats-Zoxxi** [dotnet/vscode-dotnet-runtime#2047]
### Describe the bug.

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### Expected Behavior

Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.

### .NET Install Tool Version

v8

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

**Comment by nagilson** [comment]
please update the C# extension to fix this bug
