### ISSUE TITLE
wellcome-to docker

### ISSUE THREAD

**Issue by drhassan20990** [dotnet/vscode-dotnet-runtime#2055]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\DRABDULQWI HASSAN\AppData\Roaming\Code\logs\20241125T191334\window4\exthost\ms-dotnettools.vscode-dotnet-sdk\DotNetAcquisition-ms-dotnettools.vscode-dotnet-sdk-1732552051183.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsof

**Repro steps:**

1.

**Extension Version:** 1.0.0
t.com/en-US/privacystatement

**Comment by nagilson** [comment]
Not sure what youre trying to say here. Please file a new issue.
