### ISSUE TITLE
Support virtual workspaces

### ISSUE THREAD

**Issue by lszomoru** [dotnet/vscode-dotnet-runtime#227]
👋 Hi there, Martin here, from the VS Code team.

Recently we've announced the [Remote Repository feature](https://code.visualstudio.com/updates/v1_56#_remote-repositories-remotehub) that lets you browse and edit files and folders directly on GitHub.

`Open Remote Repository...` opens VSCode on a folder or workspace located on a virtual file system. We call this a **virtual workspace**. We observed that not all extension support this well, either because they can not, or they haven't thought about it.

It would be fantastic if you could test whether your extension can handle virtual workspaces:

Check out the [Virtual Workspaces Extension Author Guide](https://github.com/microsoft/vscode/wiki/Virtual-Workspaces) on how to do that.

When done, set the new `virtualWorkspaces` capability in your 'package.json'.

```
{
  "capabilities": {
    "virtualWorkspaces": true | false
  }
}
```

- Use `"virtualWorkspaces": true` if your extension is prepared for virtual workspaces
- Use `"virtualWorkspaces": false` if your extension should be disabled when a virtual workspace is opened

For questions and comments please use the [Virtual Workspaces Tracking Issue](https://github.com/microsoft/vscode/issues/123115).

Thanks for the support and the great work! ❤️

**Comment by sfoslund** [comment]
I imagine neither of our extensions will work at all in virtual workspaces, so I'll go ahead and set `"virtualWorkspaces": false` unless you have any concerns @NTaylorMullen

**Comment by NTaylorMullen** [comment]
> I imagine neither of our extensions will work at all in virtual workspaces, so I'll go ahead and set `"virtualWorkspaces": false` unless you have any concerns @NTaylorMullen

Hmm, why wouldn't the sdk extension work in virtual workspaces? It doesn't interact with the contents of the workspace at all so I wouldn't imagine there'd be any issue. That being said, consumers of this extension may not support it but that's their own problem 😄

**Comment by sfoslund** [comment]
Are we able to depend on the file system being accessible to us? [This section](https://github.com/microsoft/vscode/wiki/Virtual-Workspaces#review-that-the-code-is-ready-for-virtual-resources) seems to imply that there may be some differences when dealing with files

**Comment by NTaylorMullen** [comment]
I believe we are, just not any of the workspaces files on the file system. Maybe i'm wrong. @lszomoru ?

**Comment by aeschli** [comment]
The local file system is still available. You can get your SDK/library files from there

**Comment by sfoslund** [comment]
Sounds good, I'll do some smoke testing when I get a chance then.
