### ISSUE TITLE
.NET Acquisition Failed Error

### ISSUE THREAD

**Issue by chrisdias** [dotnet/vscode-dotnet-runtime#242]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /home/chrisdias/.vscode-server/data/logs/20210610T122804/exthost2/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1623353575053.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Repro steps:**

1. Editing a JavaScript file with the latest build of VS Code Stable, got this popup.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.1.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.16" -Version 3.1.16 -Runtime dotnet
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.1.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.1.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.16" -Version 3.1.16 -Runtime dotnet
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.1.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.1.0/dist/extension.js:2:13753

**Comment by sfoslund** [comment]
Edit: oops, I mean a dup of https://github.com/dotnet/vscode-dotnet-runtime/issues/159
