### ISSUE TITLE
ILSpy extension won't work without a .NET 5.0 runtime.

### ISSUE THREAD

**Issue by thartdyke** [dotnet/vscode-dotnet-runtime#246]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\toby\AppData\Roaming\Code\logs\20210623T091419\exthost3\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1624438899512.txt. Note that this file may contain personal data.

**Repro steps:**

1. VSCode was open.

2. Press Ctrl-Shift-N to open a new editor

3. The error message pops up. Clicking "More information" shows a message "ILSpy extension won't work without a .NET 5.0 runtime."

 The log file at the indicated locaion was empty (i.e., zero bytes).

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: EPERM: operation not permitted, unlink 'c:\Users\anonymous\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\5.0.7\dotnet.exe'
**Error Stack:** Error: .NET Acquisition Failed: EPERM: operation not permitted, unlink 'c:\Users\anonymous\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\5.0.7\dotnet.exe'
    at c:\Users\anonymous\.vscode\extensions\vscode-dotnet-runtime-library\dist\Acquisition\DotnetCoreAcquisitionWorker.js:85:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by sfoslund** [comment]
Based on the error message it appears that the existing .NET runtime installation was locked, which caused the error. Is this error recurrent?

**Comment by thartdyke** [comment]
On restarting VSCode, the original error no longer occurs. What I do see is a quick flash of error in the status bar (too quick to read) then a message "Downloading .NET" which lasts for a few seconds, then everything is OK. This happens in the first editor window and any new editor window I open.

**Comment by sfoslund** [comment]
That sounds like it's expected, the extension will check for .NET updates every time it's activated. Since this was a transient issue I'm going to close it.
