### ISSUE TITLE
dotnet.acquire command seems to never return

### ISSUE THREAD

**Issue by Rpinski** [dotnet/vscode-dotnet-runtime#254]
Hello,

some users of our [ilspy-vscode](https://github.com/icsharpcode/ilspy-vscode) extension (so far all of them use Linux) experience weird issues since our latest release, where we started using _vscode-dotnet-runtime_ to acquire .NET 5.0 runtime. According to log output posted in https://github.com/icsharpcode/ilspy-vscode/issues/76 it looks like that our call to _dotnet.acquire_ command never comes back:

https://github.com/icsharpcode/ilspy-vscode/blob/c35acfbfb2b66440426e952084b380a70b1495f4/vscode-extension/src/dotnet-acquire/acquire.ts#L23

The log ("Check finished ...") just after this call is not seen anymore and I see no other reason, why it should be missing. Also no errors seem to be thrown. The output in ".NET runtime" tells that downloading was fine:

```
Downloading the .NET Runtime.
 Error!
ENOENT: no such file or directory, scandir '/home/arong/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/5.0.7/sdk'

Downloading .NET version(s) 5.0.7 ... Done!
.NET 5.0.7 executable path: /home/arong/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/5.0.7/dotnet
```

Unfortunately I don't have access to a Linux machine right now to reproduce it or capture any data. Everything worked well on Windows and MacOS systems so far.

Could it be possible that something goes wrong especially on Linux? Or are we using the command wrongly?

Thanks in advance,
Andreas

**Comment by sfoslund** [comment]
Hi @Rpinski, thanks for filing an issue. Would you or any of your users be able to provide logs for this incident? You can get the file path to the logs by running the `Report issues` command after the issue repros: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#other-issues.

**Comment by Rpinski** [comment]
Hi @sfoslund, finally I was able to debug these calls directly on Ubuntu WSL and actually the hanging command was `dotnet.ensureDotnetDependencies`, which is called by us afterwards. The problem here is that this command tries to start the given executable and waits until it exits to detect any crashes etc. But in our case the executable is a language server and keeps running. Then `ensureDotnetDependencies` waits forever. Happening during extension activation this seems to block other extensions as well, so several strange things occur afterwards at different places.

So we can say it has been wrong API usage on our side, but maybe it needs a note in command's documentation.

**Comment by sfoslund** [comment]
Ah yes, ensureDependencies should be run with a simple command line dotnet --info, you can check out an example usage here: https://github.com/dotnet/aspnetcore-tooling/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/src/acquireDotnetInstall.ts#L23
