### ISSUE TITLE
.Net installation issue

### ISSUE THREAD

**Issue by Alonoparag** [dotnet/vscode-dotnet-runtime#256]
The issue text was copied to the clipboard.  Please paste it into this window.

**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: cp: cannot create regular file '/home/anonymous/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.16/dotnet': Text file busy

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: cp: cannot create regular file '/home/anonymous/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.16/dotnet': Text file busy

    at /home/anonymous/.vscode/extensions/vscode-dotnet-runtime-library/dist/Acquisition/DotnetCoreAcquisitionWorker.js:85:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Please attach the log file located at /home/alonp/.config/Code/logs/20210706T121610/exthost1/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1625566584724.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by sfoslund** [comment]
@Alonoparag thanks for filing an issue! Can you please provide the log file as well? The file path is included in this issue's body.

**Comment by brandonh-msft** [comment]
On my machine w/ this issue, there was no content in the log file.
