### ISSUE TITLE
vscode keep complaining when i open arm template in macOS m1

### ISSUE THREAD

**Issue by rockyyyswagger** [dotnet/vscode-dotnet-runtime#259]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /Users/gunasun/Library/Application Support/Code/logs/20210708T211746/exthost1/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1625759334936.txt. Note that this file may contain personal data.

There is nothing written in the above log file ! 
I have installed .NET Core 3.1 SDK (v3.1.410) - macOS x64 Installer! 
https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-3.1.410-macos-x64-installer

Still there is no luck !

**Comment by rockyyyswagger** [comment]
This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire failed
See '.NET Runtime' in the output window for more information.

**Comment by sfoslund** [comment]
Hi @rockyyyswagger, thanks for filing an issue. If you manually install the SDK you have to tell the extension by updating these settings: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#manually-installing-net
