### ISSUE TITLE
Can anyone help me with this

### ISSUE THREAD

**Issue by shubht99** [dotnet/vscode-dotnet-runtime#261]
Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; & 'c:\Users\Vaibhavi Tharval\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install scripts\dotnet-install.ps1' -InstallDir 
'powershell.exe' is not recognized as an internal or external command,
operable program or batch file.

 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; & 'c:\Users\Vaibhavi Tharval\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install scripts\dotnet-install.ps1' -InstallDir 
'powershell.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sfoslund** [comment]
@shubht99 it looks like powershell is not properly configured on your machine. Can you try adding powershell to the PATH and see if that helps? You can look at these instructions for help: https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr

**Comment by shubht99** [comment]
Thankyou, it worked @sfoslund
