### ISSUE TITLE
Failed to install .NET runtime v5.0.

### ISSUE THREAD

**Issue by gaknowles** [dotnet/vscode-dotnet-runtime#263]
**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: & : File C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1 cannot be loaded because its operation is blocked by software restriction policies, such as 
those created by using Group Policy.
At line:1 char:138
+ ... ::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode- ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: & : File C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1 cannot be loaded because its operation is blocked by software restriction policies, such as 
those created by using Group Policy.
At line:1 char:138
+ ... ::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode- ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

	at c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\extension.js:2:13778
	at processTicksAndRejections (internal/process/task_queues.js:93:5)om/en-US/privacystatement

**Comment by sfoslund** [comment]
@gaknowles it looks like the install scripts are failing to run because of a software restriction policy on your machine. Do you know of any such restrictions? If you aren't able to work around it you can also configure a manual installation of .NET: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#manually-installing-net

**Comment by gaknowles** [comment]
The machine in question is my personal machine, not a corporate one with group policies. So I know of no restrictions. It is part of the Windows Insider program running Windows 21H1 version 19043.1083. I have not worked much with software restrictions but will look around and see what I can find and ultimately try the manual installation you suggested and get back to you.

**Comment by gaknowles** [comment]
I was unable to do the manual install also. I get the error message "This app has been blocked for your protection". I failed to mention earlier this is a Windows 10 Home edition machine if that matters. I say that because it does not even have gpedit as an option to edit group policy.

**Comment by sfoslund** [comment]
You got that error when running the .NET installers downloaded from https://dotnet.microsoft.com/download? I've never seen that, but it's definitely an indication that there are some strict policies/ configurations.

**Comment by gaknowles** [comment]
Does anyone have any ideas on how to correct this issue?  I checked another laptop running the same version of Windows with the same Windows Security settings that work perfectly. Obviously, there is a setting somewhere I am missing, but for the life of me, I can not find it.

**Comment by gaknowles** [comment]
I found the issue and have fixed it.
