### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by AIGamer28100** [dotnet/vscode-dotnet-runtime#266]
- Issue Type: `Bug`
- Extension Name: `vscode-dotnet-runtime`
- Extension Version: `1.2.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.58.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 1387,
		"activateCallTime": 6,
		"activateResolvedTime": 17,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "msazurermtools.azurerm-vscode-tools",
				"_lower": "msazurermtools.azurerm-vscode-tools"
			},
			"activationEvent": "onLanguage:jsonc"
		}
	},
	"runtimeErrors": []
}
```

**Comment by sfoslund** [comment]
Hi @AIGamer28100, thanks for filing an issue. I'm going to close this for now as there is not enough information to be actionable, but please reopen with more information on what the error is. You can do this by following these instructions to report an issue: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#other-issues
