### ISSUE TITLE
.NET Framework Installation fails

### ISSUE THREAD

**Issue by jkbenotmane** [dotnet/vscode-dotnet-runtime#275]
.NET Installation fails out of unknown reason.

**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:25 Zeichen:3
+ if [ -t 1 ] && command -v tput > /dev/null; then
+   ~
"(" fehlt nach "if" in der "if"-Anweisung.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:25 Zeichen:5
+ if [ -t 1 ] && command -v tput > /dev/null; then
+     ~
Der Typname nach "[" fehlt.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:25 Zeichen:13
+ if [ -t 1 ] && command -v tput > /dev/null; then
+             ~~
Das Token "&&" ist in dieser Version kein g�ltiges Anweisungstrennzeichen.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:28 Zeichen:7
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+       ~
"(" fehlt nach "if" in der "if"-Anweisung.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:28 Zeichen:9
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+         ~
Der Typname nach "[" fehlt.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:28 Zeichen:26
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                          ~~
Das Token "&&" ist in dieser Version kein g�ltiges Anweisungstrennzeichen.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:28 Zeichen:30
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                              ~
Der Typname nach "[" fehlt.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:42 Zeichen:13
+ say_warning() {
+             ~
Nach "(" wurde ein Ausdruck erwartet.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:43 Zeichen:72
+ ... printf "%b\n" "${yellow:-}dotnet_install: Warning: $1${normal:-}" >&3
+                                                                        ~
Dateispezifikation nach dem Umleitungsoperator fehlt.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:43 Zeichen:72
+ ... printf "%b\n" "${yellow:-}dotnet_install: Warning: $1${normal:-}" >&3
+                                                                        ~
Das kaufm�nnische Und-Zeichen (&) ist nicht zul�ssig. Der &-Operator ist f�r eine zuk�nftige Verwendung reserviert. 
Verwenden Sie das kaufm�nnische Und-Zeichen in doppelten Anf�hrungszeichen ("&"), um es als Teil einer Zeichenfolge zu 
�bergeben.
Es wurden nicht alle Analysefehler berichtet. Korrigieren Sie die berichteten Fehler, und versuchen Sie es erneut.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:25 Zeichen:3
+ if [ -t 1 ] && command -v tput > /dev/null; then
+   ~
"(" fehlt nach "if" in der "if"-Anweisung.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:25 Zeichen:5
+ if [ -t 1 ] && command -v tput > /dev/null; then
+     ~
Der Typname nach "[" fehlt.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:25 Zeichen:13
+ if [ -t 1 ] && command -v tput > /dev/null; then
+             ~~
Das Token "&&" ist in dieser Version kein g�ltiges Anweisungstrennzeichen.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:28 Zeichen:7
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+       ~
"(" fehlt nach "if" in der "if"-Anweisung.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:28 Zeichen:9
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+         ~
Der Typname nach "[" fehlt.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:28 Zeichen:26
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                          ~~
Das Token "&&" ist in dieser Version kein g�ltiges Anweisungstrennzeichen.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:28 Zeichen:30
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                              ~
Der Typname nach "[" fehlt.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:42 Zeichen:13
+ say_warning() {
+             ~
Nach "(" wurde ein Ausdruck erwartet.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:43 Zeichen:72
+ ... printf "%b\n" "${yellow:-}dotnet_install: Warning: $1${normal:-}" >&3
+                                                                        ~
Dateispezifikation nach dem Umleitungsoperator fehlt.
In C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:43 Zeichen:72
+ ... printf "%b\n" "${yellow:-}dotnet_install: Warning: $1${normal:-}" >&3
+                                                                        ~
Das kaufm�nnische Und-Zeichen (&) ist nicht zul�ssig. Der &-Operator ist f�r eine zuk�nftige Verwendung reserviert. 
Verwenden Sie das kaufm�nnische Und-Zeichen in doppelten Anf�hrungszeichen ("&"), um es als Teil einer Zeichenfolge zu 
�bergeben.
Es wurden nicht alle Analysefehler berichtet. Korrigieren Sie die berichteten Fehler, und versuchen Sie es erneut.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 

	at c:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\extension.js:2:13778
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by sfoslund** [comment]
Thanks for filing an issue, I'm going to close this as a dup of https://github.com/dotnet/vscode-dotnet-runtime/issues/159
