### ISSUE TITLE
`There is not enough disk space on drive` error in dotnet install script

### ISSUE THREAD

**Issue by anthony-c-martin** [dotnet/vscode-dotnet-runtime#281]
This was originally reported by @mattallford as a comment under https://github.com/Azure/bicep/issues/2839. I've copied the comment text verbatim below:

Does this occur consistently? Yes
Repro steps:
Hi all,

I've just rebooted my machine overnight, which upgraded VS Code to the latest build, and now I'm getting a `Failed to install .NET runtime v.5.0. Source: Bicep (Extension)` error when trying to launch the Bicep language service in VS Code.

The output is as follows:

```
Downloading the .NET Runtime.
Downloading .NET version(s) 5.0.9 ........ Error!
Failed to download .NET 5.0.9:
Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; & 'c:\Users\MatthewAllford\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install scripts\dotnet-install.ps1' -InstallDir 'c:\Users\MatthewAllford\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\5.0.9' -Version 5.0.9 -Runtime dotnet }
There is not enough disk space on drive C:
At C:\Users\MatthewAllford\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1:1070 char:5
+     throw "There is not enough disk space on drive ${installDrive}:"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (There is not en...ace on drive C::String) [], RuntimeException
    + FullyQualifiedErrorId : There is not enough disk space on drive C:
```

I've had a look at the `dotnet-install.ps1` scipr, and on line 1070, it is running:

```
try{
    $diskInfo = Get-PSDrive -Name $installDrive
}
catch{
    Say-Warning "Failed to check the disk space. Installation will continue, but it may fail if you do not have enough disk space."
}

if ( ($diskInfo -ne $null) -and ($diskInfo.Free / 1MB -le 100)) {
    throw "There is not enough disk space on drive ${installDrive}:"
}
```

I've noticed that in Windows PowerShell, `Get-PSDrive -Name C` doesn't return values for the `Free` property:

```
Get-PSDrive -Name C | select *


Used            : 0
Free            :
CurrentLocation : WINDOWS\system32
Name            : C
Provider        : Microsoft.PowerShell.Core\FileSystem
Root            : C:\
Description     : Windows
MaximumSize     :
Credential      : System.Management.Automation.PSCredential
DisplayRoot     :
```

But in PowerShell 7, it does:
```
get-psdrive -name C | select *

Used                   : 178563493888
Free                   : 844531826688
CurrentLocation        : Users\MatthewAllford\Documents\gitrepos
Name                   : C
Provider               : Microsoft.PowerShell.Core\FileSystem
Root                   : C:\
Description            : Windows
MaximumSize            :
Credential             : System.Management.Automation.PSCredential
DisplayRoot            :
VolumeSeparatedByColon : True
```

I've tried reinstalling the Bicep extension in VS Code. I also tried running the `dotnet-install.ps1` from PowerShell 7, which seems to run and install OK, and the dotnet files exist down in `C:\Users\MatthewAllford\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\5.0.9`,  but when re-launching VS Code, it tries to rerun the installation and fails again there. It looks like when re-launching VS Code, it starts the script again, which removes the `C:\Users\MatthewAllford\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\5.0.9` folder and recreates it, and then isn't able to install dotnet due to the error being thrown about there not being enough disk space (even though there is).

Any ideas?

Action: bicep.activate
Error type: Error
Error Message: Failed to install redacted:url runtime v5.0.

Version: 0.4.613
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.59.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:1930344extension.js:2:1930344
o extension.js:2:1919521
```

</details>

**Comment by baronfel** [comment]
This will need to be solved by the install-scripts - the relevant issue is https://github.com/dotnet/install-scripts/issues/374. I'm going to close this as a duplicate in the meantime. When install-scripts resolves that issue this extension will seamlessly download the new version.
