### ISSUE TITLE
Error when opening SSH host

### ISSUE THREAD

**Issue by gauss256** [dotnet/vscode-dotnet-runtime#285]
**Repro steps:**

1. Open SSH host in new window
2. Command issued from VSCode in Windows 10, SSH target computer is Ubuntu 20.04

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.17" -Version 3.1.17 -Runtime dotnet
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.17" -Version 3.1.17 -Runtime dotnet
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/extension.js:2:13778

**Comment by sfoslund** [comment]
Hi @gauss256, thanks for filing an issue. I'm going to close this for now as there is not enough information to be actionable, but please reopen with more information on what the error is. You can do this by pasting in the information copied to your clipboard when you made this issue and attaching the log file listed in the issue body. Thanks!
