### ISSUE TITLE
Failed to install .NET runtime v5.0 WSL

### ISSUE THREAD

**Issue by asilverman** [dotnet/vscode-dotnet-runtime#289]
```bash
Downloading the .NET Runtime.
Downloading .NET version(s) 5.0.9 ... Error!
Failed to download .NET 5.0.9:
Command failed: "/home/asilverman/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/asilverman/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/5.0.9" -Version 5.0.9 -Runtime dotnet
/home/asilverman/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected


 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: "/home/asilverman/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/asilverman/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/5.0.9" -Version 5.0.9 -Runtime dotnet
/home/asilverman/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected
```

**Comment by khashayarnazari** [comment]
> ```shell
> Downloading the .NET Runtime.
> Downloading .NET version(s) 5.0.9 ... Error!
> Failed to download .NET 5.0.9:
> Command failed: "/home/asilverman/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/asilverman/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/5.0.9" -Version 5.0.9 -Runtime dotnet
> /home/asilverman/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected
> 
> 
>  Error!
> .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/asilverman/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/asilverman/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/5.0.9" -Version 5.0.9 -Runtime dotnet
> /home/asilverman/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected
> ```

**Comment by sfoslund** [comment]
Looks like a dup of https://github.com/dotnet/vscode-dotnet-runtime/issues/159, tracking there...
