### ISSUE TITLE
Got error with ARM tools extension: This extension requires .NET Core for full functionality, 

### ISSUE THREAD

**Issue by leondelyon3** [dotnet/vscode-dotnet-runtime#294]
When creating an arm template got the following error:
This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. 

**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Cannot set property. Property setting is supported only on core types in this language mode.
At line:1 char:5
+ & { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointMa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertySetterNotSupportedInConstrainedLanguage
 
C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1 : Cannot invoke method. Method invocation is supported only on core types in this language 
mode.
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools.v ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [dotnet-install.ps1], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage,dotnet-install.ps1
 

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Cannot set property. Property setting is supported only on core types in this language mode.
At line:1 char:5
+ & { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointMa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertySetterNotSupportedInConstrainedLanguage
 
C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\install 
scripts\dotnet-install.ps1 : Cannot invoke method. Method invocation is supported only on core types in this language 
mode.
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools.v ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [dotnet-install.ps1], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage,dotnet-install.ps1
 

	at c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.2.0\dist\extension.js:2:13778
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
Please attach the log file located at c:\Users\charpenay\AppData\Roaming\Code\logs\20210909T114404\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1631180647445.txt. Note that this file may contain personal data.

**Result of dotnet --info:**
C:\Program Files\dotnet>dotnet --info

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Version Visual Studio code: 1.60**
**Version of extension ARM tools: 0.15.2**

**Comment by leondelyon3** [comment]
FYI log file is empty.

**Comment by sfoslund** [comment]
@leondelyon3 based on the error message it looks like you have powershell in constrained language mode. Can you try switching to full language mode to see if this fixes the issue?

**Comment by leondelyon3** [comment]
good catch! It works with full language support.
Thanks a lot.
