### ISSUE TITLE
.net 5 installation crash on VS Code 1.60.2

### ISSUE THREAD

**Issue by mohitvaid** [dotnet/vscode-dotnet-runtime#305]
**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.3.0\dist\install scripts\dotnet-install.ps1 
: Exception calling "ExtractToFile" with "3" argument(s): "The process cannot access the file 'C:\Users\anonymous\AppData\
Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\5.0.10\dotnet.exe' because it is being 
used by another process."
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vsco ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [dotnet-install.ps1], MethodInvocationException
    + FullyQualifiedErrorId : IOException,dotnet-install.ps1
 

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.3.0\dist\install scripts\dotnet-install.ps1 
: Exception calling "ExtractToFile" with "3" argument(s): "The process cannot access the file 'C:\Users\anonymous\AppData\
Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\5.0.10\dotnet.exe' because it is being 
used by another process."
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vsco ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [dotnet-install.ps1], MethodInvocationException
    + FullyQualifiedErrorId : IOException,dotnet-install.ps1
 

	at c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.3.0\dist\extension.js:2:13778
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by sfoslund** [comment]
> The process cannot access the file 'C:\Users\anonymous\AppData
Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime.dotnet\5.0.10\dotnet.exe' because it is being
used by another process.

It looks like dotnet.exe was locked while the extension was trying to update. Is this happening repeatedly?
