### ISSUE TITLE
Problems with C

### ISSUE THREAD

**Issue by Propagandate** [dotnet/vscode-dotnet-runtime#329]
I´m having a problem with the c++ editor and i´ve already installed all the feactured things to create c++ files..
How do i fix these??
![Sem Título](https://user-images.githubusercontent.com/93724526/140389679-8b0d857d-e640-4d19-bd87-051dec9a8cb0.png)

**Comment by sfoslund** [comment]
@Propagandate this repo contains the vscode-dotnet-sdk/runtime extensions, which manage installing .NET bundles. I think the problem you're having is with C++ tooling, so I would try filing an issue on this repo instead: https://github.com/microsoft/vscode-cpptools

**Comment by Propagandate** [comment]
> @Propagandate this repo contains the vscode-dotnet-sdk/runtime extensions, which manage installing .NET bundles. I think the problem you're having is with C++ tooling, so I would try filing an issue on this repo instead: https://github.com/microsoft/vscode-cpptools

Soo im kinda new in this subject... still learning how to do it... Can you give me a deeper explanation?

**Comment by sfoslund** [comment]
This is the wrong repo to file this issue, we don't work with C++ tools so we can't help you with this question. I recommend filing an issue at another repo, https://github.com/microsoft/vscode-cpptools looks like it might be the right place to do so.
