### ISSUE TITLE
M1 Pro Mac .net errors.

### ISSUE THREAD

**Issue by sualehasif** [dotnet/vscode-dotnet-runtime#330]
.Net Error on m1-pro machine with the following result

**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.3.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.20" -Version 3.1.20 -Runtime dotnet
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.20
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.3.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.20" -Version 3.1.20 -Runtime dotnet
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.20
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

    at /Users/anonymous/.vscode/extensions/vscode-dotnet-runtime-library/dist/Acquisition/DotnetCoreAcquisitionWorker.js:85:27

**Comment by sfoslund** [comment]
@sualehasif .NET 3.1 is not supported on arm64 machines. Do you know which extension is requesting the 3.1 runtime? If so, I recommend filing an issue with them asking them to upgrade to .NET 6 once it becomes available.

**Comment by ndelangen** [comment]
Unsure if there's any new information in here, maybe it helps:

Downloading the .NET Runtime.
Downloading .NET version(s) 3.1.21 ...... Error!
Failed to download .NET 3.1.21:
Command failed: "/Users/me/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.3.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/me/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.21" -Version 3.1.21 -Runtime dotnet
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.21
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support


 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/me/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.3.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/me/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.21" -Version 3.1.21 -Runtime dotnet
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.21
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

---



**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.3.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtianonymous/.dotnet/3.1.21" -Version 3.1.21 -Runtianonymous dotnet
dotnet_install: Error: Could not find `.NET Core Runtianonymous` with version = 3.1.21
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.3.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtianonymous/.dotnet/3.1.21" -Version 3.1.21 -Runtianonymous dotnet
dotnet_install: Error: Could not find `.NET Core Runtianonymous` with version = 3.1.21
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

	at /Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.3.0/dist/extension.js:2:13778

**Comment by sfoslund** [comment]
@ndelangen do you know what extension is calling into this extension to install .NET? This extension just installs any version of .NET that is requested, and this issue here is that the requesting extension is asking for a version of .NET that isn't supported on M1's. If you know what extension is requesting the version, I recommend filing an issue with them.

**Comment by sfoslund** [comment]
It looks like msazurermtools.azurerm-vscode-tools is the most common culprit of this error. @StephenWeatherford do you have any plans to update this extension to use .NET 6, so that it will support M1 devices?

**Comment by StephenWeatherford** [comment]
Yes, will be doing it soon, probably next week.
