### ISSUE TITLE
.NET Runtime is downloaded / installed every time

### ISSUE THREAD

**Issue by josetr** [dotnet/vscode-dotnet-runtime#331]
`const result = await vscode.commands.executeCommand('dotnet.acquire', { version: '3.1', requestingExtensionId });`

```
Downloading the .NET Runtime.
 Error!
ENOENT: no such file or directory, scandir '%userprofile%\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\3.1.20\sdk'

Downloading .NET version(s) 3.1.20 ..... Done!
.NET 3.1.20 executable path: %userprofile%\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\3.1.20\dotnet.exe
```

It happens every time VSCode is restarted. It doesn't happen if I execute the `dotnet.acquire` command twice in a row.

**Comment by josetr** [comment]
Changed the issue title. Added the following workaround and I managed to get rid of the 'sdk' error but the .NET Runtime is still downloaded every time.

```ts
const dotnetDir = path.dirname(dotnetPath)
const dotnetSdkDir = path.join(dotnetDir, 'sdk')

if (!fs.existsSync(dotnetSdkDir))
    fs.mkdirSync(dotnetSdkDir)
```

**Comment by sfoslund** [comment]
@josetr I think this might be the expected behavior. Based on the number of dots, it looks like this 'download' doesn't take too long, is that right? Usually, when the runtime is really being installed, it can take up to 2 minutes. So it looks like what's happening here is that when it says that it's downloading .NET, it's really checking that .NET is installed and checking that it is up to date.

**Comment by josetr** [comment]
The "downloading .NET" message seems pretty misleading then and probably should be changed.

The reason why I thought it was being downloaded over and over is that the acquire command takes 1.5 seconds to complete in my Ubuntu VM and 750ms on my main PC.

What's happening exactly that takes that long? Is it checking every file to see if one is corrupted?

I'm also now getting the error `"Failed to run .NET runtime. You may be missing key Linux libraries. Install them now?"` in my Ubuntu VM which is a bit misleading once again because if I just close it by clicking on 'Cancel', my dotnet app will run without any problems.

**Comment by sfoslund** [comment]
Thanks for your feedback, yes, we could probably update that string. 

> What's happening exactly that takes that long? Is it checking every file to see if one is corrupted?

The most significant operation is checking if the current version of the runtime is up to date. That involves going to the internet to get the latest version of .NET, which is probably why it's taking ~ a second.

**Comment by josetr** [comment]
https://github.com/dotnet/vscode-dotnet-runtime/blob/ce4a5bc5cb69e3a01d862afcfbe3f6c3cdc60d84/vscode-dotnet-sdk-extension/src/extension.ts#L133

Can we get this command available for the `vscode-dotnet-runtime-extension` extension as well?

I don't need the latest dotnet update. I just want the version that I've specified as quick as possible.

Every time there is an update the user will have to wait for it till it's downloaded, even tho there is already one dotnet runtime available that I could use in the meantime.

Why not give me the dotnet runtime that is available and works for me and then download / install the update in the background?

**Comment by sfoslund** [comment]
> Can we get this command available for the vscode-dotnet-runtime-extension extension as well?

I don't see any blockers off the top of my head, so I'll mark this issue as a feature request. 

> Why not give me the dotnet runtime that is available and works for me and then download / install the update in the background?

The existing runtime is still installed/ available when we're checking for updates, so the general idea is that an extension can cache the path to the runtime if they need it and we recommend they call the acquire command again on extension startup (or some other, similarly regular but non-intrusive trigger) so that runtime can be updated as updates become available. 

It might be helpful if you give me a little information about your scenario?

**Comment by josetr** [comment]
I can do the caching, in fact, that's the first thing I did. However, at some point, it's gonna be invalidated if I use a newer runtime so I'll need to check for that. This is repeated work that the `vscode-dotnet-runtime` is already supposed to do for me consistently. Then if I run the 'acquire' command without waiting for it to get the update in the background the 'Downloading' message will show up even if no new runtime is downloaded / installed.

> It might be helpful if you give me a little information about your scenario?

https://josetr.github.io/cmakels/ is the web version of the extension I'm gonna release for VSCode. Developers hate delays when showing up Intellisense / Semantic Highlightning so I'm trying hard to avoid any kind of delays.

**Comment by gulbanana** [comment]
I have a similar issue in this extension: https://github.com/gulbanana/thousand-vscode
It too uses a language server written in C# (https://github.com/gulbanana/thousand/tree/master/Thousand.LSP). I'd love to be able to specify that I need (for example) .NET 5.0, then have the .NET Install tool inform me that it's already installed *without* having to slowly connect to the net first. 
I'm also in Australia, where our internet speed is not always the best :)

**Comment by sfoslund** [comment]
Okay, thanks for the feedback. I'll take a look and see how hard it would be to add the acquireStatus command to the runtime extension.
