### ISSUE TITLE
.NET 5.0 Runtime

### ISSUE THREAD

**Issue by vLGrok** [dotnet/vscode-dotnet-runtime#333]
**Repro steps:**

1.  5.0 is installed and working.  However opening VSCode reports issues with it.
2. C:\Windows\system32>dotnet --version
5.0.403
3. Start up VSCode
4. "ILSpy won't work without a .NET 5.0 runtime."
5. An error occurred while installing .NET (5.0): .NET Acquisition Failed: EPERM: operation not permitted, unlink 'c:\Users\codeG\AppData\Roaming\Code - Insiders\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\5.0.12\dotnet.exe'
6. I have uninstalled, restarted Windows, and reinstalled .NET 5.0 SDK latest.
7. Issues persist.

The attached file was empty ("DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1636469304620.txt") so added some text and uploaded anyway.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.3.0\dist\install 
scripts\dotnet-install.ps1 : Exception calling "ExtractToFile" with "3" argument(s): "The process cannot access the 
file 'C:\Users\anonymous\AppData\Roaming\Code - 
Insiders\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\5.0.12\dotnet.exe' because it is being used 
by another process."
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\anonymous\.vscode-insiders\extensions\ms-dotnetto ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [dotnet-install.ps1], MethodInvocationException
    + FullyQualifiedErrorId : IOException,dotnet-install.ps1
 

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.3.0\dist\install 
scripts\dotnet-install.ps1 : Exception calling "ExtractToFile" with "3" argument(s): "The process cannot access the 
file 'C:\Users\anonymous\AppData\Roaming\Code - 
Insiders\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\5.0.12\dotnet.exe' because it is being used 
by another process."
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\anonymous\.vscode-insiders\extensions\ms-dotnetto ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [dotnet-install.ps1], MethodInvocationException
    + FullyQualifiedErrorId : IOException,dotnet-install.ps1
 

	at c:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.3.0\dist\extension.js:2:13778
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\codeG\AppData\Roaming\Code - Insiders\logs\20211109T094817\exthost2\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1636469304620.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly 
[DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1636469304620.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/7505636/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1636469304620.txt)
viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by sfoslund** [comment]
> dotnet.exe' because it is being used by another process."

It looks like an update failed because .NET was in use. I expect this should be a transient issue, are you seeing it regularly?
