### ISSUE TITLE
Configuration problem.

### ISSUE THREAD

**Issue by Owing1978** [dotnet/vscode-dotnet-runtime#353]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\Owing\AppData\Roaming\Code\logs\20211121T191559\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1637518629910.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by Owing1978** [comment]
The log located at c:\Users\Owing\AppData\Roaming\Code\logs\20211121T191559\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1637518629910.txt. Is empty so I can't attach it.

**Comment by sfoslund** [comment]
Hi @myhomehost, thanks for filing an issue. I'm going to close this for now as there is not enough information to be actionable, but please reopen with more information on what the error is. You can do this by pasting in the information copied to your clipboard when you made this issue. Thanks!
