### ISSUE TITLE
Just installed Bicep VsCode ext, it tried to install .NET 6 - and this is what happened

### ISSUE THREAD

**Issue by scale-tone** [dotnet/vscode-dotnet-runtime#384]
**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install scripts\dotnet-install.ps1' -InstallDir 'c:\Users\anonymous\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\6.0.1' -Version 6.0.1 -Runtime dotnet }
There is not enough disk space on drive C:
At C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:1091 char:5
+     throw "There is not enough disk space on drive ${installDrive}:"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (There is not en...ace on drive C::String) [], RuntimeException
    + FullyQualifiedErrorId : There is not enough disk space on drive C:
 

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install scripts\dotnet-install.ps1' -InstallDir 'c:\Users\anonymous\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\6.0.1' -Version 6.0.1 -Runtime dotnet }
There is not enough disk space on drive C:
At C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:1091 char:5
+     throw "There is not enough disk space on drive ${installDrive}:"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (There is not en...ace on drive C::String) [], RuntimeException
    + FullyQualifiedErrorId : There is not enough disk space on drive C:
 

    at c:\Users\anonymous\.vscode\extensions\vscode-dotnet-runtime-library\dist\Acquisition\DotnetCoreAcquisitionWorker.js:89:27

***

Log file located at c:\Users\<my-name>\AppData\Roaming\Code\logs\20220112T222502\exthost9\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1642632623728.txt 
**is empty**.

Also this:
![image](https://user-images.githubusercontent.com/5447190/150231769-2a1f1ee1-0673-4fa1-8fc3-74c55ecce3c3.png)

**Comment by baronfel** [comment]
This should be fixed with the new version of the install scripts, which should be published tomorrow.
