### ISSUE TITLE
Editing Arm on M1 Mac - fails

### ISSUE THREAD

**Issue by MiguelElGallo** [dotnet/vscode-dotnet-runtime#389]
Trying to edit ARM in M1 macs fails with the following, on the same machine I can edit BICEP using .net 5 or .net 6

Downloading the .NET Runtime.
Using configured .NET path: /usr/local/share/dotnet/dotnet
Downloading the .NET Runtime.
Downloading .NET version(s) 3.1.22 .......... Error!
Failed to download .NET 3.1.22:
Command failed: "/Users/xxxxxxxxxxx/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users......../Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.22" -Version 3.1.22 -Runtime dotnet
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.22
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

**Comment by gfs** [comment]
There likely isn't an appropriate build for .NET 3.1.2 for ARM Macs. Have you tried updating the version you're requesting to the latest (currently 6.0.1)?
