### ISSUE TITLE
Failed to download .NET 6.0.1: .NET installation timed out.  Error! .NET Acquisition Failed: Installation failed: Error: .NET installation timed out.

### ISSUE THREAD

**Issue by laurynxrobson** [dotnet/vscode-dotnet-runtime#391]
I keep getting this error message and I've tried uninstalling and reinstalling the .NET  6.0.1 SDKs, the extensions and VS Code. I've also tried manually installing .NET and installing script timeouts but the error message still persists. Please help. 
The issue text was copied to the clipboard.  Please paste it into this window.
![NET Acquisition Failed -- Error](https://user-images.githubusercontent.com/62890671/151033895-3c8ae981-7682-4075-a1ce-ce598d0190e2.png)
Please attach the log file located at c:\Users\laury\AppData\Roaming\Code\logs\20220125T195414\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1643133262916.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by whbxs** [comment]
Have you solved your problem?I have encountered the same problem. If you solve it, can you tell me the solution?

**Comment by BGMyang** [comment]
Me too

**Comment by ZengHugh** [comment]
可以参照手动添加扩展插件json设置解决，详见https://github.com/dotnet/vscode-dotnet-runtime/issues/707
