### ISSUE TITLE
.NET Acquisition Failed: Installation failed: tar: Failed to set default locale

### ISSUE THREAD

**Issue by StephenWeatherford** [dotnet/vscode-dotnet-runtime#397]
**Repro steps:**

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: tar: Failed to set default locale

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: tar: Failed to set default locale

	at /Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/extension.js:2:13750

> Please attach the log file located at /Users/stephenweatherford/Library/Application Support/Code - Insiders/logs/20220209T125230/exthost5/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1644440441936.txt. Note that this file may contain personal data.

This file is empty on my desk

**Comment by StephenWeatherford** [comment]
.NET Output window:

```
Downloading the .NET Runtime.
Downloading .NET version(s) 6.0.2 ......... Error!
Failed to download .NET 6.0.2:
tar: Failed to set default locale


 Error!
.NET Acquisition Failed: Installation failed: tar: Failed to set default locale
```

<img width="496" alt="image" src="https://user-images.githubusercontent.com/6913354/153291376-0829ca30-1a45-4afb-a0cf-b46447c16d42.png">

**Comment by StephenWeatherford** [comment]
Also happens with other .NET versions.  E.g. from ARM Tools extension:
```
Downloading the .NET Runtime.
Downloading .NET version(s) 3.1.22 ......... Error!
Failed to download .NET 3.1.22:
tar: Failed to set default locale


 Error!
.NET Acquisition Failed: Installation failed: tar: Failed to set default locale
```

**Comment by sihde** [comment]
I'm seeing the exact same thing. In my case the Bicep extension has triggered the attempted .NET install.

The log file mentioned is zero bytes for me as well (`/Users/sihde/Library/Application Support/Code - Insiders/logs/20220209T161737/exthost1/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1644452259957.txt`).

Same error in the output window:

```
Downloading the .NET Runtime.
Downloading .NET version(s) 6.0.2 ....... Error!
Failed to download .NET 6.0.2:
tar: Failed to set default locale


 Error!
.NET Acquisition Failed: Installation failed: tar: Failed to set default locale
```

**Comment by StephenWeatherford** [comment]
@sihde I see this in Code Insiders (and only recently) but not in the released vscode.  Makes me wonder if somehow vscode-insiders somehow broke it.  Also, if I run the install scripts manually they work fine.

What versions of vscode are you using and does it repro on insiders and stable vscode?  Thx.

**Comment by sihde** [comment]
@StephenWeatherford , agreed it repros on Insiders but not the released version. I tested Insiders 1.65.0 from today's build and several earlier builds; they all failed. Released version 1.64.2 works OK. I'm on MacOS 12.2, US English.

Probably Code Insiders changed something about the execution environment such that tar is missing LANG or some LC_* variables or something like that, though I am not able to nail down what exactly causes tar to emit that error.

**Comment by sihde** [comment]
This is fixed as of the most recent Insiders build
```
Version: 1.65.0-insider (Universal)
Commit: 52e65499654de7525e30df3a8228b69320796bf5
Date: 2022-02-16T05:16:06.667Z
Electron: 16.0.9
Chromium: 96.0.4664.174
Node.js: 16.9.1
V8: 9.6.180.23-electron.0
OS: Darwin x64 21.3.0
```

**Comment by StephenWeatherford** [comment]
Yay!
