### ISSUE TITLE
Setting up project environment

### ISSUE THREAD

**Issue by carloslahrssen** [dotnet/vscode-dotnet-runtime#4]
Just to clarify, to run our own extension with the library and extension (excluding the sample) we just add the two folders (library and extension) to our project directory and then reference as a file dependency in our own projects package.json correct? 

On another note, is there support on a branch for acquiring dotnet for windows, linux and mac? If not what are the OS limitations. 

Thanks

**Comment by sfoslund** [comment]
Sorry for the very delayed response, this repo was private for several months. If you are looking to experiment with the extension you can find a preview .vsix [here](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-runtime). Note that we're in early testing at this point, so if you plan on leveraging the extension in production scenarios please let us know first. 

The extension supports windows, linux, and mac. Note that .NET has some [dependencies on linux](https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-linux), so we have [some support](https://github.com/dotnet/vscode-dotnet-runtime/blob/master/vscode-dotnet-runtime-library/src/Acquisition/DotnetCoreDependencyInstaller.ts) for prompting those installations as well.

**Comment by sfoslund** [comment]
Closing due to age.
