### ISSUE TITLE
PYTHON 

### ISSUE THREAD

**Issue by samman121** [dotnet/vscode-dotnet-runtime#436]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located atPython is not installed. Please download and install Python before using the extension. c:\Users\Microsoft\AppData\Roaming\Code\logs\20220414T131045\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1649922116365.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by samman121** [comment]
Python is not installed. Please download and install Python before using the extension.

**Comment by nagilson** [comment]
Please try installing the Python extension. If you encounter this issue again and need help just ping us and we'll reopen it.
