### ISSUE TITLE
vscode extension crashes

### ISSUE THREAD

**Issue by cveld** [dotnet/vscode-dotnet-runtime#461]
**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1 : Exception calling "ExtractToFile" with "3" argument(s): "The process cannot access the 
file 'C:\Users\anonymous\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\6.0.5\d
otnet.exe' because it is being used by another process."
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [dotnet-install.ps1], MethodInvocationException
    + FullyQualifiedErrorId : IOException,dotnet-install.ps1
 

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: C:\Users\anonymous\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1 : Exception calling "ExtractToFile" with "3" argument(s): "The process cannot access the 
file 'C:\Users\anonymous\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\6.0.5\d
otnet.exe' because it is being used by another process."
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\anonymous\.vscode\extensions\ms-dotnettools ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [dotnet-install.ps1], MethodInvocationException
    + FullyQualifiedErrorId : IOException,dotnet-install.ps1
 

    at c:\Users\anonymous\.vscode\extensions\vscode-dotnet-runtime-library\dist\Acquisition\DotnetCoreAcquisitionWorker.js:89:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by nagilson** [comment]
Please comment again if this occurred with only one instance of vscode and the extension running, elsewise that was the issue
