### ISSUE TITLE
.NET Acquisition Failed: Installation failed: Error: .NET installation timed out.

### ISSUE THREAD

**Issue by PJ986116392** [dotnet/vscode-dotnet-runtime#486]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\124\AppData\Roaming\Code\logs\20220615T220633\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1655302001039.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by PJ986116392** [comment]
[DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1655302001039.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/8910131/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1655302001039.txt)

**Comment by nagilson** [comment]
We're sorry to hear you're experiencing this issue. Thank you for following the steps to attach a file. The log file you attached appears to be empty. If you have one that has all personal data removed but is not an empty file, please do provide it. 

If there are any reproduction or context steps you can provide (such as OS and extension version number), please provide that as well. For now, I've closed the issue as we are getting these reports elsewhere; if your log file no longer exists, don't worry. We'll resolve it through another contact point. We will happily re-open it if you provide the file.
