### ISSUE TITLE
Unexpected path returned

### ISSUE THREAD

**Issue by sfoslund** [dotnet/vscode-dotnet-runtime#50]
See Original Issue: microsoft/vscode-azurearmtools#396

**Comment by sfoslund** [comment]
@cschertz @SergeiY are you still having the issue described in https://github.com/microsoft/vscode-azurearmtools/issues/396 with more recent versions of the extension? Thanks!

**Comment by cschertzmsft** [comment]
Have not encountered it in a while

**Comment by sfoslund** [comment]
Great, I'll close this issue then, please open a new issue if you have problems, thanks!
