### ISSUE TITLE
warning notification in vscode: ignoring .NET paths defined in settings.json

### ISSUE THREAD

**Issue by cgrama** [dotnet/vscode-dotnet-runtime#515]
In vscode, when using .NET install tool extension to install .NET runtime from another vsix extension,  a warning notification is shown with message: Ignoring .NET paths defined in settings.json .....
(1) Is this warning notification shown because ""dotnetAcquisitionExtension.existingDotnetPath" is not included in the settings ?
(2) Is every vsix extension using the .NET install tool extension expected to check if "dotnetAcquisitionExtension.existingDotnetPath" is included in settings.json and update the same to include the vsix extension's id in the settings, before trying to download/install a .NET runtime using the .NET install tool extension ?
(2) If not, is there a way to turn off this notification ?
(3) After the ".NET install tools for extension authors" downloads and installs a .NETCore runtime, will it add/update the  ""dotnetAcquisitionExtension.existingDotnetPath"  or is the vsix extension using the .NET install tool extension expected to add this setting to the vscode settings ?

**Comment by nagilson** [comment]
1)	No, it is in fact the opposite. 
`dotnetAcquisitionExtension.existingDotnetPath` is an optional setting that can be provided in the event that the extension is failing to acquire dotnet or an extension wants to use a local copy of dotnet that is, say, a specific version of .NET. Its usage is documented here: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#manually-installing-net 

2) It isn't expected to. This error appears when an extension that relies on our extension provides it so and does it incorrectly. Most likely the extension provided a .NET path, but it didn't provide the name of itself / the extension ID.  This means we could not map dotnet to the extension that needs it; you would need to ping the author of that extension, the above documentation should be helpful. If you want to disable this warning, there are two possible approaches. One is to fix the extension which relies on our extension and make it provide an ID. Are there any extensions you have that rely on our extensions you know of? If not, which extensions do you have installed? The second way which is easier is if the extension had supplied this setting in your settings.json you can remove it to prevent the warning. (Preferences: Open Settings (JSON))

3) No, the extension keeps its own record of the .NET paths, the dotnetAcquisitionExtension.existingDotnetPath setting is only for the users or extension developers if they want to do a special configuration.
