### ISSUE TITLE
Extension by visual studio code

### ISSUE THREAD

**Issue by lucianoCircelli** [dotnet/vscode-dotnet-runtime#541]
The issue text was copied to the clipboard.  Please paste it into this window.

**Repro steps:**

1.

**Extension Version:** 1.0.0
[DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1658598053837.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/9174320/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1658598053837.txt)

Please attach the log file located at c:\Users\lucia\AppData\Roaming\Code\logs\20220723T192604\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1658598053837.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by lucianoCircelli** [comment]
22_07_23 just after to install Visual Studio code on Alibis-one

**Comment by nagilson** [comment]
Closing for now but feel free to reopen. May you provide some more info to the problem you're facing and want fixed?
