### ISSUE TITLE
vs

### ISSUE THREAD

**Issue by ayan8092** [dotnet/vscode-dotnet-runtime#568]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\ayank\AppData\Roaming\Code\logs\20220820T123958\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1660981372304.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by ayan8092** [comment]
vs code

**Comment by jmigual** [comment]
Just read the text FFS
