### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by akaraol** [dotnet/vscode-dotnet-runtime#573]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\user\AppData\Roaming\Code\logs\20220826T141313\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1661522253700.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by nagilson** [comment]
Closing for now but feel free to reopen. May you provide some more info to the problem you're facing and want fixed?
