### ISSUE TITLE
Bundle The Extension to Reduce CPU Usage

### ISSUE THREAD

**Issue by SivaNagaRaju-27** [dotnet/vscode-dotnet-runtime#588]
- Issue Type: `Performance`
- Extension Name: `vscode-dotnet-runtime`
- Extension Version: `1.5.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/tsnra/AppData/Local/Temp/ms-dotnettools.vscode-dotnet-runtime-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nagilson** [comment]
Basically, this is a request to increase the perf by bundling.
