### ISSUE TITLE
Connecting to WSL

### ISSUE THREAD

**Issue by softopti** [dotnet/vscode-dotnet-runtime#610]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /home/sbeliveau/.vscode-server/data/logs/20220926T114620/exthost2/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1664208469548.txt. Note that this file may contain personal data.

This file have 0 bytes

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by nagilson** [comment]
Closing for now but feel free to reopen. May you provide some more info to the problem you're facing and want fixed?
