### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by jojoChambana** [dotnet/vscode-dotnet-runtime#630]
- Issue Type: `Bug`
- Extension Name: `vscode-dotnet-runtime`
- Extension Version: `1.5.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by nagilson** [comment]
Closing for now but feel free to reopen. May you provide some more info to the problem you're facing and want fixed?
