### ISSUE TITLE
Issue in my system while installing

### ISSUE THREAD

**Issue by ChaithraGirish** [dotnet/vscode-dotnet-runtime#69]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\admin\AppData\Roaming\Code\logs\20200430T111219\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition1588257437996.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by sfoslund** [comment]
Hi @ChaithraGirish, thanks for filing an issue. Do you mind giving some more information on what the error is? You can do this by pasting in the information copied to your clipboard when you made this issue and attaching the log file listed in the issue body. Thanks!

**Comment by sfoslund** [comment]
@ChaithraGirish I'm closing this for now, but please reopen with more information on the error. Thanks!
