### ISSUE TITLE
下载.NET失败： Acquisition Failed: Installation failed: Error: .NET installation timed out

### ISSUE THREAD

**Issue by tidys** [dotnet/vscode-dotnet-runtime#707]
![image](https://user-images.githubusercontent.com/7894208/211748099-3ebc4629-3d75-49a0-bf86-c608f513ca5d.png)

解决办法：
- 手动下载[dotnet](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)，然后安装到你的电脑上，比如：`C:\\Program Files (x86)\\dotnet\\dotnet.exe`
- vscode中设置：`"dotnetAcquisitionExtension.existingDotnetPath": "C:\\Program Files (x86)\\dotnet\\dotnet.exe"`

如果你使用到了`CMake Language Support`插件，如下设置也能解决问题：

`"cmake.languageSupport.dotnetPath": "C:\\Program Files (x86)\\dotnet\\dotnet.exe"`

**Comment by szp11** [comment]
mac os中如何解决呢？

**Comment by tidys** [comment]
我是使用cmake遇到了这个问题，mac你下载这个试试吧

![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/7894208/3e36ade6-b81f-4b9b-87eb-716feffa2670)

**Comment by szp11** [comment]
"dotnetAcquisitionExtension.existingDotnetPath": [
        {"extensionId": "msazurermtools.azurerm-vscode-tools", "path": "/usr/local/share/dotnet/dotnet"}
    ]
我设置了，但不起作用！打开后它还是在下载.NET version(s) 7.0.9，下载不成功，我用都用不了！

**Comment by tidys** [comment]
触发这个逻辑的相关[代码](https://github.com/dotnet/vscode-dotnet-runtime/blob/2b3b7402e3a31bfb5f3ae0c4347be2a061c6d707/vscode-dotnet-runtime-library/src/Acquisition/DotnetCoreAcquisitionWorker.ts#L151)：
```c#
const installContext = {
    installDir: dotnetInstallDir,
    version,
    dotnetPath,
    timeoutValue: this.timeoutValue,
    installRuntime,
} as IDotnetInstallationContext;
this.context.eventStream.post(new DotnetAcquisitionStarted(version));
await this.context.acquisitionInvoker.installDotnet(installContext).catch((reason) => {
    throw Error(`Installation failed: ${reason}`);
});
```
[installDotnet](https://github.com/dotnet/vscode-dotnet-runtime/blob/2b3b7402e3a31bfb5f3ae0c4347be2a061c6d707/vscode-dotnet-runtime-library/src/Acquisition/AcquisitionInvoker.ts#L33)

可以自己把源代码下载下来，试着调试下着段代码，我也忘了当时是怎么解决的了

**Comment by ZengHugh** [comment]
参照https://github.com/dotnet/vscode-dotnet-runtime/issues/1159页面orange-pig的回答，在扩展.NET Install Tool for Extention扩展插件设置里面添加（add the follow config to vscode settings.json）
"dotnetAcquisitionExtension.existingDotnetPath": [
    {
        "extensionId": "ms-dotnettools.csdevkit",
        "path": "C:\\Program Files\\dotnet\\dotnet.exe"
    },
    {
        "extensionId": "ms-dotnettools.vscodeintellicode-csharp",
        "path": "C:\\Program Files\\dotnet\\dotnet.exe"
    },
    {
        "extensionId": "ms-dotnettools.csharp",
        "path": "C:\\Program Files\\dotnet\\dotnet.exe"
    },
    {
        "extensionId": "ms-dotnettools.vscode-dotnet-runtime",
        "path": "C:\\Program Files\\dotnet\\dotnet.exe"
    }
],

**Comment by tidys** [comment]
https://github.com/dotnet/vscode-dotnet-runtime/issues/1159
