### ISSUE TITLE
Allow other extensions to request a list of available SDK/Runtime versions

### ISSUE THREAD

**Issue by baronfel** [dotnet/vscode-dotnet-runtime#764]
We should add a new command, possibly called `listVersions`, that would allow other extensions to discover what recent versions of .NET SDK/Runtime are available. 

The API surface area should be:

```ts
export interface IDotnetListVersionsContext {

}

export interface IDotnetListVersionsResponse = IDotnetVersion[]

export interface IDotnetVersion {
	version: string,
        supportStatus: DotnetVersionSupportStatus,
        support-phase: DotnetVersionSupportPhase,
        channelVersion: string
        errorConfiguration?: AcquireErrorConfiguration;
} 

export type DotnetVersionSupportStatus = 'lts' | 'sts'; 
export type DotnetVersionSupportPhase = 'active' | 'preview' | 'eol' | 'maintenance' | 'go-live' ; 

```

We should only list in-support versions at any given time, and within a given major/minor we should only list the most recent versions.

**Comment by joeloff** [comment]
The releases.json library exposes proper enumerations https://github.com/dotnet/deployment-tools/blob/main/src/Microsoft.Deployment.DotNet.Releases/src/ReleaseType.cs
https://github.com/dotnet/deployment-tools/blob/main/src/Microsoft.Deployment.DotNet.Releases/src/SupportPhase.cs

**Comment by nagilson** [comment]
Thanks @joeloff, the current plan is indeed to make a GET request to the releases json manifest 😉

**Comment by nagilson** [comment]
@baronfel  By `version` I assume you mean the major.minor's `latest-sdk` for listing the SDKs and `latest-runtime` for runtimes?

**Comment by baronfel** [comment]
Yes - the `latest-sdk` and `latest-runtime` would be the useful data here, but across all in-support channels. So at this exact moment that would be the 6.0 and 7.0 channels' `latest-sdk` and `latest-runtime`.

**Comment by nagilson** [comment]
I've amended the proposal to include `support-phase` as we will be needing that I think

**Comment by joeloff** [comment]
> Yes - the `latest-sdk` and `latest-runtime` would be the useful data here, but across all in-support channels. So at this exact moment that would be the 6.0 and 7.0 channels' `latest-sdk` and `latest-runtime`.

Just be aware that the latest SDK is usually set to the highest feature band and patch, The concept is a bit vague because all the SDKs within a release are technically the latest patch for their respective bands

**Comment by joeloff** [comment]
@baronfel regarding this `export type DotnetVersionSupportPhase = 'active' | 'preview' | 'eol'; `  There are other phases (maintenance, preview and go-live). Should those not be included?

**Comment by baronfel** [comment]
Depends on use case - if the intent is a raw wrapper against the backing releases.json data, then sure, but I think this extension isn't quite as broad. Consumers probably just want to say "give me the latest stable SDK that my app will build with", for example. I'm leaning towards the latter for our first use cases because it's easier to 'widen' than it is to 'narrow' return values.

**Comment by nagilson** [comment]
> @joeloff  @baronfel regarding this `export type DotnetVersionSupportPhase = 'active' | 'preview' | 'eol'; ` There are other phases (maintenance, preview and go-live). Should those not be included?

I agree with @baronfel that these values wouldn't be used. However, I think it's good to include them as I (think) we could fail trying to cast the json string into a string that doexn't exist. So this is a really good catch, thanks!

**Comment by nagilson** [comment]
I've updated the spec to include the standard errorConfiguration pattern.

**Comment by nagilson** [comment]
omg why did I call it ` support-phase` when everything else is camel cased 💀
