### ISSUE TITLE
.NET Branding Pass

### ISSUE THREAD

**Issue by sfoslund** [dotnet/vscode-dotnet-runtime#85]
We need to to a branding pass to update instances of `.NET Core` to `.NET`. We should also update the sample extension's default version from 2.2 to a runtime version that is in support and update the channel output wording from `.NET tooling` to `.NET runtime` to reduce confusion.

**Comment by scottaddie** [comment]
@sfoslund Heads up that the `.NET tooling` to `.NET runtime` change was completed in https://github.com/dotnet/vscode-dotnet-runtime/pull/87.
