### ISSUE TITLE
<!-- IMPORTANT: Please be sure to remove any private information before submitting. -->  **Repro steps:**  1.  **Extension Version:** 0.1.2

### ISSUE THREAD

**Issue by jurgen1c** [dotnet/vscode-dotnet-runtime#89]

**Comment by sfoslund** [comment]
Hi @jurgen1c, thanks for filing an issue. I'm going to close this for now as there is not enough information to be actionable, but please reopen with more information on what the error is. You can do this by pasting in the information copied to your clipboard when you made this issue and attaching the log file listed in the issue body. Thanks!
