### ISSUE TITLE
I need some help resolving "Git bash exited with code 1 ( Compile Sass assets )" error on pushing below yml file to azure pipeline from VS code

### ISSUE THREAD

**Issue by hugo-0602** [dotnet/vscode-dotnet-runtime#91]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\lenovo\AppData\Roaming\Code\logs\20200531T010919\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition1590885686178.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by hugo-0602** [comment]
Find code below

# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: 'ubuntu-16.04'
  demands:
    - npm

variables:
  buildConfiguration: 'Release'
  
steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.100'
  inputs:
    packageType: sdk
    version: 3.1.100

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'
[logs_6.zip](https://github.com/dotnet/vscode-dotnet-runtime/files/4706948/logs_6.zip)

**Comment by sfoslund** [comment]
It looks like this is an issue with azure pipelines, not the vscode-dotnet-runtime extension. Please file an issue there instead, if you file it under https://github.com/MicrosoftDocs/pipelines-dotnet-core they should be able to redirect you to the appropriate place.
