### ISSUE TITLE
errors when install new version omnisharp

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/vscode-dotnet-runtime#914]
error in output even though I have 200gb of disk space left

Downloading the .NET Runtime.
Downloading .NET version(s) 7.0.5 .............. Error!
Failed to download .NET 7.0.5:
Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; & 'd:\VSCode-win32-x64-1.78.2\data\extensions\ms-dotnettools.vscode-dotnet-runtime-1.6.0\dist\install scripts\dotnet-install.ps1' -InstallDir 'd:\VSCode-win32-x64-1.78.2\data\user-data\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.5' -Version 7.0.5 -Runtime dotnet }
There is not enough disk space on drive D:
At D:\VSCode-win32-x64-1.78.2\data\extensions\ms-dotnettools.vscode-dotnet-runtime-1.6.0\dist\install 
scripts\dotnet-install.ps1:1115 char:9
+         throw "There is not enough disk space on drive ${installDrive ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (There is not en...ace on drive D::String) [], RuntimeException
    + FullyQualifiedErrorId : There is not enough disk space on drive D:
 

 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; & 'd:\VSCode-win32-x64-1.78.2\data\extensions\ms-dotnettools.vscode-dotnet-runtime-1.6.0\dist\install scripts\dotnet-install.ps1' -InstallDir 'd:\VSCode-win32-x64-1.78.2\data\user-data\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.5' -Version 7.0.5 -Runtime dotnet }
There is not enough disk space on drive D:
At D:\VSCode-win32-x64-1.78.2\data\extensions\ms-dotnettools.vscode-dotnet-runtime-1.6.0\dist\install 
scripts\dotnet-install.ps1:1115 char:9
+         throw "There is not enough disk space on drive ${installDrive ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (There is not en...ace on drive D::String) [], RuntimeException
    + FullyQualifiedErrorId : There is not enough disk space on drive D:

**Comment by nagilson** [comment]
Sorry for the ping, David was able to give me the permissions. Thanks!

**Comment by NCLnclNCL** [comment]
> Looks like I don't have permissions to transfer. @nagilson are you able to make the transfer to vscode-dotnet-runtime? Seems to be a runtime acquisition error about disk space when they have 200gb free.

how to fix bro

**Comment by nagilson** [comment]
@NCLnclNCL What's the output of `Get-PSDrive -Name D` if you go to type that into powershell?

**Comment by NCLnclNCL** [comment]
> @NCLnclNCL What's the output of `Get-PSDrive -Name D` if you go to type that into powershell?

There is not enough disk space on drive D:

**Comment by NCLnclNCL** [comment]
> @NCLnclNCL What's the output of `Get-PSDrive -Name D` if you go to type that into powershell?

Name           Used (GB)     Free (GB) Provider      Root                                               CurrentLocation
----           ---------     --------- --------      ----                                               ---------------
D                                      FileSystem    D:\
oh it cannot get space

**Comment by nagilson** [comment]
It looks like this is a known issue in Powershell/The .NET Install Scripts repo. https://github.com/dotnet/sdk/issues/11400 
If you can update powershell on your system, I think it will fix your issue. Let me know if you encounter more issues. I think we could re-open the one I've linked for discussion as it wasn't fixed.
