### ISSUE TITLE
tools

### ISSUE THREAD

**Issue by paulsd2020** [dotnet/vscode-dotnet-runtime#92]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\Administrator\AppData\Roaming\Code\logs\20200601T004706\exthost4\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition1590933800791.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by sfoslund** [comment]
Hi @paulsd2020, thanks for filing an issue. I'm going to close this for now as there is not enough information to be actionable, but please reopen with more information on what the error is. You can do this by pasting in the information copied to your clipboard when you made this issue and attaching the log file listed in the issue body. Thanks!
