### ISSUE TITLE
sdk 

### ISSUE THREAD

**Issue by inbaraja272** [dotnet/vscode-dotnet-runtime#936]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\AP\AppData\Roaming\Code\logs\20230614T130309\window1\exthost\ms-dotnettools.vscode-dotnet-sdk\DotN
![Annotation 2023-06-14 131310](https://github.com/dotnet/vscode-dotnet-runtime/assets/57892706/495f2569-5a67-4e56-a65f-0d58f961a486)
etAcquisition-ms-dotnettools.vscode-dotnet-sdk-1686728379805.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by baronfel** [comment]
sdkmanager is an android concept, not something managed by this extension.
