### ISSUE TITLE
21ede

### ISSUE THREAD

**Issue by Raptus369** [dotnet/vscode-dotnet-runtime#97]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\Leif\AppData\Roaming\Code\logs\20200609T002014\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition1591658217109.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by sfoslund** [comment]
Hi @Raptus369, as with the other issue I'm going to close this one until you can provide more information. Thanks!
